#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using NUnit.Framework;

namespace Arena.Tests.Editor
{
    public sealed class CombatBuildV2Phase6Tests
    {
        private const string ContractPath =
            "docs/combat-build-v2-phase-0-contract-2026-08-29.json";
        private const string GeneratedClientPath =
            "Assets/Arena/Runtime/Generated/RehearsalHubV2SpacetimeDB/SpacetimeDBClient.g.cs";
        private const string RehearsalClientPath =
            "Assets/Arena/Runtime/Network/CombatBuildV2RehearsalClient.cs";
        private const string CanonicalHubClientPath =
            "Assets/Arena/Runtime/Network/HubNetworkManager.cs";

        [Test]
        public void RehearsalBindings_AreGeneratedAndIsolatedFromCanonicalHubClient()
        {
            string generated = File.ReadAllText(GeneratedClientPath);
            string rehearsal = File.ReadAllText(RehearsalClientPath);
            string canonical = File.ReadAllText(CanonicalHubClientPath);

            Assert.That(generated, Does.StartWith(
                "// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB."));
            Assert.That(generated, Does.Contain("namespace Arena.RehearsalHubV2Db"));
            Assert.That(rehearsal, Does.Contain(
                "private const string AllowedDatabasePrefix = \"arena-cbv2-p6-\";"));
            Assert.That(rehearsal, Does.Contain("uri.IsLoopback"));
            Assert.That(rehearsal, Does.Not.Contain("RuntimeInitializeOnLoadMethod"));
            Assert.That(canonical, Does.Not.Contain("RehearsalHubV2Db"));
            Assert.That(canonical, Does.Not.Contain("CombatBuildV2RehearsalClient"));
        }

        [Test]
        public void DirectActionInputIdentities_MatchLockedPhase0Contract()
        {
            string json = File.ReadAllText(ContractPath);
            string[] expected = Regex.Matches(
                    json,
                    "\\\"input_action_id\\\"\\s*:\\s*\\\"(COMBAT_ACTION_[0-9]{2})\\\"")
                .Cast<Match>()
                .Select(match => match.Groups[1].Value)
                .Distinct(StringComparer.Ordinal)
                .ToArray();

            Type contractType = AppDomain.CurrentDomain.Load("Assembly-CSharp")
                .GetType("Arena.Network.CombatBuildV2InputContract", throwOnError: true)!;
            PropertyInfo bindingsProperty = contractType.GetProperty(
                    "Bindings",
                    BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                ?? throw new InvalidOperationException("v2 input contract has no Bindings property");
            var actual = new List<string>();
            foreach (object binding in (IEnumerable)bindingsProperty.GetValue(null)!)
            {
                PropertyInfo actionProperty = binding.GetType().GetProperty(
                        "InputActionId",
                        BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                    ?? throw new InvalidOperationException("v2 binding has no InputActionId");
                actual.Add((string)actionProperty.GetValue(binding)!);
            }

            Assert.That(expected, Has.Length.EqualTo(18));
            Assert.That(actual, Is.EqualTo(expected));
        }
    }
}
