//! Arena instances and deterministic arena terrain.
//!
//! This module provides:
//! - Arena lifecycle (create/list/join/leave instance)
//! - Authoritative player world state
//! - Deterministic height sampling for server-side validation
#![allow(dead_code)]

use serde::Deserialize;
use spacetimedb::{reducer, table, Identity, ReducerContext, Table};
use std::f32::consts::TAU;
use std::sync::OnceLock;

use crate::actor_lifecycle::{despawn_actor_bundle, ActorDespawnOptions, ActorWorldCleanup};
// Import accessor traits (generated by #[table] macro, needed for ctx.db.table_name())
#[allow(unused_imports)]
use crate::arena::arena_instance as _;
#[allow(unused_imports)]
use crate::arena::player_open_world_scene as _;
#[allow(unused_imports)]
use crate::arena::player_world as _;
#[allow(unused_imports)]
use crate::combat::match_participant_stats as _;
use crate::combat::{clear_combat_engagement_for_identity, clear_statuses_for_identity};
use crate::combat::{
    emit_player_spawned, reset_player_state_to_spawn, DEFAULT_HIT_HEIGHT, DEFAULT_HIT_RADIUS,
};
#[allow(unused_imports)]
use crate::npcs::npc_instance as _;
use crate::open_world_scene::{
    default_open_world_scene_profile, is_known_open_world_scene, open_world_scene_profile_for_scene,
};
#[allow(unused_imports)]
use crate::player::player as _;
use crate::player_input::clear_pending_player_commands;
#[allow(unused_imports)]
use crate::player_input::player_command as _;
#[allow(unused_imports)]
use crate::player_input::player_input_cursor as _;
#[allow(unused_imports)]
use crate::player_intent::player_intent as _;
#[allow(unused_imports)]
use crate::player_physics::player_physics as _;
use crate::player_physics::{commit_player_physics, PhysicsWriteMode};
#[allow(unused_imports)]
use crate::player_state::player_state as _;
use crate::playground_targets::despawn_all_playground_targets_for_owner;
use crate::practice::{
    despawn_training_instance, is_training_instance, resolve_instance_spawn_override,
};
use crate::world_collision::{
    resolve_world_spawn_position_with_layout, resolve_world_spawn_position_with_layout_for_scene,
};

const DEFAULT_MAX_PLAYERS: u32 = 8;
const MIN_MAX_PLAYERS: u32 = 1;
const MAX_MAX_PLAYERS: u32 = 64;
const JS_SAFE_SEED_MASK: u64 = (1_u64 << 53) - 1;

const MIX_MUL_A: u64 = 0xff51_afd7_ed55_8ccd;
const MIX_MUL_B: u64 = 0xc4ce_b9fe_1a85_ec53;
const HASH_X_MUL: u64 = 0x9e37_79b9_7f4a_7c15;
const HASH_Z_MUL: u64 = 0xc2b2_ae3d_27d4_eb4f;

const NOISE_LARGE_SCALE: f64 = 38.0;
const NOISE_MEDIUM_SCALE: f64 = 19.0;
const NOISE_SMALL_SCALE: f64 = 9.0;

const NOISE_LARGE_WEIGHT: f64 = 3.2;
const NOISE_MEDIUM_WEIGHT: f64 = 1.4;
const NOISE_SMALL_WEIGHT: f64 = 0.6;
pub(crate) const COLLISION_EPSILON: f32 = 0.0001;
const TERRAIN_RAY_STEP: f32 = 0.5;
const TERRAIN_RAY_REFINEMENT_STEPS: usize = 8;
const WORLD_KIND_OPEN: &str = "OPEN";
const WORLD_KIND_INSTANCE: &str = "INSTANCE";
const LEGACY_OPEN_WORLD_DUMMY_ID_HEX: &str =
    "000000000000000000000000000000000000000000000000000000000000d00d";
pub(crate) const MATCH_PHASE_WAITING: &str = "WAITING";
pub(crate) const MATCH_PHASE_COUNTDOWN: &str = "COUNTDOWN";
pub(crate) const MATCH_PHASE_IN_PROGRESS: &str = "IN_PROGRESS";
pub(crate) const MATCH_PHASE_ENDED: &str = "ENDED";
const LEGACY_INSTANCE_DUMMY_PREFIX_HEX: &str = "00000000000000000000000000000000000000000000d00d";
const INSTANCE_PLAYER_SPAWN_RADIUS: f32 = 5.0;
const INSTANCE_PLAYER_SPAWN_RADIUS_JITTER: f32 = 1.2;

const ARENA_LAYOUT_JSON: &str = include_str!("arena_layout.shared.json");

#[derive(Clone, Copy, Deserialize)]
struct ArenaLayoutWallSegment {
    x: f32,
    z: f32,
    half_x: f32,
    half_z: f32,
}

#[derive(Clone, Copy, Deserialize)]
struct ArenaLayoutPoint {
    x: f32,
    z: f32,
}

#[derive(Clone, Copy, Deserialize)]
struct ArenaLayoutRamp {
    x: f32,
    z: f32,
    side: f32,
}

#[derive(Deserialize)]
struct ArenaLayoutConfig {
    arena_radius: f32,
    center_flatten_radius: f32,
    ruin_wall_height: f32,
    ruin_wall_segments: Vec<ArenaLayoutWallSegment>,
    platform_half_x: f32,
    platform_half_z: f32,
    platform_center_height_offset: f32,
    platform_half_height: f32,
    platforms: Vec<ArenaLayoutPoint>,
    ramp_half_x: f32,
    ramp_half_z: f32,
    ramp_center_height_offset: f32,
    ramp_half_height: f32,
    ramp_platform_link_x_offset: f32,
    ramp_rot_z_abs: f32,
    ramp_top_center_offset: f32,
    ramp_top_slope_delta: f32,
    ramps: Vec<ArenaLayoutRamp>,
    pillar_collider_radius: f32,
    pillar_count: usize,
    pillar_hash_step: u64,
}

fn arena_layout() -> &'static ArenaLayoutConfig {
    static ARENA_LAYOUT: OnceLock<ArenaLayoutConfig> = OnceLock::new();
    ARENA_LAYOUT.get_or_init(|| {
        serde_json::from_str(ARENA_LAYOUT_JSON)
            .expect("arena_layout.shared.json must remain valid and schema-compatible")
    })
}

#[table(accessor = arena_instance, public)]
pub struct ArenaInstance {
    #[primary_key]
    #[auto_inc]
    pub id: u64,
    pub seed: u64,
    pub max_players: u32,
    pub player_count: u32,
    pub phase: String,
    pub winner_id: Option<Identity>,
    pub ended_at: Option<spacetimedb::Timestamp>,
    pub is_practice: bool,
    pub countdown_started_at: Option<spacetimedb::Timestamp>,
}

#[table(accessor = player_world, public)]
pub struct PlayerWorld {
    #[primary_key]
    pub identity: Identity,
    pub world_kind: String,
    pub instance_id: Option<u64>,
    pub open_world_scene_name: String,
}

#[table(accessor = player_open_world_scene, public)]
pub struct PlayerOpenWorldScene {
    #[primary_key]
    pub identity: Identity,
    pub scene_name: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum ResolvedWorldContext {
    Open(String),
    Instance(u64),
}

#[reducer]
pub fn create_instance(ctx: &ReducerContext, max_players: u32) -> Result<(), String> {
    // Prevent creating a new instance while already in one.
    if let Some(world) = ctx.db.player_world().identity().find(ctx.sender()) {
        if world_kind_is_instance(world.world_kind.as_str()) {
            return Err("Already in an instance — leave before creating a new one".to_string());
        }
    }
    let max_players = sanitize_max_players(max_players);
    create_arena_instance(ctx, max_players);
    Ok(())
}

#[reducer]
pub fn list_open_instances(ctx: &ReducerContext) -> Result<(), String> {
    ensure_open_arena_exists(ctx);
    Ok(())
}

#[reducer]
pub fn join_instance(ctx: &ReducerContext, arena_id: u64) -> Result<(), String> {
    ensure_open_arena_exists(ctx);
    join_identity_into_instance(ctx, ctx.sender(), arena_id)
}

#[reducer]
pub fn start_match(ctx: &ReducerContext, arena_id: u64) -> Result<(), String> {
    let Some(mut arena) = ctx.db.arena_instance().id().find(arena_id) else {
        return Err(format!("Instance {arena_id} not found"));
    };

    if arena.is_practice || is_training_instance(ctx, arena_id) {
        return Err("Cannot start a practice instance as a match".to_string());
    }

    if arena.phase != MATCH_PHASE_WAITING {
        return Err("Match already started".to_string());
    }

    if arena.player_count < 2 {
        return Err("Need at least 2 players to start a match".to_string());
    }

    arena.phase = MATCH_PHASE_COUNTDOWN.to_string();
    arena.winner_id = None;
    arena.ended_at = None;
    arena.countdown_started_at = Some(ctx.timestamp);
    ctx.db.arena_instance().id().update(arena);
    Ok(())
}

#[reducer]
pub fn leave_instance(ctx: &ReducerContext) -> Result<(), String> {
    set_player_open_world(ctx, ctx.sender())
}

#[reducer]
pub fn set_open_world_scene(ctx: &ReducerContext, scene_name: String) -> Result<(), String> {
    if !is_known_open_world_scene(scene_name.as_str()) {
        return Err(format!("Unknown open-world scene '{scene_name}'"));
    }

    let scene_name = scene_name.as_str();
    despawn_all_playground_targets_for_owner(ctx, ctx.sender())?;
    upsert_player_open_world_scene(ctx, ctx.sender(), scene_name);

    if let Some(world) = ctx.db.player_world().identity().find(ctx.sender()) {
        if world_kind_is_open(world.world_kind.as_str()) {
            upsert_player_world(ctx, ctx.sender(), WORLD_KIND_OPEN, None);
            restore_player_to_open_world_spawn(ctx, ctx.sender())?;
        }
    }

    Ok(())
}

pub fn set_player_open_world(ctx: &ReducerContext, identity: Identity) -> Result<(), String> {
    despawn_all_playground_targets_for_owner(ctx, identity)?;
    clear_statuses_for_identity(ctx, identity);
    clear_combat_engagement_for_identity(ctx, identity);
    remove_identity_from_current_instance(ctx, identity)?;
    ensure_player_open_world_scene(ctx, identity);
    restore_player_to_open_world_spawn(ctx, identity)?;
    upsert_player_world(ctx, identity, WORLD_KIND_OPEN, None);
    Ok(())
}

pub fn backfill_player_world_rows(ctx: &ReducerContext) -> usize {
    let identities: Vec<Identity> = ctx
        .db
        .player()
        .iter()
        .map(|player| player.identity)
        .collect();
    let mut repaired = 0_usize;

    for identity in identities {
        let preferred_scene = ensure_player_open_world_scene(ctx, identity);
        if let Some(world) = ctx.db.player_world().identity().find(identity) {
            if player_world_needs_invariant_repair(&world, preferred_scene.as_str()) {
                upsert_player_world(ctx, identity, world.world_kind.as_str(), world.instance_id);
                repaired += 1;
            }
            continue;
        }

        upsert_player_world(ctx, identity, WORLD_KIND_OPEN, None);
        repaired += 1;
    }

    repaired
}

fn player_world_needs_invariant_repair(world: &PlayerWorld, preferred_scene_name: &str) -> bool {
    if world_kind_is_open(world.world_kind.as_str()) {
        return world.instance_id.is_some() || world.open_world_scene_name != preferred_scene_name;
    }

    if world_kind_is_instance(world.world_kind.as_str()) {
        return !world.open_world_scene_name.is_empty();
    }

    false
}

pub fn backfill_player_open_world_scene_rows(ctx: &ReducerContext) -> usize {
    let identities: Vec<Identity> = ctx
        .db
        .player()
        .iter()
        .map(|player| player.identity)
        .collect();
    let mut repaired = 0_usize;

    for identity in identities {
        if ctx
            .db
            .player_open_world_scene()
            .identity()
            .find(identity)
            .is_some()
        {
            continue;
        }

        ensure_player_open_world_scene(ctx, identity);
        repaired += 1;
    }

    repaired
}

pub fn clear_player_world(ctx: &ReducerContext, identity: Identity) -> Result<(), String> {
    clear_statuses_for_identity(ctx, identity);
    clear_combat_engagement_for_identity(ctx, identity);
    remove_identity_from_current_instance(ctx, identity)?;
    if ctx.db.player_world().identity().find(identity).is_some() {
        ctx.db.player_world().identity().delete(identity);
    }
    Ok(())
}

pub fn remove_player_from_arena(ctx: &ReducerContext, identity: Identity) -> Result<(), String> {
    remove_identity_from_current_instance(ctx, identity)
}

fn remove_identity_from_current_instance(
    ctx: &ReducerContext,
    identity: Identity,
) -> Result<(), String> {
    let Some(world) = ctx.db.player_world().identity().find(identity) else {
        return Ok(());
    };

    if !world_kind_is_instance(world.world_kind.as_str()) {
        return Ok(());
    }

    let Some(instance_id) = world.instance_id else {
        return Ok(());
    };

    let Some(mut arena) = ctx.db.arena_instance().id().find(instance_id) else {
        return Ok(());
    };

    if arena.player_count > 0 {
        arena.player_count -= 1;
    }

    if arena.player_count == 0 {
        ctx.db.arena_instance().id().delete(arena.id);
        clear_match_stats_for_instance(ctx, arena.id);
        if is_training_instance(ctx, arena.id) {
            despawn_training_instance(ctx, arena.id);
        }
    } else {
        ctx.db.arena_instance().id().update(arena);
    }

    Ok(())
}

fn restore_player_to_open_world_spawn(
    ctx: &ReducerContext,
    identity: Identity,
) -> Result<(), String> {
    let now = ctx.timestamp;
    let profile = open_world_scene_profile_for_identity(ctx, identity);
    let (spawn_x, spawn_y, spawn_z) = resolve_world_spawn_position_with_layout_for_scene(
        None,
        false,
        Some(profile.scene_name),
        profile.spawn_x,
        profile.spawn_z,
        DEFAULT_HIT_RADIUS,
        DEFAULT_HIT_HEIGHT,
    );

    if let Some(mut physics) = ctx.db.player_physics().identity().find(identity) {
        let last_processed_tick = physics.last_processed_tick;
        physics.pos_x = spawn_x;
        physics.pos_y = spawn_y;
        physics.pos_z = spawn_z;
        physics.vel_x = 0.0;
        physics.vel_y = 0.0;
        physics.vel_z = 0.0;
        physics.yaw = profile.spawn_yaw;
        physics.grounded = true;
        physics.updated_at = now;
        commit_player_physics(
            ctx,
            physics,
            PhysicsWriteMode::Force,
            "restore_player_to_open_world_spawn",
        );

        if let Some(mut intent) = ctx.db.player_intent().identity().find(identity) {
            intent.forward = 0.0;
            intent.strafe = 0.0;
            intent.yaw = profile.spawn_yaw;
            intent.jump = false;
            intent.input_tick = last_processed_tick;
            intent.updated_at = now;
            ctx.db.player_intent().identity().update(intent);
        }
    }

    if let Some(mut state) = ctx.db.player_state().player_id().find(identity) {
        reset_player_state_to_spawn(&mut state, now);
        ctx.db.player_state().player_id().update(state);
    }

    clear_pending_player_commands(ctx, identity);
    emit_player_spawned(ctx, identity, spawn_x, spawn_y, spawn_z);
    Ok(())
}

fn sanitize_max_players(max_players: u32) -> u32 {
    max_players.clamp(MIN_MAX_PLAYERS, MAX_MAX_PLAYERS)
}

pub(crate) fn create_arena_instance(ctx: &ReducerContext, max_players: u32) -> u64 {
    create_arena_instance_with_options(ctx, max_players, false)
}

pub(crate) fn create_arena_instance_with_options(
    ctx: &ReducerContext,
    max_players: u32,
    is_practice: bool,
) -> u64 {
    let previous_max_id = max_arena_id(ctx);
    let fallback_id = previous_max_id.saturating_add(1);
    let fallback_seed = seed_for_arena(ctx, fallback_id);

    ctx.db.arena_instance().insert(ArenaInstance {
        id: 0,
        seed: fallback_seed,
        max_players,
        player_count: 0,
        phase: if is_practice {
            MATCH_PHASE_IN_PROGRESS.to_string()
        } else {
            MATCH_PHASE_WAITING.to_string()
        },
        winner_id: None,
        ended_at: None,
        is_practice,
        countdown_started_at: None,
    });

    let arena_id = max_arena_id(ctx).max(fallback_id);
    if let Some(mut arena) = ctx.db.arena_instance().id().find(arena_id) {
        let final_seed = seed_for_arena(ctx, arena_id);
        if arena.seed != final_seed {
            arena.seed = final_seed;
            ctx.db.arena_instance().id().update(arena);
        }
    }

    arena_id
}

fn max_arena_id(ctx: &ReducerContext) -> u64 {
    ctx.db
        .arena_instance()
        .iter()
        .map(|arena| arena.id)
        .max()
        .unwrap_or(0)
}

fn seed_for_arena(ctx: &ReducerContext, arena_id: u64) -> u64 {
    let sender_hash = hash_bytes(ctx.sender().to_hex().as_bytes());
    let mixed = mix64(sender_hash ^ arena_id.wrapping_mul(HASH_X_MUL));
    let js_safe = mixed & JS_SAFE_SEED_MASK;
    if js_safe == 0 {
        1
    } else {
        js_safe
    }
}

fn hash_bytes(bytes: &[u8]) -> u64 {
    // FNV-1a 64-bit
    let mut hash = 0xcbf2_9ce4_8422_2325_u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

fn ensure_open_arena_exists(ctx: &ReducerContext) {
    let has_open_arena = ctx
        .db
        .arena_instance()
        .iter()
        .any(|arena| arena.player_count < arena.max_players);

    if !has_open_arena {
        create_arena_instance(ctx, DEFAULT_MAX_PLAYERS);
    }
}

pub(crate) fn join_identity_into_instance(
    ctx: &ReducerContext,
    identity: Identity,
    instance_id: u64,
) -> Result<(), String> {
    if let Some(world) = ctx.db.player_world().identity().find(identity) {
        if world_kind_is_instance(world.world_kind.as_str())
            && world.instance_id == Some(instance_id)
        {
            return Ok(());
        }
    }
    despawn_all_playground_targets_for_owner(ctx, identity)?;
    clear_statuses_for_identity(ctx, identity);
    clear_combat_engagement_for_identity(ctx, identity);
    remove_identity_from_current_instance(ctx, identity)?;

    let Some(mut arena) = ctx.db.arena_instance().id().find(instance_id) else {
        return Err(format!("Instance {instance_id} not found"));
    };

    if !arena.is_practice && arena.phase != MATCH_PHASE_WAITING {
        return Err(format!("Instance {instance_id} is no longer joinable"));
    }

    if arena.player_count >= arena.max_players {
        return Err(format!("Instance {instance_id} is full"));
    }

    arena.player_count += 1;
    let arena_seed = arena.seed;
    ctx.db.arena_instance().id().update(arena);
    upsert_player_world(ctx, identity, WORLD_KIND_INSTANCE, Some(instance_id));
    reset_player_for_instance(ctx, identity, arena_seed)?;
    Ok(())
}

fn reset_player_for_instance(
    ctx: &ReducerContext,
    identity: Identity,
    arena_seed: u64,
) -> Result<(), String> {
    let now = ctx.timestamp;
    let instance_id = ctx
        .db
        .player_world()
        .identity()
        .find(identity)
        .and_then(|world| world.instance_id);
    let (spawn_target_x, spawn_target_z, spawn_yaw) = instance_id
        .and_then(|instance_id| resolve_instance_spawn_override(ctx, instance_id, identity))
        .unwrap_or_else(|| {
            let (spawn_x, spawn_z) = instance_spawn_for_player(arena_seed, identity);
            (spawn_x, spawn_z, 0.0)
        });
    let use_flat_training_layout = instance_id
        .map(|id| is_training_instance(ctx, id))
        .unwrap_or(false);
    let (spawn_x, spawn_y, spawn_z) = resolve_world_spawn_position_with_layout(
        Some(arena_seed),
        use_flat_training_layout,
        spawn_target_x,
        spawn_target_z,
        DEFAULT_HIT_RADIUS,
        DEFAULT_HIT_HEIGHT,
    );

    let Some(mut physics) = ctx.db.player_physics().identity().find(identity) else {
        return Err(format!(
            "Cannot join instance: missing physics row for {}",
            &identity.to_hex()[..8]
        ));
    };
    physics.pos_x = spawn_x;
    physics.pos_y = spawn_y;
    physics.pos_z = spawn_z;
    physics.vel_x = 0.0;
    physics.vel_y = 0.0;
    physics.vel_z = 0.0;
    physics.yaw = spawn_yaw;
    physics.grounded = true;
    physics.updated_at = now;
    let last_processed_tick = physics.last_processed_tick;
    commit_player_physics(
        ctx,
        physics,
        PhysicsWriteMode::Force,
        "reset_player_for_instance",
    );

    let Some(mut state) = ctx.db.player_state().player_id().find(identity) else {
        return Err(format!(
            "Cannot join instance: missing player_state row for {}",
            &identity.to_hex()[..8]
        ));
    };
    reset_player_state_to_spawn(&mut state, now);
    ctx.db.player_state().player_id().update(state);

    if let Some(mut intent) = ctx.db.player_intent().identity().find(identity) {
        intent.forward = 0.0;
        intent.strafe = 0.0;
        intent.yaw = spawn_yaw;
        intent.jump = false;
        intent.input_tick = last_processed_tick;
        intent.updated_at = now;
        ctx.db.player_intent().identity().update(intent);
    }
    clear_pending_player_commands(ctx, identity);

    emit_player_spawned(ctx, identity, spawn_x, spawn_y, spawn_z);
    Ok(())
}

fn instance_spawn_for_player(seed: u64, identity: Identity) -> (f32, f32) {
    let identity_hash = hash_bytes(identity.to_hex().as_bytes());
    let angle_hash = mix64(seed ^ identity_hash);
    let radius_hash = mix64(angle_hash ^ HASH_Z_MUL);

    let angle_unit = hash_to_unit(angle_hash);
    let radius_unit = hash_to_unit(radius_hash);
    let angle = angle_unit * TAU;
    let radius =
        INSTANCE_PLAYER_SPAWN_RADIUS + (radius_unit - 0.5) * INSTANCE_PLAYER_SPAWN_RADIUS_JITTER;

    let spawn_x = radius * angle.cos();
    let spawn_z = radius * angle.sin();
    (spawn_x, spawn_z)
}

pub(crate) fn upsert_player_world(
    ctx: &ReducerContext,
    identity: Identity,
    world_kind: &str,
    instance_id: Option<u64>,
) {
    let normalized_world_kind = if world_kind_is_instance(world_kind) {
        WORLD_KIND_INSTANCE
    } else {
        WORLD_KIND_OPEN
    };
    let normalized_instance_id = if world_kind_is_instance(normalized_world_kind) {
        instance_id
    } else {
        None
    };
    let open_world_scene_name = if world_kind_is_open(normalized_world_kind) {
        ensure_player_open_world_scene(ctx, identity)
    } else {
        String::new()
    };

    if let Some(mut world) = ctx.db.player_world().identity().find(identity) {
        world.world_kind = normalized_world_kind.to_string();
        world.instance_id = normalized_instance_id;
        world.open_world_scene_name = open_world_scene_name;
        ctx.db.player_world().identity().update(world);
    } else {
        ctx.db.player_world().insert(PlayerWorld {
            identity,
            world_kind: normalized_world_kind.to_string(),
            instance_id: normalized_instance_id,
            open_world_scene_name,
        });
    }
}

pub(crate) fn open_world_scene_name_for_identity(
    ctx: &ReducerContext,
    identity: Identity,
) -> String {
    if let Some(world) = ctx.db.player_world().identity().find(identity) {
        if world_kind_is_open(world.world_kind.as_str()) {
            if is_known_open_world_scene(world.open_world_scene_name.as_str()) {
                return world.open_world_scene_name;
            }
        }
    }
    if let Some(npc) = ctx.db.npc_instance().identity().find(identity) {
        if world_kind_is_open(npc.world_kind.as_str())
            && is_known_open_world_scene(npc.open_world_scene_name.as_str())
        {
            return npc.open_world_scene_name;
        }
    }

    ctx.db
        .player_open_world_scene()
        .identity()
        .find(identity)
        .map(|row| row.scene_name)
        .unwrap_or_else(|| default_open_world_scene_profile().scene_name.to_string())
}

pub(crate) fn open_world_scene_profile_for_identity(
    ctx: &ReducerContext,
    identity: Identity,
) -> &'static crate::open_world_scene::OpenWorldSceneProfile {
    open_world_scene_profile_for_scene(open_world_scene_name_for_identity(ctx, identity).as_str())
        .unwrap_or_else(default_open_world_scene_profile)
}

pub(crate) fn upsert_player_open_world_scene(
    ctx: &ReducerContext,
    identity: Identity,
    scene_name: &str,
) {
    if let Some(mut row) = ctx.db.player_open_world_scene().identity().find(identity) {
        row.scene_name = scene_name.to_string();
        ctx.db.player_open_world_scene().identity().update(row);
    } else {
        ctx.db
            .player_open_world_scene()
            .insert(PlayerOpenWorldScene {
                identity,
                scene_name: scene_name.to_string(),
            });
    }
}

pub(crate) fn ensure_player_open_world_scene(ctx: &ReducerContext, identity: Identity) -> String {
    if let Some(row) = ctx.db.player_open_world_scene().identity().find(identity) {
        if is_known_open_world_scene(row.scene_name.as_str()) {
            return row.scene_name;
        }
    }

    let scene_name = default_open_world_scene_profile().scene_name.to_string();
    upsert_player_open_world_scene(ctx, identity, scene_name.as_str());
    scene_name
}

pub(crate) fn despawn_legacy_default_dummies(ctx: &ReducerContext) {
    let mut identities = Vec::new();
    if let Ok(identity) = Identity::from_hex(LEGACY_OPEN_WORLD_DUMMY_ID_HEX) {
        push_unique_identity(&mut identities, identity);
    } else {
        log::error!(
            "[LEGACY_DUMMY_CLEANUP] Invalid legacy open-world dummy identity {}",
            LEGACY_OPEN_WORLD_DUMMY_ID_HEX
        );
    }

    for row in ctx.db.player().iter() {
        push_if_legacy_instance_dummy(&mut identities, row.identity);
    }
    for row in ctx.db.player_state().iter() {
        push_if_legacy_instance_dummy(&mut identities, row.player_id);
    }
    for row in ctx.db.player_physics().iter() {
        push_if_legacy_instance_dummy(&mut identities, row.identity);
    }
    for row in ctx.db.player_world().iter() {
        push_if_legacy_instance_dummy(&mut identities, row.identity);
    }
    for row in ctx.db.player_open_world_scene().iter() {
        push_if_legacy_instance_dummy(&mut identities, row.identity);
    }
    for row in ctx.db.player_intent().iter() {
        push_if_legacy_instance_dummy(&mut identities, row.identity);
    }
    for row in ctx.db.player_input_cursor().iter() {
        push_if_legacy_instance_dummy(&mut identities, row.identity);
    }

    for identity in identities {
        if ctx
            .db
            .player_open_world_scene()
            .identity()
            .find(identity)
            .is_some()
        {
            ctx.db.player_open_world_scene().identity().delete(identity);
        }
        if let Err(error) = despawn_actor_bundle(
            ctx,
            identity,
            ActorDespawnOptions {
                world_cleanup: ActorWorldCleanup::DeleteOnly,
            },
        ) {
            log::error!(
                "[LEGACY_DUMMY_CLEANUP] Failed to despawn {}: {}",
                identity.to_hex(),
                error
            );
        }
    }
}

fn push_if_legacy_instance_dummy(identities: &mut Vec<Identity>, identity: Identity) {
    if identity
        .to_hex()
        .starts_with(LEGACY_INSTANCE_DUMMY_PREFIX_HEX)
    {
        push_unique_identity(identities, identity);
    }
}

fn push_unique_identity(identities: &mut Vec<Identity>, identity: Identity) {
    if !identities.iter().any(|existing| *existing == identity) {
        identities.push(identity);
    }
}

fn clear_match_stats_for_instance(ctx: &ReducerContext, arena_id: u64) {
    let keys: Vec<String> = ctx
        .db
        .match_participant_stats()
        .iter()
        .filter(|stats| stats.instance_id == arena_id)
        .map(|stats| stats.key)
        .collect();

    for key in keys {
        ctx.db.match_participant_stats().key().delete(key);
    }
}

fn mix64(mut value: u64) -> u64 {
    value ^= value >> 33;
    value = value.wrapping_mul(MIX_MUL_A);
    value ^= value >> 33;
    value = value.wrapping_mul(MIX_MUL_B);
    value ^= value >> 33;
    value
}

fn hash_grid(seed: u64, x: i32, z: i32) -> u64 {
    let x_bits = x as i64 as u64;
    let z_bits = z as i64 as u64;
    let value = seed
        .wrapping_add(x_bits.wrapping_mul(HASH_X_MUL))
        .wrapping_add(z_bits.wrapping_mul(HASH_Z_MUL));
    mix64(value)
}

fn hash_to_signed_unit(hash: u64) -> f64 {
    let upper53 = hash >> 11;
    let unit = (upper53 as f64) / ((1_u64 << 53) - 1) as f64;
    unit * 2.0 - 1.0
}

fn hash_to_unit(hash: u64) -> f32 {
    let upper53 = hash >> 11;
    let unit = (upper53 as f64) / ((1_u64 << 53) - 1) as f64;
    unit as f32
}

fn world_kind_is_open(value: &str) -> bool {
    value.eq_ignore_ascii_case(WORLD_KIND_OPEN)
}

fn world_kind_is_instance(value: &str) -> bool {
    value.eq_ignore_ascii_case(WORLD_KIND_INSTANCE)
}

fn lerp(a: f64, b: f64, t: f64) -> f64 {
    a + (b - a) * t
}

fn smoothstep(t: f64) -> f64 {
    t * t * (3.0 - 2.0 * t)
}

fn value_noise(seed: u64, x: f64, z: f64, scale: f64) -> f64 {
    let fx = x / scale;
    let fz = z / scale;

    let x0 = fx.floor() as i32;
    let z0 = fz.floor() as i32;
    let x1 = x0.saturating_add(1);
    let z1 = z0.saturating_add(1);

    let tx = smoothstep(fx - x0 as f64);
    let tz = smoothstep(fz - z0 as f64);

    let n00 = hash_to_signed_unit(hash_grid(seed, x0, z0));
    let n10 = hash_to_signed_unit(hash_grid(seed, x1, z0));
    let n01 = hash_to_signed_unit(hash_grid(seed, x0, z1));
    let n11 = hash_to_signed_unit(hash_grid(seed, x1, z1));

    let nx0 = lerp(n00, n10, tx);
    let nx1 = lerp(n01, n11, tx);
    lerp(nx0, nx1, tz)
}

pub fn height_at(_seed: u64, _x: f32, _z: f32) -> f32 {
    // ArenaMatch currently uses a flat authored floor, so the authoritative arena
    // terrain must stay flat until the scene visuals/collision are upgraded to the
    // procedural arena layout.
    0.0
}

/// Returns the highest walkable surface at (x, z) — legacy interface.
/// Prefers the highest surface overall (used for spawning where no current_y exists).
pub fn surface_height_at(seed: u64, x: f32, z: f32) -> f32 {
    surface_height_at_y(seed, x, z, f32::MAX)
}

/// Y-aware surface query.  Returns the highest walkable surface at (x, z) that
/// is at or below `current_y + SURFACE_SNAP_UP`.  This lets players walk under
/// platforms instead of being teleported on top of them.
///
/// When `current_y` is `f32::MAX` the function behaves like the old
/// `surface_height_at` (returns the global maximum).
pub const SURFACE_SNAP_UP: f32 = 1.2;

pub fn surface_height_at_y(seed: u64, x: f32, z: f32, current_y: f32) -> f32 {
    let base = height_at(seed, x, z);
    let ceiling = current_y + SURFACE_SNAP_UP;

    // Base terrain is always a candidate (you can always fall to it).
    let mut surface = base;

    for_each_arena_walkable_surface(seed, |walkable| {
        if !walkable.contains_xz(x, z) {
            return;
        }
        let top = walkable.top_y_at_x(x);
        if top <= ceiling && top > surface {
            surface = top;
        }
    });

    surface
}

pub fn arena_seed_for_identity(ctx: &ReducerContext, identity: Identity) -> Option<u64> {
    let ResolvedWorldContext::Instance(instance_id) = resolve_player_world_context(ctx, identity)?
    else {
        return None;
    };
    let arena = ctx.db.arena_instance().id().find(instance_id)?;
    Some(arena.seed)
}

pub fn shared_arena_seed_for_identities(
    ctx: &ReducerContext,
    a: Identity,
    b: Identity,
) -> Option<u64> {
    let ResolvedWorldContext::Instance(a_instance) = resolve_player_world_context(ctx, a)? else {
        return None;
    };
    let ResolvedWorldContext::Instance(b_instance) = resolve_player_world_context(ctx, b)? else {
        return None;
    };
    if a_instance != b_instance {
        return None;
    }
    let arena = ctx.db.arena_instance().id().find(a_instance)?;
    Some(arena.seed)
}

pub(crate) fn resolve_player_world_context(
    ctx: &ReducerContext,
    identity: Identity,
) -> Option<ResolvedWorldContext> {
    if let Some(world) = ctx.db.player_world().identity().find(identity) {
        if world_kind_is_open(world.world_kind.as_str()) {
            let scene_name = if is_known_open_world_scene(world.open_world_scene_name.as_str()) {
                world.open_world_scene_name
            } else {
                open_world_scene_name_for_identity(ctx, identity)
            };
            return Some(ResolvedWorldContext::Open(scene_name));
        }

        if world_kind_is_instance(world.world_kind.as_str()) {
            return world.instance_id.map(ResolvedWorldContext::Instance);
        }

        return None;
    }

    let npc = ctx.db.npc_instance().identity().find(identity)?;

    if world_kind_is_open(npc.world_kind.as_str()) {
        return Some(ResolvedWorldContext::Open(npc.open_world_scene_name));
    }

    if world_kind_is_instance(npc.world_kind.as_str()) {
        return npc.instance_id.map(ResolvedWorldContext::Instance);
    }

    None
}

pub(crate) fn world_contexts_share(a: &ResolvedWorldContext, b: &ResolvedWorldContext) -> bool {
    match (a, b) {
        (ResolvedWorldContext::Open(a_scene), ResolvedWorldContext::Open(b_scene)) => {
            a_scene == b_scene
        }
        (
            ResolvedWorldContext::Instance(a_instance),
            ResolvedWorldContext::Instance(b_instance),
        ) => a_instance == b_instance,
        _ => false,
    }
}

pub fn players_share_world_context(ctx: &ReducerContext, a: Identity, b: Identity) -> bool {
    let Some(a_context) = resolve_player_world_context(ctx, a) else {
        log::warn!(
            "[WORLD] Missing player_world row for caster/attacker {}",
            a.to_hex()
        );
        return false;
    };
    let Some(b_context) = resolve_player_world_context(ctx, b) else {
        log::warn!(
            "[WORLD] Missing player_world row for target/victim {}",
            b.to_hex()
        );
        return false;
    };

    world_contexts_share(&a_context, &b_context)
}

#[cfg(test)]
mod tests {
    use super::{world_contexts_share, ResolvedWorldContext};

    #[test]
    fn open_world_context_requires_matching_scene() {
        let oasis_a = ResolvedWorldContext::Open("Oasis_Day".to_string());
        let oasis_b = ResolvedWorldContext::Open("Oasis_Day".to_string());
        let desert = ResolvedWorldContext::Open("Desert_Day".to_string());

        assert!(world_contexts_share(&oasis_a, &oasis_b));
        assert!(!world_contexts_share(&oasis_a, &desert));
    }

    #[test]
    fn instance_context_requires_matching_instance_id() {
        let instance_a = ResolvedWorldContext::Instance(7);
        let instance_b = ResolvedWorldContext::Instance(7);
        let instance_c = ResolvedWorldContext::Instance(9);
        let open = ResolvedWorldContext::Open("Oasis_Day".to_string());

        assert!(world_contexts_share(&instance_a, &instance_b));
        assert!(!world_contexts_share(&instance_a, &instance_c));
        assert!(!world_contexts_share(&instance_a, &open));
    }
}

#[derive(Clone, Copy, Debug)]
pub struct WorldRayHit {
    pub t: f32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[derive(Clone, Copy, Debug)]
pub struct WorldRaycastRequest {
    pub origin_x: f32,
    pub origin_y: f32,
    pub origin_z: f32,
    pub dir_x: f32,
    pub dir_y: f32,
    pub dir_z: f32,
    pub max_distance: f32,
    pub radius: f32,
}

pub fn raycast_arena_world(
    seed: u64,
    origin_x: f32,
    origin_y: f32,
    origin_z: f32,
    dir_x: f32,
    dir_y: f32,
    dir_z: f32,
    max_distance: f32,
    radius: f32,
) -> Option<WorldRayHit> {
    raycast_arena_world_with(
        seed,
        WorldRaycastRequest {
            origin_x,
            origin_y,
            origin_z,
            dir_x,
            dir_y,
            dir_z,
            max_distance,
            radius,
        },
    )
}

pub fn raycast_arena_world_with(seed: u64, request: WorldRaycastRequest) -> Option<WorldRayHit> {
    if request.max_distance <= 0.0 {
        return None;
    }

    let mut best: Option<WorldRayHit> = raycast_terrain_surface(seed, request);

    for_each_arena_raycast_obstacle(seed, |obstacle| match obstacle {
        ArenaRaycastObstacle::Aabb(aabb) => {
            try_world_aabb_hit(&mut best, request, aabb);
        }
        ArenaRaycastObstacle::ObbZ(ramp) => {
            try_world_obb_z_hit(&mut best, request, ramp);
        }
    });

    best
}

fn raycast_terrain_surface(seed: u64, request: WorldRaycastRequest) -> Option<WorldRayHit> {
    let clearance_at = |t: f32| -> f32 {
        let x = request.origin_x + request.dir_x * t;
        let y = request.origin_y + request.dir_y * t;
        let z = request.origin_z + request.dir_z * t;
        y - (surface_height_at(seed, x, z) + request.radius)
    };

    let start_clearance = clearance_at(0.0);
    if start_clearance <= 0.0 {
        return Some(world_ray_hit_at_t(request, 0.0));
    }

    let mut prev_t = 0.0;
    let mut t = TERRAIN_RAY_STEP
        .min(request.max_distance)
        .max(COLLISION_EPSILON);
    while t <= request.max_distance {
        let clearance = clearance_at(t);
        if clearance <= 0.0 {
            let hit_t = refine_terrain_hit_t(clearance_at, prev_t, t);
            return Some(world_ray_hit_at_t(request, hit_t));
        }
        prev_t = t;
        t += TERRAIN_RAY_STEP;
    }

    let end_clearance = clearance_at(request.max_distance);
    if end_clearance <= 0.0 {
        let hit_t = refine_terrain_hit_t(clearance_at, prev_t, request.max_distance);
        return Some(world_ray_hit_at_t(request, hit_t));
    }

    None
}

fn world_ray_hit_at_t(request: WorldRaycastRequest, t: f32) -> WorldRayHit {
    WorldRayHit {
        t,
        x: request.origin_x + request.dir_x * t,
        y: request.origin_y + request.dir_y * t,
        z: request.origin_z + request.dir_z * t,
    }
}

fn refine_terrain_hit_t<F>(clearance_at: F, mut lo: f32, mut hi: f32) -> f32
where
    F: Fn(f32) -> f32,
{
    for _ in 0..TERRAIN_RAY_REFINEMENT_STEPS {
        let mid = (lo + hi) * 0.5;
        if clearance_at(mid) <= 0.0 {
            hi = mid;
        } else {
            lo = mid;
        }
    }
    hi
}

/// Legacy signature kept for callers that don't have a Y coordinate.
pub fn resolve_arena_horizontal_collision(
    seed: u64,
    x: f32,
    z: f32,
    player_radius: f32,
) -> (f32, f32) {
    resolve_arena_horizontal_collision_y(seed, x, z, player_radius, f32::MAX, f32::MAX)
}

/// Y-aware horizontal collision.  Only pushes the player out of obstacles
/// whose vertical extent overlaps the player's Y band.
pub fn resolve_arena_horizontal_collision_y(
    seed: u64,
    x: f32,
    z: f32,
    player_radius: f32,
    current_y: f32,
    player_height: f32,
) -> (f32, f32) {
    let mut out_x = x;
    let mut out_z = z;

    let max_radius = (arena_layout().arena_radius - player_radius).max(0.0);
    let dist = (out_x * out_x + out_z * out_z).sqrt();
    if dist > max_radius && dist > COLLISION_EPSILON {
        let scale = max_radius / dist;
        out_x *= scale;
        out_z *= scale;
    }

    for _ in 0..2 {
        for_each_arena_horizontal_blocker(seed, |blocker| match blocker {
            ArenaHorizontalBlocker::Aabb(wall) => {
                if !collider_overlaps_player_band(
                    wall.base_y(),
                    wall.top_y(),
                    current_y,
                    player_height,
                ) {
                    return;
                }
                (out_x, out_z) = push_out_aabb_2d(
                    out_x,
                    out_z,
                    wall.center_x,
                    wall.center_z,
                    wall.half_x,
                    wall.half_z,
                    player_radius,
                );
            }
            ArenaHorizontalBlocker::Circle(pillar) => {
                if !collider_overlaps_player_band(
                    pillar.base_y(),
                    pillar.top_y(),
                    current_y,
                    player_height,
                ) {
                    return;
                }
                (out_x, out_z) = push_out_circle_2d(
                    out_x,
                    out_z,
                    pillar.center_x,
                    pillar.center_z,
                    pillar.collider_radius + player_radius,
                );
            }
        });
    }

    (out_x, out_z)
}

fn collider_overlaps_player_band(
    collider_y_min: f32,
    collider_y_max: f32,
    current_y: f32,
    player_height: f32,
) -> bool {
    if !current_y.is_finite() || !player_height.is_finite() {
        return true;
    }
    let foot_y = current_y;
    let head_y = current_y + player_height.max(0.1);
    head_y > collider_y_min + COLLISION_EPSILON && foot_y < collider_y_max - COLLISION_EPSILON
}

fn inside_aabb_2d(x: f32, z: f32, cx: f32, cz: f32, half_x: f32, half_z: f32) -> bool {
    (x - cx).abs() <= half_x && (z - cz).abs() <= half_z
}

fn try_world_aabb_hit(
    best: &mut Option<WorldRayHit>,
    request: WorldRaycastRequest,
    obstacle: ArenaAabbObstacle,
) {
    let Some(t) = raycast_aabb_expanded(
        request.origin_x,
        request.origin_y,
        request.origin_z,
        request.dir_x,
        request.dir_y,
        request.dir_z,
        request.max_distance,
        obstacle.center_x,
        obstacle.center_y,
        obstacle.center_z,
        obstacle.half_x,
        obstacle.half_y,
        obstacle.half_z,
        request.radius,
    ) else {
        return;
    };

    if best.is_some_and(|hit| t >= hit.t) {
        return;
    }
    *best = Some(world_ray_hit_at_t(request, t));
}

fn try_world_obb_z_hit(
    best: &mut Option<WorldRayHit>,
    request: WorldRaycastRequest,
    obstacle: ArenaRampObstacle,
) {
    let Some(t) = raycast_obb_z_expanded(
        request.origin_x,
        request.origin_y,
        request.origin_z,
        request.dir_x,
        request.dir_y,
        request.dir_z,
        request.max_distance,
        obstacle.center_x,
        obstacle.center_y,
        obstacle.center_z,
        obstacle.half_x,
        obstacle.half_y,
        obstacle.half_z,
        obstacle.rot_z(),
        request.radius,
    ) else {
        return;
    };

    if best.is_some_and(|hit| t >= hit.t) {
        return;
    }
    *best = Some(world_ray_hit_at_t(request, t));
}

fn raycast_aabb_expanded(
    origin_x: f32,
    origin_y: f32,
    origin_z: f32,
    dir_x: f32,
    dir_y: f32,
    dir_z: f32,
    max_distance: f32,
    center_x: f32,
    center_y: f32,
    center_z: f32,
    half_x: f32,
    half_y: f32,
    half_z: f32,
    radius: f32,
) -> Option<f32> {
    let min_x = center_x - (half_x + radius);
    let max_x = center_x + (half_x + radius);
    let min_y = center_y - (half_y + radius);
    let max_y = center_y + (half_y + radius);
    let min_z = center_z - (half_z + radius);
    let max_z = center_z + (half_z + radius);
    raycast_aabb_bounds(
        origin_x,
        origin_y,
        origin_z,
        dir_x,
        dir_y,
        dir_z,
        max_distance,
        min_x,
        max_x,
        min_y,
        max_y,
        min_z,
        max_z,
    )
}

fn raycast_obb_z_expanded(
    origin_x: f32,
    origin_y: f32,
    origin_z: f32,
    dir_x: f32,
    dir_y: f32,
    dir_z: f32,
    max_distance: f32,
    center_x: f32,
    center_y: f32,
    center_z: f32,
    half_x: f32,
    half_y: f32,
    half_z: f32,
    rot_z: f32,
    radius: f32,
) -> Option<f32> {
    let cos = rot_z.cos();
    let sin = rot_z.sin();

    let dx = origin_x - center_x;
    let dy = origin_y - center_y;
    let dz = origin_z - center_z;

    let local_origin_x = cos * dx + sin * dy;
    let local_origin_y = -sin * dx + cos * dy;
    let local_origin_z = dz;

    let local_dir_x = cos * dir_x + sin * dir_y;
    let local_dir_y = -sin * dir_x + cos * dir_y;
    let local_dir_z = dir_z;

    raycast_aabb_bounds(
        local_origin_x,
        local_origin_y,
        local_origin_z,
        local_dir_x,
        local_dir_y,
        local_dir_z,
        max_distance,
        -(half_x + radius),
        half_x + radius,
        -(half_y + radius),
        half_y + radius,
        -(half_z + radius),
        half_z + radius,
    )
}

fn raycast_aabb_bounds(
    origin_x: f32,
    origin_y: f32,
    origin_z: f32,
    dir_x: f32,
    dir_y: f32,
    dir_z: f32,
    max_distance: f32,
    min_x: f32,
    max_x: f32,
    min_y: f32,
    max_y: f32,
    min_z: f32,
    max_z: f32,
) -> Option<f32> {
    let mut t_min = 0.0_f32;
    let mut t_max = max_distance;

    if !slab_intersection(origin_x, dir_x, min_x, max_x, &mut t_min, &mut t_max) {
        return None;
    }
    if !slab_intersection(origin_y, dir_y, min_y, max_y, &mut t_min, &mut t_max) {
        return None;
    }
    if !slab_intersection(origin_z, dir_z, min_z, max_z, &mut t_min, &mut t_max) {
        return None;
    }

    Some(t_min.clamp(0.0, max_distance))
}

fn slab_intersection(
    origin: f32,
    dir: f32,
    min: f32,
    max: f32,
    t_min: &mut f32,
    t_max: &mut f32,
) -> bool {
    if dir.abs() <= COLLISION_EPSILON {
        return origin >= min && origin <= max;
    }

    let inv = 1.0 / dir;
    let mut t1 = (min - origin) * inv;
    let mut t2 = (max - origin) * inv;
    if t1 > t2 {
        std::mem::swap(&mut t1, &mut t2);
    }

    *t_min = (*t_min).max(t1);
    *t_max = (*t_max).min(t2);
    *t_min <= *t_max
}

fn push_out_circle_2d(x: f32, z: f32, cx: f32, cz: f32, radius: f32) -> (f32, f32) {
    let mut dx = x - cx;
    let mut dz = z - cz;
    let dist_sq = dx * dx + dz * dz;
    let radius_sq = radius * radius;
    if dist_sq >= radius_sq {
        return (x, z);
    }

    if dist_sq <= COLLISION_EPSILON {
        // Degenerate overlap (exact center): pick a deterministic direction tied
        // to the collider position to avoid globally biasing ejections toward +X.
        let hash = u64::from(cx.to_bits())
            .wrapping_mul(HASH_X_MUL)
            .wrapping_add(u64::from(cz.to_bits()).wrapping_mul(HASH_Z_MUL))
            .max(1);
        let angle = ((hash % 65_536) as f32 / 65_536.0) * TAU;
        dx = angle.cos() * radius;
        dz = angle.sin() * radius;
    }

    let dist = (dx * dx + dz * dz).sqrt().max(COLLISION_EPSILON);
    let push = (radius - dist).max(0.0);
    let nx = dx / dist;
    let nz = dz / dist;
    (x + nx * push, z + nz * push)
}

fn push_out_aabb_2d(
    x: f32,
    z: f32,
    cx: f32,
    cz: f32,
    half_x: f32,
    half_z: f32,
    padding: f32,
) -> (f32, f32) {
    let expanded_half_x = half_x + padding;
    let expanded_half_z = half_z + padding;

    let dx = x - cx;
    let dz = z - cz;
    let abs_dx = dx.abs();
    let abs_dz = dz.abs();

    if abs_dx >= expanded_half_x || abs_dz >= expanded_half_z {
        return (x, z);
    }

    let pen_x = expanded_half_x - abs_dx;
    let pen_z = expanded_half_z - abs_dz;

    if pen_x < pen_z {
        let sign = if dx >= 0.0 { 1.0 } else { -1.0 };
        (x + sign * pen_x, z)
    } else {
        let sign = if dz >= 0.0 { 1.0 } else { -1.0 };
        (x, z + sign * pen_z)
    }
}

fn seeded_unit(seed: u64, offset: u64) -> f32 {
    let mixed = ((seed & JS_SAFE_SEED_MASK)
        .wrapping_add(offset.wrapping_mul(arena_layout().pillar_hash_step))
        & JS_SAFE_SEED_MASK)
        .max(1);
    (mixed % 1000) as f32 / 999.0
}

#[derive(Clone, Copy)]
struct ArenaAabbObstacle {
    center_x: f32,
    center_y: f32,
    center_z: f32,
    half_x: f32,
    half_y: f32,
    half_z: f32,
}

impl ArenaAabbObstacle {
    fn base_y(self) -> f32 {
        self.center_y - self.half_y
    }

    fn top_y(self) -> f32 {
        self.center_y + self.half_y
    }
}

#[derive(Clone, Copy)]
struct ArenaPlatformObstacle {
    center_x: f32,
    center_y: f32,
    center_z: f32,
    half_x: f32,
    half_y: f32,
    half_z: f32,
}

impl ArenaPlatformObstacle {
    fn top_y(self) -> f32 {
        self.center_y + self.half_y
    }
}

impl From<ArenaPlatformObstacle> for ArenaAabbObstacle {
    fn from(platform: ArenaPlatformObstacle) -> Self {
        Self {
            center_x: platform.center_x,
            center_y: platform.center_y,
            center_z: platform.center_z,
            half_x: platform.half_x,
            half_y: platform.half_y,
            half_z: platform.half_z,
        }
    }
}

#[derive(Clone, Copy)]
struct ArenaRampObstacle {
    center_x: f32,
    center_y: f32,
    center_z: f32,
    side: f32,
    half_x: f32,
    half_y: f32,
    half_z: f32,
}

impl ArenaRampObstacle {
    fn rot_z(self) -> f32 {
        self.side * arena_layout().ramp_rot_z_abs
    }

    fn top_y_at_x(self, sample_x: f32) -> f32 {
        let t = ((sample_x - self.center_x) / self.half_x).clamp(-1.0, 1.0) * self.side;
        self.center_y
            + arena_layout().ramp_top_center_offset
            + t * arena_layout().ramp_top_slope_delta
    }
}

#[derive(Clone, Copy)]
struct ArenaPillarObstacle {
    center_x: f32,
    center_y: f32,
    center_z: f32,
    half_x: f32,
    half_y: f32,
    half_z: f32,
    collider_radius: f32,
}

impl ArenaPillarObstacle {
    fn base_y(self) -> f32 {
        self.center_y - self.half_y
    }

    fn top_y(self) -> f32 {
        self.center_y + self.half_y
    }
}

impl From<ArenaPillarObstacle> for ArenaAabbObstacle {
    fn from(pillar: ArenaPillarObstacle) -> Self {
        Self {
            center_x: pillar.center_x,
            center_y: pillar.center_y,
            center_z: pillar.center_z,
            half_x: pillar.half_x,
            half_y: pillar.half_y,
            half_z: pillar.half_z,
        }
    }
}

#[derive(Clone, Copy)]
enum ArenaWalkableSurface {
    Platform(ArenaPlatformObstacle),
    Ramp(ArenaRampObstacle),
}

impl ArenaWalkableSurface {
    fn contains_xz(self, x: f32, z: f32) -> bool {
        match self {
            Self::Platform(platform) => inside_aabb_2d(
                x,
                z,
                platform.center_x,
                platform.center_z,
                platform.half_x,
                platform.half_z,
            ),
            Self::Ramp(ramp) => {
                inside_aabb_2d(x, z, ramp.center_x, ramp.center_z, ramp.half_x, ramp.half_z)
            }
        }
    }

    fn top_y_at_x(self, sample_x: f32) -> f32 {
        match self {
            Self::Platform(platform) => platform.top_y(),
            Self::Ramp(ramp) => ramp.top_y_at_x(sample_x),
        }
    }
}

#[derive(Clone, Copy)]
enum ArenaRaycastObstacle {
    Aabb(ArenaAabbObstacle),
    ObbZ(ArenaRampObstacle),
}

#[derive(Clone, Copy)]
enum ArenaHorizontalBlocker {
    Aabb(ArenaAabbObstacle),
    Circle(ArenaPillarObstacle),
}

#[derive(Clone, Copy)]
enum ArenaObstacle {
    Wall(ArenaAabbObstacle),
    Platform(ArenaPlatformObstacle),
    Ramp(ArenaRampObstacle),
    Pillar(ArenaPillarObstacle),
}

#[derive(Clone, Copy)]
struct ArenaObstacleFilter {
    include_walls: bool,
    include_platforms: bool,
    include_ramps: bool,
    include_pillars: bool,
}

const ARENA_OBSTACLES_WALKABLE: ArenaObstacleFilter = ArenaObstacleFilter {
    include_walls: false,
    include_platforms: true,
    include_ramps: true,
    include_pillars: false,
};

const ARENA_OBSTACLES_RAYCAST: ArenaObstacleFilter = ArenaObstacleFilter {
    include_walls: true,
    include_platforms: true,
    include_ramps: true,
    include_pillars: true,
};

const ARENA_OBSTACLES_HORIZONTAL: ArenaObstacleFilter = ArenaObstacleFilter {
    include_walls: true,
    include_platforms: false,
    include_ramps: false,
    include_pillars: true,
};

fn for_each_arena_wall(seed: u64, mut emit: impl FnMut(ArenaAabbObstacle)) {
    let layout = arena_layout();
    let wall_half_height = layout.ruin_wall_height * 0.5;
    for segment in &layout.ruin_wall_segments {
        let base_y = height_at(seed, segment.x, segment.z);
        emit(ArenaAabbObstacle {
            center_x: segment.x,
            center_y: base_y + wall_half_height,
            center_z: segment.z,
            half_x: segment.half_x,
            half_y: wall_half_height,
            half_z: segment.half_z,
        });
    }
}

fn for_each_arena_obstacle(
    seed: u64,
    filter: ArenaObstacleFilter,
    mut emit: impl FnMut(ArenaObstacle),
) {
    if filter.include_walls {
        for_each_arena_wall(seed, |wall| emit(ArenaObstacle::Wall(wall)));
    }
    if filter.include_platforms {
        for_each_arena_platform(seed, |platform| emit(ArenaObstacle::Platform(platform)));
    }
    if filter.include_ramps {
        for_each_arena_ramp(seed, |ramp| emit(ArenaObstacle::Ramp(ramp)));
    }
    if filter.include_pillars {
        for_each_arena_pillar_obstacle(seed, |pillar| emit(ArenaObstacle::Pillar(pillar)));
    }
}

fn for_each_arena_walkable_surface(seed: u64, mut emit: impl FnMut(ArenaWalkableSurface)) {
    for_each_arena_obstacle(seed, ARENA_OBSTACLES_WALKABLE, |obstacle| match obstacle {
        ArenaObstacle::Platform(platform) => emit(ArenaWalkableSurface::Platform(platform)),
        ArenaObstacle::Ramp(ramp) => emit(ArenaWalkableSurface::Ramp(ramp)),
        ArenaObstacle::Wall(_) | ArenaObstacle::Pillar(_) => {}
    });
}

fn for_each_arena_raycast_obstacle(seed: u64, mut emit: impl FnMut(ArenaRaycastObstacle)) {
    for_each_arena_obstacle(seed, ARENA_OBSTACLES_RAYCAST, |obstacle| match obstacle {
        ArenaObstacle::Wall(wall) => emit(ArenaRaycastObstacle::Aabb(wall)),
        ArenaObstacle::Platform(platform) => {
            emit(ArenaRaycastObstacle::Aabb(ArenaAabbObstacle::from(
                platform,
            )));
        }
        ArenaObstacle::Ramp(ramp) => emit(ArenaRaycastObstacle::ObbZ(ramp)),
        ArenaObstacle::Pillar(pillar) => {
            emit(ArenaRaycastObstacle::Aabb(ArenaAabbObstacle::from(pillar)));
        }
    });
}

fn for_each_arena_horizontal_blocker(seed: u64, mut emit: impl FnMut(ArenaHorizontalBlocker)) {
    for_each_arena_obstacle(
        seed,
        ARENA_OBSTACLES_HORIZONTAL,
        |obstacle| match obstacle {
            ArenaObstacle::Wall(wall) => emit(ArenaHorizontalBlocker::Aabb(wall)),
            ArenaObstacle::Pillar(pillar) => emit(ArenaHorizontalBlocker::Circle(pillar)),
            ArenaObstacle::Platform(_) | ArenaObstacle::Ramp(_) => {}
        },
    );
}

fn for_each_arena_platform(seed: u64, mut emit: impl FnMut(ArenaPlatformObstacle)) {
    let layout = arena_layout();
    for platform in &layout.platforms {
        emit(ArenaPlatformObstacle {
            center_x: platform.x,
            center_y: platform_center_y(seed, platform.x, platform.z),
            center_z: platform.z,
            half_x: layout.platform_half_x,
            half_y: layout.platform_half_height,
            half_z: layout.platform_half_z,
        });
    }
}

fn for_each_arena_ramp(seed: u64, mut emit: impl FnMut(ArenaRampObstacle)) {
    let layout = arena_layout();
    for ramp in &layout.ramps {
        emit(ArenaRampObstacle {
            center_x: ramp.x,
            center_y: ramp_center_y(seed, ramp.x, ramp.z, ramp.side),
            center_z: ramp.z,
            side: ramp.side,
            half_x: layout.ramp_half_x,
            half_y: layout.ramp_half_height,
            half_z: layout.ramp_half_z,
        });
    }
}

fn platform_center_y(seed: u64, platform_x: f32, platform_z: f32) -> f32 {
    height_at(seed, platform_x, platform_z) + arena_layout().platform_center_height_offset
}

fn platform_top_y(seed: u64, platform_x: f32, platform_z: f32) -> f32 {
    platform_center_y(seed, platform_x, platform_z) + arena_layout().platform_half_height
}

fn ramp_center_y(seed: u64, ramp_x: f32, ramp_z: f32, side: f32) -> f32 {
    let (linked_platform_x, linked_platform_z) = linked_platform_anchor(ramp_x, ramp_z, side);
    height_at(seed, linked_platform_x, linked_platform_z) + arena_layout().ramp_center_height_offset
}

fn linked_platform_anchor(ramp_x: f32, ramp_z: f32, side: f32) -> (f32, f32) {
    let layout = arena_layout();
    let target_dx = side * layout.ramp_platform_link_x_offset;
    let mut best: Option<(f32, f32, f32)> = None;

    for platform in &layout.platforms {
        let dx = platform.x - ramp_x;
        if dx * side <= 0.0 {
            continue;
        }
        let dz = (platform.z - ramp_z).abs();
        let score = (dx - target_dx).abs() + dz * 2.0;
        match best {
            Some((best_score, _, _)) if best_score <= score => {}
            _ => best = Some((score, platform.x, platform.z)),
        }
    }

    if let Some((_, platform_x, platform_z)) = best {
        (platform_x, platform_z)
    } else {
        (ramp_x + target_dx, ramp_z)
    }
}

fn ramp_top_y_at_x(seed: u64, ramp_x: f32, ramp_z: f32, side: f32, sample_x: f32) -> f32 {
    let layout = arena_layout();
    let t = ((sample_x - ramp_x) / layout.ramp_half_x).clamp(-1.0, 1.0) * side;
    ramp_center_y(seed, ramp_x, ramp_z, side)
        + layout.ramp_top_center_offset
        + t * layout.ramp_top_slope_delta
}

#[derive(Clone, Copy)]
struct ArenaPillar {
    x: f32,
    z: f32,
    height: f32,
}

fn for_each_arena_pillar(seed: u64, mut emit: impl FnMut(ArenaPillar)) {
    let layout = arena_layout();
    for i in 0..layout.pillar_count {
        let jitter = seeded_unit(seed, i as u64 * 2 + 1);
        let angle = (i as f32 / layout.pillar_count as f32) * TAU + jitter * 0.35;
        let ring_radius = 7.0 + seeded_unit(seed, i as u64 * 2 + 2) * 5.0;
        let column_scale = 0.7 + seeded_unit(seed, i as u64 * 3 + 7) * 0.9;
        emit(ArenaPillar {
            x: angle.cos() * ring_radius,
            z: angle.sin() * ring_radius,
            height: 6.0 * column_scale,
        });
    }
}

fn for_each_arena_pillar_obstacle(seed: u64, mut emit: impl FnMut(ArenaPillarObstacle)) {
    for_each_arena_pillar(seed, |pillar| {
        let base_y = height_at(seed, pillar.x, pillar.z);
        emit(ArenaPillarObstacle {
            center_x: pillar.x,
            center_y: base_y + pillar.height * 0.5,
            center_z: pillar.z,
            half_x: 0.55,
            half_y: pillar.height * 0.5,
            half_z: 0.55,
            collider_radius: arena_layout().pillar_collider_radius,
        });
    });
}
