use spacetimedb::{table, ReducerContext, Table, Timestamp};

#[allow(unused_imports)]
use crate::contract_version::contract_version as _;

/// Netcode audit R5: content stamps for the shared-JSON contract surface.
/// One static row per `*.shared.json` known to the server package. The client
/// hashes its bundled copies on connect and warns on mismatch — the shared
/// collision/heightfield data must match exactly for movement parity, and
/// the sync step (`GameplayCollisionExporter.SyncSharedMovementData`) is
/// easy to forget.
#[table(accessor = contract_version, public)]
#[derive(Clone)]
pub struct ContractVersion {
    #[primary_key]
    pub key: String,
    pub content_hash: u64,
    pub stamped_at: Timestamp,
}

// `(key, hash)` for every shared JSON under `src/`, generated by build.rs.
// Keys are server-relative paths; the client maps `world_data/` to its
// bundled `SharedData/Worlds/` copies and ignores keys it has no copy of.
include!(concat!(env!("OUT_DIR"), "/shared_file_hashes.rs"));

#[cfg(test)]
const FNV_OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
#[cfg(test)]
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

/// FNV-1a over the file bytes, skipping CR so checkouts with different line
/// endings hash identically. Mirrored by `ContractVersionGuard` on the
/// client — keep the two implementations in sync.
#[cfg(test)]
pub(crate) fn shared_content_hash(contents: &str) -> u64 {
    let mut hash = FNV_OFFSET;
    for byte in contents.bytes() {
        if byte == b'\r' {
            continue;
        }
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

/// Change-gated upsert: writes nothing when stamps are current. `init`
/// covers clean publishes; the `client_connected` call covers hot module
/// updates, which do not re-run `init`.
pub(crate) fn sync_contract_versions(ctx: &ReducerContext) {
    for (key, content_hash) in SHARED_FILE_HASHES {
        match ctx.db.contract_version().key().find((*key).to_string()) {
            Some(existing) if existing.content_hash == *content_hash => {}
            Some(existing) => {
                ctx.db.contract_version().key().update(ContractVersion {
                    content_hash: *content_hash,
                    stamped_at: ctx.timestamp,
                    ..existing
                });
            }
            None => {
                ctx.db.contract_version().insert(ContractVersion {
                    key: (*key).to_string(),
                    content_hash: *content_hash,
                    stamped_at: ctx.timestamp,
                });
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every shared JSON compiled anywhere into the module must be stamped.
    /// Native-only: walks the authoritative source tree, which wasm cannot do.
    #[test]
    fn shared_files_list_is_complete() {
        // Both server and match-server compile shared content from server/src.
        let src_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../server/src");
        let mut on_disk = Vec::new();
        collect_shared_json(&src_root, &src_root, &mut on_disk);
        // build.rs also compiles this Unity-owned shared catalog from outside
        // src/ so the client can verify the authoritative server stamp.
        on_disk.push("weapon_appearance_catalog.shared.json".to_string());
        on_disk.sort();

        let mut listed: Vec<String> = SHARED_FILE_HASHES
            .iter()
            .map(|(key, _)| (*key).to_string())
            .collect();
        listed.sort();

        assert_eq!(
            listed, on_disk,
            "generated SHARED_FILE_HASHES is out of sync with src/**/*.shared.json"
        );
    }

    #[test]
    fn shared_content_hash_ignores_carriage_returns() {
        assert_eq!(shared_content_hash("a\r\nb"), shared_content_hash("a\nb"));
        assert_ne!(shared_content_hash("a\nb"), shared_content_hash("ab"));
    }

    fn collect_shared_json(root: &std::path::Path, dir: &std::path::Path, found: &mut Vec<String>) {
        for entry in std::fs::read_dir(dir).expect("readable src dir") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                collect_shared_json(root, &path, found);
            } else if path
                .file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.ends_with(".shared.json"))
            {
                found.push(
                    path.strip_prefix(root)
                        .expect("path under src root")
                        .to_string_lossy()
                        .replace('\\', "/"),
                );
            }
        }
    }
}
