//! Game Loop - The SOLE Authority on Physics State
//!
//! This module contains:
//! - GameLoopTimer table (for scheduled reducer)
//! - init reducer (starts the game loop)
//! - game_tick reducer (THE physics simulation)
//!
//! CRITICAL OWNERSHIP RULE:
//! `game_tick` is the ONLY reducer that writes to PlayerPhysics.
//! All movement state changes happen HERE and NOWHERE else.
//!
//! The game_tick reducer:
//! 1. Reads PlayerIntent (what player wants)
//! 2. Computes new physics state (what actually happens)
//! 3. Writes PlayerPhysics (authoritative result)
//! 4. Clears consumed intent flags (jump)
//!
//! Jump and landing transitions BOTH happen in this function.
//! You can read this one function to understand the complete state machine.

use spacetimedb::{reducer, table, Identity, ReducerContext, ScheduleAt, Table, Timestamp};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

// Import movement constants and helper
use crate::action_prediction::prune_predicted_action_results;
use crate::appearance::backfill_character_appearance_rows;
#[allow(unused_imports)]
use crate::arena::arena_instance as _;
#[allow(unused_imports)]
use crate::arena::player_open_world_scene as _;
#[allow(unused_imports)]
use crate::arena::player_world as _;
use crate::arena::{
    arena_seed_for_identity, backfill_player_open_world_scene_rows, backfill_player_world_rows,
    despawn_legacy_default_dummies, open_world_scene_name_for_identity, MATCH_PHASE_COUNTDOWN,
    MATCH_PHASE_IN_PROGRESS,
};
use crate::auto_attack::tick_auto_attacks;
use crate::combat::player_snapshot::PlayerSnapshotSet;
use crate::combat::{
    clear_statuses_for_dead_players, expire_combat_engagements, expire_status_effects,
    has_due_pending_effects, movement_modifiers, normalize_legacy_hot_status_rows,
    process_periodic_status_ticks, prune_combat_events, resolve_pending_effects, respawn_player,
    sync_combat_projectile_definitions, sync_player_state_derived_stats, tick_auras,
    tick_combat_projectiles_with_snapshots, tick_combat_stacking_passives, MovementModifiers,
};
use crate::defense::prune_defense_states;
use crate::derived_stats::derived_combat_stats_for_owner;
use crate::inventory::{
    equipment_modifier_totals_for_owner, sync_item_definitions, tick_equipment_periodic_effects,
};
use crate::melee::{
    has_due_pending_melee_impacts, has_due_pending_projectile_releases,
    resolve_pending_melee_impacts, resolve_pending_projectile_releases, sync_melee_definitions,
    tick_pending_melee_timed_movements, tick_queued_melee_followups,
};
use crate::movement::{
    velocity_from_intent, FIXED_TICK_MILLIS, FIXED_TICK_SECONDS, GRAVITY, JUMP_VELOCITY,
    MOVE_SPEED, ZERO_INPUT_EPSILON,
};
use crate::movement_actions::{
    reset_dodge_charge_state_to_full, sync_all_fixed_action_charge_states,
    tick_fixed_action_charge_states, tick_movement_actions,
};
use crate::npcs::{prune_due_npc_corpse_despawns, tick_npc_combat};
use crate::party::expire_party_invites;
use crate::player_input::{
    clear_pending_player_commands, clear_pending_player_commands_through_tick, pop_command_for_tick,
};
use crate::player_intent::PlayerIntent;
use crate::player_physics::{commit_player_physics, PhysicsWriteMode, PlayerPhysics};
use crate::playground_targets::is_playground_target;
use crate::practice::{is_training_instance, tick_practice};
use crate::progression::{
    backfill_character_action_bar_rows, backfill_sword_and_shield_visible_action_bar_rows,
    clear_generic_fixed_action_bar_assignments, migrate_renamed_skyfall_action_bar_assignments,
    sync_progression_catalogs,
};
use crate::resources::{
    reset_player_resources_to_full, sync_all_player_resources, sync_primary_resource_for_player,
    tick_primary_resource_for_player,
};
use crate::spells::{
    has_due_pending_area_impacts, resolve_pending_area_impacts, resolve_pending_casts,
    resolve_special_movement_y, sync_spell_definitions, tick_active_casts,
    tick_bespoke_spells_with_snapshots,
};
use crate::world_collision::{
    preload_world_collision_data, resolve_world_horizontal_sweep_collision_y_with_layout_for_scene,
    surface_height_for_world_at_y_with_layout, surface_height_for_world_at_y_with_layout_for_scene,
};

// Import accessor traits (generated by #[table] macro, needed for ctx.db.table_name())
#[allow(unused_imports)]
use crate::combat::active_combat_projectile as _;
#[allow(unused_imports)]
use crate::movement_actions::fixed_action_charge_state as _;
#[allow(unused_imports)]
use crate::movement_actions::movement_action_state as _;
#[allow(unused_imports)]
use crate::player::player as _;
#[allow(unused_imports)]
use crate::player_input::player_command as _;
#[allow(unused_imports)]
use crate::player_input::player_input_cursor as _;
#[allow(unused_imports)]
use crate::player_intent::player_intent as _;
#[allow(unused_imports)]
use crate::player_physics::player_physics as _;
#[allow(unused_imports)]
use crate::player_state::player_state as _;
#[allow(unused_imports)]
use crate::spells::active_bespoke_spell as _;
#[allow(unused_imports)]
use crate::spells::active_cast as _;
#[allow(unused_imports)]
use crate::spells::special_movement_runtime as _;

const MAX_HORIZONTAL_COLLISION_STEP: f32 = 0.10;
const MAX_GROUNDED_SNAP_DOWN: f32 = 0.75;
const GAME_TICK_INTERVAL: Duration = Duration::from_millis(FIXED_TICK_MILLIS);
const EVENT_PRUNE_INTERVAL: Duration = Duration::from_millis(500);
const TICK_PROFILE_ENV_VAR: &str = "ARENA_PROFILE_TICKS";
const TICK_PROFILE_WINDOW_MICROS: i64 = 5_000_000;
const TICK_BUDGET_MICROS: u32 = FIXED_TICK_MILLIS as u32 * 1_000;
const SPECIAL_MOVEMENT_PATH_INSTANT: &str = "INSTANT";
const SPECIAL_MOVEMENT_FACING_FACE_PATH: &str = "FACE_PATH";
const SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y: &str = "STOP_AT_BLOCK_FIXED_Y";
const SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY: &str =
    "STOP_AT_BLOCK_KEEP_HEIGHT";
const SPECIAL_MOVEMENT_INPUT_DISCARD_LEAD_TICKS: u32 = 4;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct TickProfileSample {
    total_micros: u32,
    pre_tick_micros: u32,
    player_sim_micros: u32,
    post_tick_micros: u32,
    match_maintenance_micros: u32,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct TickPhaseSummary {
    p95_micros: u32,
    max_micros: u32,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct TickProfileSummary {
    count: usize,
    total_p50_micros: u32,
    total_p95_micros: u32,
    total_p99_micros: u32,
    total_max_micros: u32,
    over_budget_count: usize,
    max_consecutive_over_budget: usize,
    pre_tick: TickPhaseSummary,
    player_sim: TickPhaseSummary,
    post_tick: TickPhaseSummary,
    match_maintenance: TickPhaseSummary,
}

#[derive(Default)]
struct TickProfileWindowState {
    window_started_at_micros: Option<i64>,
    total_micros: Vec<u32>,
    pre_tick_micros: Vec<u32>,
    player_sim_micros: Vec<u32>,
    post_tick_micros: Vec<u32>,
    match_maintenance_micros: Vec<u32>,
    over_budget_count: usize,
    consecutive_over_budget: usize,
    max_consecutive_over_budget: usize,
}

impl TickProfileWindowState {
    fn record(&mut self, now_micros: i64, sample: TickProfileSample) -> Option<TickProfileSummary> {
        if self.window_started_at_micros.is_none() {
            self.window_started_at_micros = Some(now_micros);
        }

        self.total_micros.push(sample.total_micros);
        self.pre_tick_micros.push(sample.pre_tick_micros);
        self.player_sim_micros.push(sample.player_sim_micros);
        self.post_tick_micros.push(sample.post_tick_micros);
        self.match_maintenance_micros
            .push(sample.match_maintenance_micros);

        if sample.total_micros > TICK_BUDGET_MICROS {
            self.over_budget_count += 1;
            self.consecutive_over_budget += 1;
            self.max_consecutive_over_budget = self
                .max_consecutive_over_budget
                .max(self.consecutive_over_budget);
        } else {
            self.consecutive_over_budget = 0;
        }

        let window_started_at_micros = self.window_started_at_micros.unwrap_or(now_micros);
        if now_micros.saturating_sub(window_started_at_micros) < TICK_PROFILE_WINDOW_MICROS {
            return None;
        }

        self.flush()
    }

    fn flush(&mut self) -> Option<TickProfileSummary> {
        if self.total_micros.is_empty() {
            self.window_started_at_micros = None;
            self.consecutive_over_budget = 0;
            return None;
        }

        let summary = TickProfileSummary {
            count: self.total_micros.len(),
            total_p50_micros: percentile_value(&self.total_micros, 50, 100),
            total_p95_micros: percentile_value(&self.total_micros, 95, 100),
            total_p99_micros: percentile_value(&self.total_micros, 99, 100),
            total_max_micros: max_value(&self.total_micros),
            over_budget_count: self.over_budget_count,
            max_consecutive_over_budget: self.max_consecutive_over_budget,
            pre_tick: summarize_phase(&self.pre_tick_micros),
            player_sim: summarize_phase(&self.player_sim_micros),
            post_tick: summarize_phase(&self.post_tick_micros),
            match_maintenance: summarize_phase(&self.match_maintenance_micros),
        };

        self.window_started_at_micros = None;
        self.total_micros.clear();
        self.pre_tick_micros.clear();
        self.player_sim_micros.clear();
        self.post_tick_micros.clear();
        self.match_maintenance_micros.clear();
        self.over_budget_count = 0;
        self.consecutive_over_budget = 0;
        self.max_consecutive_over_budget = 0;

        Some(summary)
    }
}

fn max_value(values: &[u32]) -> u32 {
    values.iter().copied().max().unwrap_or(0)
}

fn summarize_phase(values: &[u32]) -> TickPhaseSummary {
    TickPhaseSummary {
        p95_micros: percentile_value(values, 95, 100),
        max_micros: max_value(values),
    }
}

fn percentile_value(values: &[u32], numerator: usize, denominator: usize) -> u32 {
    if values.is_empty() {
        return 0;
    }

    let mut sorted = values.to_vec();
    sorted.sort_unstable();
    percentile_sorted(&sorted, numerator, denominator)
}

fn percentile_sorted(sorted: &[u32], numerator: usize, denominator: usize) -> u32 {
    if sorted.is_empty() {
        return 0;
    }

    let rank = div_ceil(sorted.len() * numerator, denominator).saturating_sub(1);
    sorted[rank.min(sorted.len().saturating_sub(1))]
}

fn div_ceil(value: usize, divisor: usize) -> usize {
    if divisor == 0 {
        return 0;
    }
    (value + divisor - 1) / divisor
}

fn format_micros(micros: u32) -> String {
    format!("{:.2}ms", micros as f32 / 1_000.0)
}

fn tick_profile_store() -> &'static Mutex<TickProfileWindowState> {
    static TICK_PROFILE_STORE: OnceLock<Mutex<TickProfileWindowState>> = OnceLock::new();
    TICK_PROFILE_STORE.get_or_init(|| Mutex::new(TickProfileWindowState::default()))
}

fn record_tick_profile(now: Timestamp, sample: TickProfileSample) {
    let maybe_summary = {
        let mut state = tick_profile_store()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        state.record(now.to_micros_since_unix_epoch(), sample)
    };

    let Some(summary) = maybe_summary else {
        return;
    };

    log::info!(
        "[TICK_PROFILE] window=5.00s ticks={} total(p50/p95/p99/max)={}/{}/{}/{} over_budget={} max_consecutive_over_budget={} pre(p95/max)={}/{} player(p95/max)={}/{} post(p95/max)={}/{} match(p95/max)={}/{}",
        summary.count,
        format_micros(summary.total_p50_micros),
        format_micros(summary.total_p95_micros),
        format_micros(summary.total_p99_micros),
        format_micros(summary.total_max_micros),
        summary.over_budget_count,
        summary.max_consecutive_over_budget,
        format_micros(summary.pre_tick.p95_micros),
        format_micros(summary.pre_tick.max_micros),
        format_micros(summary.player_sim.p95_micros),
        format_micros(summary.player_sim.max_micros),
        format_micros(summary.post_tick.p95_micros),
        format_micros(summary.post_tick.max_micros),
        format_micros(summary.match_maintenance.p95_micros),
        format_micros(summary.match_maintenance.max_micros),
    );
}

fn elapsed_micros(started_at: Instant) -> u32 {
    started_at.elapsed().as_micros().min(u32::MAX as u128) as u32
}

fn tick_profiling_enabled() -> bool {
    static ENABLED: OnceLock<bool> = OnceLock::new();
    *ENABLED.get_or_init(|| {
        let Some(raw) = std::env::var_os(TICK_PROFILE_ENV_VAR) else {
            return false;
        };

        match raw.to_string_lossy().trim().to_ascii_lowercase().as_str() {
            "0" | "false" | "off" | "no" => false,
            "1" | "true" | "on" | "yes" => true,
            _ => {
                log::warn!(
                    "[INIT] Invalid {} value {:?}; defaulting to disabled",
                    TICK_PROFILE_ENV_VAR,
                    raw
                );
                false
            }
        }
    })
}

pub(crate) fn ensure_game_loop_schedule(ctx: &ReducerContext) {
    if ctx.db.game_loop_timer().iter().next().is_some() {
        return;
    }

    ctx.db.game_loop_timer().insert(GameLoopTimer {
        scheduled_id: 0,
        scheduled_at: ScheduleAt::Interval(GAME_TICK_INTERVAL.into()),
    });
    log::info!("[GAME_LOOP] Scheduled game_tick at 30.3Hz (33ms tick)");
}

fn bootstrap_server_state(ctx: &ReducerContext) {
    let collision_summary = preload_world_collision_data();
    log::info!(
        "[INIT] Preloaded world collision data scenes={} arena_gameplay_boxes={} arena_query_boxes={} arena_query_mesh_geometries={} arena_query_mesh_instances={} arena_query_mesh_triangles={} open_world_gameplay_boxes={} open_world_query_boxes={} open_world_query_mesh_geometries={} open_world_query_mesh_instances={} open_world_query_mesh_triangles={} query_mesh_bvh_nodes={} broadphase_cells={} broadphase_index_entries={} broadphase_max_cell_occupancy={} broadphase_max_cells_per_collider={} broadphase_unindexed_colliders={} generated_open_world_colliders={}",
        collision_summary.scene_count,
        collision_summary.arena_gameplay_boxes,
        collision_summary.arena_query_boxes,
        collision_summary.arena_query_mesh_geometries,
        collision_summary.arena_query_mesh_instances,
        collision_summary.arena_query_mesh_triangles,
        collision_summary.open_world_gameplay_boxes,
        collision_summary.open_world_query_boxes,
        collision_summary.open_world_query_mesh_geometries,
        collision_summary.open_world_query_mesh_instances,
        collision_summary.open_world_query_mesh_triangles,
        collision_summary.query_mesh_bvh_nodes,
        collision_summary.broadphase_cells,
        collision_summary.broadphase_index_entries,
        collision_summary.broadphase_max_cell_occupancy,
        collision_summary.broadphase_max_cells_per_collider,
        collision_summary.broadphase_unindexed_colliders,
        collision_summary.generated_open_world_colliders
    );
    if collision_summary.broadphase_unindexed_colliders > 0 {
        log::warn!(
            "[INIT] World collision broadphase left {} gameplay collider(s) unindexed; affected queries will fall back to full scan to avoid false negatives.",
            collision_summary.broadphase_unindexed_colliders
        );
    }

    sync_progression_catalogs(ctx);
    sync_item_definitions(ctx);
    sync_combat_projectile_definitions(ctx);
    sync_spell_definitions(ctx);
    sync_melee_definitions(ctx);
    sync_all_player_resources(ctx, ctx.timestamp);
    sync_all_fixed_action_charge_states(ctx, ctx.timestamp);
    let removed_generic_fixed_action_bar_rows = clear_generic_fixed_action_bar_assignments(ctx);
    if removed_generic_fixed_action_bar_rows > 0 {
        log::warn!(
            "[INIT] Removed {} legacy generic fixed action-bar assignment row(s)",
            removed_generic_fixed_action_bar_rows
        );
    }
    let migrated_skyfall_action_bar_rows = migrate_renamed_skyfall_action_bar_assignments(ctx);
    if migrated_skyfall_action_bar_rows > 0 {
        log::warn!(
            "[INIT] Migrated {} renamed Skyfall action-bar assignment row(s)",
            migrated_skyfall_action_bar_rows
        );
    }
    let repaired_action_bar_rows = backfill_character_action_bar_rows(ctx);
    if repaired_action_bar_rows > 0 {
        log::warn!(
            "[INIT] Backfilled default action bars for {} character(s)",
            repaired_action_bar_rows
        );
    }
    let repaired_sword_and_shield_visible_rows =
        backfill_sword_and_shield_visible_action_bar_rows(ctx);
    if repaired_sword_and_shield_visible_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} SwordAndShield visible action-bar assignment row(s)",
            repaired_sword_and_shield_visible_rows
        );
    }
    let repaired_appearance_rows = backfill_character_appearance_rows(ctx);
    if repaired_appearance_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} missing character appearance rows",
            repaired_appearance_rows
        );
    }
    let repaired_hot_rows = normalize_legacy_hot_status_rows(ctx);
    if repaired_hot_rows > 0 {
        log::warn!(
            "[INIT] Normalized {} legacy HOT status rows with negative tick_amount",
            repaired_hot_rows
        );
    }
    sync_progression_runtime_rows(ctx, ctx.timestamp);
}

/// Schedule table for the game loop.
/// Inserting a row schedules game_tick to run.
#[table(accessor = game_loop_timer, scheduled(game_tick))]
pub struct GameLoopTimer {
    #[primary_key]
    #[auto_inc]
    pub scheduled_id: u64,
    pub scheduled_at: ScheduleAt,
}

/// Module initialization - starts the game loop.
#[reducer(init)]
pub fn init(ctx: &ReducerContext) -> Result<(), String> {
    ensure_game_loop_schedule(ctx);
    bootstrap_server_state(ctx);
    despawn_legacy_default_dummies(ctx);

    let repaired_rows = backfill_player_world_rows(ctx);
    if repaired_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} missing player_world rows as open-world",
            repaired_rows
        );
    }
    let repaired_scene_rows = backfill_player_open_world_scene_rows(ctx);
    if repaired_scene_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} missing player_open_world_scene rows with default open-world scene",
            repaired_scene_rows
        );
    }

    log::info!("[INIT] Game loop started at 30.3Hz (33ms tick)");
    if tick_profiling_enabled() {
        log::info!(
            "[INIT] Tick profiling enabled via {}. Logging 5.00s rolling stats; target p95 < 20ms, p99 < 28ms, no sustained ticks over {}ms.",
            TICK_PROFILE_ENV_VAR,
            FIXED_TICK_MILLIS
        );
    }
    Ok(())
}

fn resolve_combat_cycle(ctx: &ReducerContext, now: Timestamp) {
    resolve_pending_melee_impacts(ctx, now);
    resolve_pending_projectile_releases(ctx, now);
    resolve_pending_area_impacts(ctx, now);
    resolve_pending_effects(ctx, now);
    clear_statuses_for_dead_players(ctx);
    expire_status_effects(ctx, now);
    prune_defense_states(ctx, now);
}

fn resolve_combat_cycle_if_needed(ctx: &ReducerContext, now: Timestamp) {
    if has_due_pending_melee_impacts(ctx, now)
        || has_due_pending_projectile_releases(ctx, now)
        || has_due_pending_area_impacts(ctx, now)
        || has_due_pending_effects(ctx, now)
    {
        resolve_combat_cycle(ctx, now);
    }
}

fn should_prune_events(now: Timestamp) -> bool {
    let now_micros = now.to_micros_since_unix_epoch();
    let tick_micros = GAME_TICK_INTERVAL.as_micros() as i64;
    let prune_micros = EVENT_PRUNE_INTERVAL.as_micros() as i64;
    let previous_tick_micros = now_micros.saturating_sub(tick_micros);
    now_micros.div_euclid(prune_micros) != previous_tick_micros.div_euclid(prune_micros)
}

fn run_pre_tick_housekeeping_phase(
    ctx: &ReducerContext,
    now: Timestamp,
    dt: f32,
) -> Result<MovementModifiers, String> {
    sync_progression_runtime_rows(ctx, now);
    tick_fixed_action_charge_states(ctx, now);
    tick_practice(ctx, now)?;
    // Cancel invalid movement actions before authored displacement is sampled.
    tick_movement_actions(ctx, now);
    tick_pending_melee_timed_movements(ctx, now);
    tick_special_movement_runtimes(ctx, now);

    // Resolve active cast completion/cancellation before combat resolution.
    tick_active_casts(ctx, now)?;
    // Movement delivery uses active_cast as a completion/impact latch, so clean
    // the replicated movement-action mirror after completion/cancel.
    tick_movement_actions(ctx, now);

    // Buffered melee follow-ups release here once their authored combo
    // transition timing has elapsed.
    tick_queued_melee_followups(ctx, now);
    tick_auto_attacks(ctx, now);
    tick_npc_combat(ctx, now);

    // Pass A: resolve effects already queued (casts/reducers from previous frame boundary).
    resolve_combat_cycle_if_needed(ctx, now);

    // Spell/projectile simulation can enqueue effects based on current
    // authoritative state. These phases run before their queued effects are
    // resolved, so they can share one phase-local player snapshot set.
    let has_active_bespoke_spells = ctx.db.active_bespoke_spell().iter().next().is_some();
    let has_active_combat_projectiles = ctx.db.active_combat_projectile().iter().next().is_some();
    if has_active_bespoke_spells || has_active_combat_projectiles {
        let player_snapshots = PlayerSnapshotSet::collect(ctx);
        tick_bespoke_spells_with_snapshots(ctx, dt, &player_snapshots)?;
        tick_combat_projectiles_with_snapshots(ctx, dt, &player_snapshots)?;
    }

    // Periodic DOT/HOT effects can enqueue additional rows in the same frame.
    let periodic_queued = process_periodic_status_ticks(ctx, now);
    let equipment_periodic_queued = tick_equipment_periodic_effects(ctx, now, dt);
    if periodic_queued > 0
        || equipment_periodic_queued > 0
        || has_due_pending_melee_impacts(ctx, now)
        || has_due_pending_projectile_releases(ctx, now)
        || has_due_pending_area_impacts(ctx, now)
        || has_due_pending_effects(ctx, now)
    {
        // Single post-simulation pass resolves both spell-sim and periodic queues.
        resolve_combat_cycle(ctx, now);
    }
    tick_combat_stacking_passives(ctx, now);
    tick_auras(ctx, now);
    expire_combat_engagements(ctx, now);
    expire_status_effects(ctx, now);

    Ok(movement_modifiers(ctx, now))
}

fn sync_progression_runtime_rows(ctx: &ReducerContext, now: Timestamp) {
    let owners: Vec<_> = ctx
        .db
        .player_state()
        .iter()
        .filter(|row| !row.is_dummy)
        .map(|row| row.player_id)
        .collect();
    for owner in owners {
        sync_player_state_derived_stats(ctx, owner);
        sync_primary_resource_for_player(ctx, owner, now);
    }
}

fn run_player_simulation_phase(
    ctx: &ReducerContext,
    now: Timestamp,
    dt: f32,
    movement_modifiers: &MovementModifiers,
) {
    let player_ids: Vec<_> = ctx.db.player_physics().iter().map(|p| p.identity).collect();
    for identity in player_ids {
        tick_player(ctx, identity, now, dt, movement_modifiers);
    }
}

fn run_post_tick_maintenance_phase(ctx: &ReducerContext, now: Timestamp) {
    prune_due_npc_corpse_despawns(ctx, now);
    if should_prune_events(now) {
        prune_combat_events(ctx, now);
        prune_predicted_action_results(ctx, now);
    }
}

fn run_match_world_maintenance_phase(ctx: &ReducerContext, now: Timestamp) {
    tick_countdowns(ctx, now);
    expire_party_invites(ctx, now);
}

fn try_tick_dead_player(
    ctx: &ReducerContext,
    now: Timestamp,
    physics: &mut PlayerPhysics,
    state: &mut crate::player_state::PlayerState,
) -> bool {
    if state.alive {
        return false;
    }

    if state.eliminated {
        return true;
    }

    if now >= state.respawn_at {
        let (spawn_x, spawn_y, spawn_z, spawn_yaw) = respawn_player(ctx, state);
        physics.pos_x = spawn_x;
        physics.pos_y = spawn_y;
        physics.pos_z = spawn_z;
        physics.vel_x = 0.0;
        physics.vel_y = 0.0;
        physics.vel_z = 0.0;
        physics.yaw = spawn_yaw;
        physics.grounded = true;
        physics.updated_at = now;
        if let Some(mut intent) = ctx.db.player_intent().identity().find(state.player_id) {
            intent.forward = 0.0;
            intent.strafe = 0.0;
            intent.yaw = spawn_yaw;
            intent.jump = false;
            intent.input_tick = physics.last_processed_tick;
            intent.updated_at = now;
            ctx.db.player_intent().identity().update(intent);
        }
        reset_player_resources_to_full(ctx, state.player_id, now);
        reset_dodge_charge_state_to_full(ctx, state.player_id, now);
        clear_pending_player_commands(ctx, state.player_id);
    }

    true
}

fn try_tick_dummy_player(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    physics: &mut PlayerPhysics,
    state: &crate::player_state::PlayerState,
) -> bool {
    if !state.is_dummy {
        return false;
    }

    if ctx
        .db
        .special_movement_runtime()
        .owner()
        .find(identity)
        .is_some()
    {
        return true;
    }

    let flat_ground_only = uses_flat_training_collision(ctx, identity);
    let ground_y = surface_height_for_world_at_y_with_layout(
        arena_seed_for_identity(ctx, identity),
        flat_ground_only,
        physics.pos_x,
        physics.pos_z,
        physics.pos_y,
    );
    settle_stationary_dummy(physics, ground_y, now);

    true
}

fn try_tick_playground_target(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    physics: &mut PlayerPhysics,
) -> bool {
    if !is_playground_target(ctx, identity) {
        return false;
    }

    ctx.db.special_movement_runtime().owner().delete(identity);
    settle_stationary_playground_target(physics, now);
    true
}

fn settle_stationary_playground_target(physics: &mut PlayerPhysics, now: Timestamp) {
    physics.vel_x = 0.0;
    physics.vel_y = 0.0;
    physics.vel_z = 0.0;
    physics.grounded = true;
    physics.updated_at = now;
}

fn settle_stationary_dummy(physics: &mut PlayerPhysics, ground_y: f32, now: Timestamp) {
    physics.pos_y = ground_y;
    physics.vel_x = 0.0;
    physics.vel_y = 0.0;
    physics.vel_z = 0.0;
    physics.grounded = true;
    physics.updated_at = now;
}

#[allow(clippy::too_many_arguments)]
fn simulate_non_dummy_player_kinematics(
    identity: Identity,
    physics: &mut PlayerPhysics,
    intent: &PlayerIntent,
    arena_seed: Option<u64>,
    flat_ground_only: bool,
    open_world_scene_name: String,
    now: Timestamp,
    dt: f32,
    movement_blocked: bool,
    move_speed_multiplier: f32,
    hit_radius: f32,
    hit_height: f32,
) {
    let ground_at = |x: f32, z: f32, probe_y: f32| -> f32 {
        surface_height_for_world_at_y_with_layout_for_scene(
            arena_seed,
            flat_ground_only,
            Some(open_world_scene_name.as_str()),
            x,
            z,
            probe_y,
        )
    };

    if physics.grounded {
        // Pre-step stabilization: terrain can shift under the player between ticks.
        // We still resnap after integration for final authoritative placement.
        physics.pos_y = ground_at(physics.pos_x, physics.pos_z, physics.pos_y);
    }

    // === Step 1: Always update yaw from intent ===
    // Player can rotate regardless of grounded state
    physics.yaw = intent.yaw;

    // === Step 2: Branch on grounded state ===
    if physics.grounded {
        // --- GROUNDED BRANCH ---
        if !movement_blocked {
            // Compute velocity from intent
            let (vel_x, vel_z) = velocity_from_intent(
                intent.forward,
                intent.strafe,
                intent.yaw,
                MOVE_SPEED * move_speed_multiplier,
            );
            physics.vel_x = vel_x;
            physics.vel_z = vel_z;
        }
        physics.vel_y = 0.0; // No vertical velocity when grounded

        // Check for jump request
        if intent.jump && !movement_blocked {
            // === JUMP TRANSITION ===
            // This is the ONLY place grounded becomes false
            log::debug!(
                "[JUMP] Player {} | pos_y={:.2} | vel=({:.2},{:.2},{:.2}) | grounded: true -> false",
                &identity.to_hex()[..8],
                physics.pos_y,
                physics.vel_x,
                physics.vel_y,
                physics.vel_z
            );

            physics.grounded = false;
            physics.vel_y = JUMP_VELOCITY;

            // Horizontal velocity is already set from intent above.
            // It will be LOCKED (not overwritten) while airborne.
            // No separate preserved_vel field needed.
        }
    } else {
        // --- AIRBORNE BRANCH ---

        // Horizontal velocity is LOCKED - do not modify vel_x or vel_z
        // This is the "preservation" - we simply don't touch them.

        // Apply gravity to vertical velocity
        physics.vel_y += GRAVITY * dt;
    }

    if movement_blocked {
        // Root is an immediate horizontal stop, including while airborne.
        physics.vel_x = 0.0;
        physics.vel_z = 0.0;
    }

    // === Step 3: Integrate position ===
    // This happens regardless of grounded state.
    // CRITICAL: This happens in the SAME tick as jump transition.
    let delta_x = physics.vel_x * dt;
    let delta_z = physics.vel_z * dt;
    let max_delta = delta_x.abs().max(delta_z.abs());
    let step_count = ((max_delta / MAX_HORIZONTAL_COLLISION_STEP).ceil() as usize).max(1);
    let step_x = delta_x / step_count as f32;
    let step_z = delta_z / step_count as f32;
    let mut next_x = physics.pos_x;
    let mut next_z = physics.pos_z;

    for _ in 0..step_count {
        let target_x = next_x + step_x;
        let target_z = next_z + step_z;
        let (resolved_x, resolved_z) =
            resolve_world_horizontal_sweep_collision_y_with_layout_for_scene(
                arena_seed,
                flat_ground_only,
                Some(open_world_scene_name.as_str()),
                next_x,
                next_z,
                target_x,
                target_z,
                hit_radius.max(0.1),
                hit_height.max(0.5),
                physics.pos_y,
            );
        next_x = resolved_x;
        next_z = resolved_z;
    }

    physics.pos_x = next_x;
    physics.pos_z = next_z;

    if physics.grounded {
        let ground_y = ground_at(physics.pos_x, physics.pos_z, physics.pos_y);
        let drop_to_ground = physics.pos_y - ground_y;
        if drop_to_ground <= MAX_GROUNDED_SNAP_DOWN {
            // Small step-down or incline change: keep grounded and snap.
            physics.pos_y = ground_y;
        } else {
            // Walking off a ledge: transition to airborne instead of teleporting down.
            // We intentionally defer landing checks until the next fully-airborne frame.
            physics.grounded = false;
            physics.vel_y = GRAVITY * dt;
            physics.pos_y += physics.vel_y * dt;
        }
    } else {
        // Capture the pre-integration height so landing probes can detect crossing this frame.
        let previous_y = physics.pos_y;
        physics.pos_y += physics.vel_y * dt;
        let ground_y = ground_at(physics.pos_x, physics.pos_z, previous_y);

        // === Step 4: Check landing (ONLY if airborne) ===
        // Landing condition: crossed below sampled walkable surface AND descending.
        // We probe with previous_y so high-speed falls cannot skip narrow tops.
        // Both conditions required - prevents landing while ascending.
        // This check happens AFTER integration - player has moved.
        if physics.pos_y <= ground_y && physics.vel_y <= 0.0 {
            // === LANDING TRANSITION ===
            // This is the ONLY place grounded becomes true (after initial spawn)
            log::debug!(
                "[LAND] Player {} | pos_y={:.2} | vel_y={:.2} | grounded: false -> true",
                &identity.to_hex()[..8],
                physics.pos_y,
                physics.vel_y
            );

            physics.pos_y = ground_y; // Snap to sampled ground
            physics.vel_y = 0.0; // Stop falling
            physics.grounded = true;

            // Note: vel_x and vel_z retain their values from airtime.
            // Next tick (grounded), they'll be recomputed from intent.
            // This prevents stale velocity issues.
        }
    }

    physics.updated_at = now;
}

fn uses_flat_training_collision(ctx: &ReducerContext, identity: Identity) -> bool {
    let Some(world) = ctx.db.player_world().identity().find(identity) else {
        return false;
    };

    let Some(instance_id) = world.instance_id else {
        return false;
    };

    is_training_instance(ctx, instance_id)
}

fn sync_player_movement_context(
    state: &mut crate::player_state::PlayerState,
    movement_blocked: bool,
    move_speed_multiplier: f32,
    movement_context_tick: u32,
) -> bool {
    let clamped_multiplier = move_speed_multiplier.clamp(0.0, 4.0);
    let multiplier_changed = (state.move_speed_multiplier - clamped_multiplier).abs() > 0.0001;
    let changed = state.movement_blocked != movement_blocked
        || multiplier_changed
        || state.movement_context_tick != movement_context_tick;

    if !changed {
        return false;
    }

    state.movement_blocked = movement_blocked;
    state.move_speed_multiplier = clamped_multiplier;
    state.movement_context_tick = movement_context_tick;
    true
}

fn sync_player_voluntary_move_epoch(
    state: &mut crate::player_state::PlayerState,
    movement_blocked: bool,
    intent: &PlayerIntent,
    grounded_before_step: bool,
    command_input_tick: Option<u32>,
) -> bool {
    if movement_blocked {
        return false;
    }

    // Axis input is voluntary even if some other force also moves the player.
    // Jump only counts when the server could accept it from a grounded step.
    let accepted_move = intent.forward.abs() > ZERO_INPUT_EPSILON
        || intent.strafe.abs() > ZERO_INPUT_EPSILON
        || (intent.jump && grounded_before_step);
    if !accepted_move {
        return false;
    }

    state.voluntary_move_epoch = state.voluntary_move_epoch.saturating_add(1);
    if let Some(command_input_tick) = command_input_tick {
        state.last_voluntary_move_input_tick = command_input_tick;
    }
    true
}

fn tick_special_movement_runtimes(ctx: &ReducerContext, now: Timestamp) {
    let runtimes: Vec<crate::spells::SpecialMovementRuntime> =
        ctx.db.special_movement_runtime().iter().collect();
    for runtime in runtimes {
        if is_playground_target(ctx, runtime.owner) {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        }

        let Some(mut physics) = ctx.db.player_physics().identity().find(runtime.owner) else {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        };
        let Some(state) = ctx.db.player_state().player_id().find(runtime.owner) else {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        };
        if !state.alive {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        }

        let (desired_x, desired_y, desired_z, desired_yaw, finished) =
            sample_special_movement_pose(&runtime, now);
        let arena_seed = arena_seed_for_identity(ctx, runtime.owner);
        let flat_ground_only = uses_flat_training_collision(ctx, runtime.owner);
        let ground_y = surface_height_for_world_at_y_with_layout(
            arena_seed,
            flat_ground_only,
            desired_x,
            desired_z,
            desired_y,
        );
        let resolved_y = resolve_special_movement_y(
            &runtime.collision_policy,
            runtime.start_y,
            desired_y,
            ground_y,
        );

        let prev_x = physics.pos_x;
        let prev_y = physics.pos_y;
        let prev_z = physics.pos_z;
        physics.pos_x = desired_x;
        physics.pos_y = resolved_y;
        physics.pos_z = desired_z;
        physics.yaw = desired_yaw;
        if finished {
            // Prevent residual authored-movement velocity from carrying into
            // normal physics (airborne lock would otherwise slide the player
            // past the destination). Grounded state is handed back to normal
            // physics instead of being reclassified from terrain here.
            physics.vel_x = 0.0;
            physics.vel_y = 0.0;
            physics.vel_z = 0.0;
        } else {
            physics.vel_x = (desired_x - prev_x) / FIXED_TICK_SECONDS;
            physics.vel_y = (resolved_y - prev_y) / FIXED_TICK_SECONDS;
            physics.vel_z = (desired_z - prev_z) / FIXED_TICK_SECONDS;
        }
        physics.grounded =
            special_movement_grounded_state(&runtime.collision_policy, physics.grounded);
        physics.updated_at = now;
        let handoff_input_tick = physics.last_processed_tick;
        let handoff_yaw = physics.yaw;
        commit_player_physics(
            ctx,
            physics,
            PhysicsWriteMode::SpecialMovementTick,
            "tick_special_movement_runtimes",
        );

        if finished {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            reset_player_intent_after_special_movement(
                ctx,
                runtime.owner,
                handoff_input_tick,
                handoff_yaw,
                now,
            );
            // Drop queued commands and advance the receive cursor through the
            // normal client lead window. Commands authored during the special
            // movement can arrive after this reducer tick; rejecting that
            // in-flight window prevents a delayed jump edge from launching on
            // the first post-special-movement physics ticks.
            clear_pending_player_commands_through_tick(
                ctx,
                runtime.owner,
                handoff_input_tick.saturating_add(SPECIAL_MOVEMENT_INPUT_DISCARD_LEAD_TICKS),
            );
        }
    }
}

fn reset_player_intent_after_special_movement(
    ctx: &ReducerContext,
    identity: Identity,
    input_tick: u32,
    yaw: f32,
    now: Timestamp,
) {
    let Some(mut intent) = ctx.db.player_intent().identity().find(identity) else {
        return;
    };

    intent.forward = 0.0;
    intent.strafe = 0.0;
    intent.yaw = yaw;
    intent.jump = false;
    intent.input_tick = input_tick;
    intent.updated_at = now;
    ctx.db.player_intent().identity().update(intent);
}

fn special_movement_grounded_state(collision_policy: &str, current_grounded: bool) -> bool {
    if uses_fixed_y_collision_policy(collision_policy) {
        false
    } else {
        current_grounded
    }
}

fn sample_special_movement_pose(
    runtime: &crate::spells::SpecialMovementRuntime,
    now: Timestamp,
) -> (f32, f32, f32, f32, bool) {
    let start = runtime.started_at.to_micros_since_unix_epoch();
    let duration_micros = (runtime.duration_ms as i64).saturating_mul(1000);
    let end = start.saturating_add(duration_micros);
    let now_micros = now.to_micros_since_unix_epoch();
    let finished = runtime.duration_ms == 0 || now_micros >= end;

    if runtime.path_mode == SPECIAL_MOVEMENT_PATH_INSTANT || runtime.duration_ms == 0 {
        return (
            runtime.end_x,
            runtime.end_y,
            runtime.end_z,
            runtime.facing_yaw_start,
            true,
        );
    }

    let progress = if duration_micros <= 0 {
        1.0
    } else {
        ((now_micros - start) as f64 / duration_micros as f64).clamp(0.0, 1.0) as f32
    };
    let pos_x = runtime.start_x + (runtime.end_x - runtime.start_x) * progress;
    let pos_y = if uses_fixed_y_collision_policy(&runtime.collision_policy) {
        runtime.start_y
    } else {
        runtime.start_y + (runtime.end_y - runtime.start_y) * progress
    };
    let pos_z = runtime.start_z + (runtime.end_z - runtime.start_z) * progress;
    let yaw = if runtime.facing_policy == SPECIAL_MOVEMENT_FACING_FACE_PATH {
        let dx = runtime.end_x - runtime.start_x;
        let dz = runtime.end_z - runtime.start_z;
        if dx * dx + dz * dz > 0.0001 {
            dx.atan2(dz)
        } else {
            runtime.facing_yaw_start
        }
    } else {
        runtime.facing_yaw_start
    };

    (pos_x, pos_y, pos_z, yaw, finished)
}

fn uses_fixed_y_collision_policy(collision_policy: &str) -> bool {
    collision_policy == SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y
        || collision_policy == SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY
}

fn try_tick_special_movement_player(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    movement_blocked: bool,
    move_speed_multiplier: f32,
    physics: &mut PlayerPhysics,
    state: &mut crate::player_state::PlayerState,
    intent: &mut PlayerIntent,
) -> bool {
    if ctx
        .db
        .special_movement_runtime()
        .owner()
        .find(identity)
        .is_none()
    {
        return false;
    }

    let next_input_tick = physics.last_processed_tick.saturating_add(1);
    let mut step_intent = PlayerIntent {
        identity,
        forward: intent.forward,
        strafe: intent.strafe,
        yaw: intent.yaw,
        jump: false,
        input_tick: next_input_tick,
        updated_at: now,
    };
    if let Some(command) = pop_command_for_tick(ctx, identity, next_input_tick) {
        step_intent.forward = command.forward;
        step_intent.strafe = command.strafe;
        step_intent.yaw = command.yaw;
    }

    physics.last_processed_tick = next_input_tick;
    physics.updated_at = now;
    intent.forward = step_intent.forward;
    intent.strafe = step_intent.strafe;
    intent.yaw = step_intent.yaw;
    intent.jump = false;
    intent.input_tick = next_input_tick;
    intent.updated_at = now;
    ctx.db.player_intent().identity().update(PlayerIntent {
        identity: intent.identity,
        forward: intent.forward,
        strafe: intent.strafe,
        yaw: intent.yaw,
        jump: intent.jump,
        input_tick: intent.input_tick,
        updated_at: intent.updated_at,
    });

    let state_changed = sync_player_movement_context(
        state,
        movement_blocked,
        move_speed_multiplier,
        next_input_tick,
    );
    commit_player_physics(
        ctx,
        PlayerPhysics {
            identity: physics.identity,
            pos_x: physics.pos_x,
            pos_y: physics.pos_y,
            pos_z: physics.pos_z,
            vel_x: physics.vel_x,
            vel_y: physics.vel_y,
            vel_z: physics.vel_z,
            yaw: physics.yaw,
            grounded: physics.grounded,
            last_processed_tick: physics.last_processed_tick,
            updated_at: physics.updated_at,
        },
        PhysicsWriteMode::Normal,
        "try_tick_special_movement_player",
    );
    if state_changed {
        ctx.db
            .player_state()
            .player_id()
            .update(crate::player_state::PlayerState {
                player_id: state.player_id,
                is_dummy: state.is_dummy,
                alive: state.alive,
                eliminated: state.eliminated,
                hp: state.hp,
                max_hp: state.max_hp,
                hit_radius: state.hit_radius,
                hit_height: state.hit_height,
                movement_blocked: state.movement_blocked,
                move_speed_multiplier: state.move_speed_multiplier,
                movement_context_tick: state.movement_context_tick,
                voluntary_move_epoch: state.voluntary_move_epoch,
                last_voluntary_move_input_tick: state.last_voluntary_move_input_tick,
                respawn_at: state.respawn_at,
                last_strike_id: state.last_strike_id.clone(),
                last_strike_at: state.last_strike_at,
            });
    }

    true
}

fn tick_player(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    dt: f32,
    movement_modifiers: &MovementModifiers,
) {
    // Get current physics state
    let Some(mut physics) = ctx.db.player_physics().identity().find(identity) else {
        return;
    };

    // Get current player state
    let Some(mut state) = ctx.db.player_state().player_id().find(identity) else {
        return;
    };

    let next_input_tick = physics.last_processed_tick.saturating_add(1);
    let movement_blocked = movement_modifiers.blocks_movement(&identity);
    let mut move_speed_multiplier =
        movement_modifiers.move_speed_multiplier(&identity, next_input_tick);

    // Dead players ignore inputs and physics until respawn.
    if try_tick_dead_player(ctx, now, &mut physics, &mut state) {
        if state.alive {
            commit_player_physics(
                ctx,
                physics,
                PhysicsWriteMode::Force,
                "try_tick_dead_player_respawn",
            );
            ctx.db.player_state().player_id().update(state);
        }
        return;
    }

    if try_tick_playground_target(ctx, identity, now, &mut physics) {
        commit_player_physics(
            ctx,
            physics,
            PhysicsWriteMode::Normal,
            "try_tick_playground_target",
        );
        return;
    }

    if try_tick_dummy_player(ctx, identity, now, &mut physics, &state) {
        let movement_context_tick = physics.last_processed_tick;
        let state_changed = sync_player_movement_context(
            &mut state,
            movement_blocked,
            move_speed_multiplier,
            movement_context_tick,
        );
        commit_player_physics(
            ctx,
            physics,
            PhysicsWriteMode::Normal,
            "try_tick_dummy_player",
        );
        if state_changed {
            ctx.db.player_state().player_id().update(state);
        }
        return;
    }

    // Get current intent
    let Some(mut intent) = ctx.db.player_intent().identity().find(identity) else {
        return;
    };
    if try_tick_special_movement_player(
        ctx,
        identity,
        now,
        movement_blocked,
        move_speed_multiplier,
        &mut physics,
        &mut state,
        &mut intent,
    ) {
        return;
    }
    let mut step_intent = PlayerIntent {
        identity,
        forward: intent.forward,
        strafe: intent.strafe,
        yaw: intent.yaw,
        jump: false,
        input_tick: next_input_tick,
        updated_at: now,
    };
    let mut applied_command_input_tick = None;
    if let Some(command) = pop_command_for_tick(ctx, identity, next_input_tick) {
        step_intent.forward = command.forward;
        step_intent.strafe = command.strafe;
        step_intent.yaw = command.yaw;
        step_intent.jump = command.jump;
        step_intent.input_tick = next_input_tick;
        step_intent.updated_at = now;
        applied_command_input_tick = Some(command.input_tick);
    } else {
        // Command hasn't arrived yet — use latest known intent values.
        // The client's prediction deadband absorbs the small error from
        // the stale yaw. Always advance the tick so the server stays
        // current and spells/effects use an up-to-date position.
        log::debug!(
            "[MOVE_FALLBACK] Player {} | tick={} | using fallback intent from tick={}",
            &identity.to_hex()[..8],
            next_input_tick,
            intent.input_tick
        );
        step_intent.jump = false;
        step_intent.input_tick = next_input_tick;
        step_intent.updated_at = now;
    }

    let derived_stats = derived_combat_stats_for_owner(ctx, identity);
    move_speed_multiplier *= derived_stats.run_speed_multiplier;
    move_speed_multiplier *=
        equipment_modifier_totals_for_owner(ctx, identity).move_speed_multiplier();

    let grounded_before_step = physics.grounded;
    simulate_non_dummy_player_kinematics(
        identity,
        &mut physics,
        &step_intent,
        arena_seed_for_identity(ctx, identity),
        uses_flat_training_collision(ctx, identity),
        open_world_scene_name_for_identity(ctx, identity),
        now,
        dt,
        movement_blocked,
        move_speed_multiplier,
        state.hit_radius,
        state.hit_height,
    );
    physics.last_processed_tick = next_input_tick;
    intent.forward = step_intent.forward;
    intent.strafe = step_intent.strafe;
    intent.yaw = step_intent.yaw;
    intent.jump = false;
    intent.input_tick = next_input_tick;
    intent.updated_at = now;
    ctx.db.player_intent().identity().update(intent);
    tick_primary_resource_for_player(ctx, identity, now, dt);
    let voluntary_epoch_changed = sync_player_voluntary_move_epoch(
        &mut state,
        movement_blocked,
        &step_intent,
        grounded_before_step,
        applied_command_input_tick,
    );
    let state_changed = sync_player_movement_context(
        &mut state,
        movement_blocked,
        move_speed_multiplier,
        next_input_tick,
    ) || voluntary_epoch_changed;

    // === Step 5: Write physics state ===
    commit_player_physics(
        ctx,
        physics,
        PhysicsWriteMode::Normal,
        "simulate_non_dummy_player_kinematics",
    );
    if state_changed {
        ctx.db.player_state().player_id().update(state);
    }
}

/// The game tick - runs every 33ms.
///
/// This is the SOLE AUTHORITY on physics state.
///
/// The reducer is intentionally a phase orchestrator:
/// 1. Pre-tick housekeeping (casts, practice, queued combat/effects)
/// 2. Per-player authoritative simulation
/// 3. Post-tick pruning/maintenance
///
/// Physics ownership remains singular:
/// - `game_tick` is the only reducer that writes `PlayerPhysics`
/// - helpers may structure the logic, but they execute only inside this reducer
#[reducer]
pub fn game_tick(ctx: &ReducerContext, _timer: GameLoopTimer) -> Result<(), String> {
    let dt = FIXED_TICK_SECONDS;
    let now = ctx.timestamp;
    let profiling_enabled = tick_profiling_enabled();
    let total_started_at = profiling_enabled.then(Instant::now);

    let pre_tick_started_at = profiling_enabled.then(Instant::now);
    let movement_modifiers = run_pre_tick_housekeeping_phase(ctx, now, dt)?;
    let pre_tick_micros = pre_tick_started_at.map(elapsed_micros).unwrap_or(0);

    let player_sim_started_at = profiling_enabled.then(Instant::now);
    run_player_simulation_phase(ctx, now, dt, &movement_modifiers);
    resolve_pending_casts(ctx, now)?;
    let player_sim_micros = player_sim_started_at.map(elapsed_micros).unwrap_or(0);

    let post_tick_started_at = profiling_enabled.then(Instant::now);
    run_post_tick_maintenance_phase(ctx, now);
    let post_tick_micros = post_tick_started_at.map(elapsed_micros).unwrap_or(0);

    let match_maintenance_started_at = profiling_enabled.then(Instant::now);
    run_match_world_maintenance_phase(ctx, now);
    let match_maintenance_micros = match_maintenance_started_at
        .map(elapsed_micros)
        .unwrap_or(0);

    if let Some(total_started_at) = total_started_at {
        record_tick_profile(
            now,
            TickProfileSample {
                total_micros: elapsed_micros(total_started_at),
                pre_tick_micros,
                player_sim_micros,
                post_tick_micros,
                match_maintenance_micros,
            },
        );
    }

    Ok(())
}

const COUNTDOWN_DURATION: Duration = Duration::from_secs(3);

fn tick_countdowns(ctx: &ReducerContext, now: Timestamp) {
    let instances: Vec<_> = ctx
        .db
        .arena_instance()
        .iter()
        .filter(|a| a.phase == MATCH_PHASE_COUNTDOWN)
        .collect();

    for mut arena in instances {
        let Some(started_at) = arena.countdown_started_at else {
            continue;
        };
        let now_micros: i64 = now.to_micros_since_unix_epoch();
        let started_micros: i64 = started_at.to_micros_since_unix_epoch();
        let elapsed_micros = now_micros.saturating_sub(started_micros);
        if elapsed_micros >= COUNTDOWN_DURATION.as_micros() as i64 {
            arena.phase = MATCH_PHASE_IN_PROGRESS.to_string();
            arena.countdown_started_at = None;
            ctx.db.arena_instance().id().update(arena);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        percentile_sorted, settle_stationary_playground_target, special_movement_grounded_state,
        sync_player_voluntary_move_epoch, PlayerIntent, PlayerPhysics, TickProfileSample,
        TickProfileWindowState, SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y,
        SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY,
    };
    use crate::combat::new_player_state;
    use spacetimedb::{Identity, Timestamp};

    fn sample(total_micros: u32, pre_micros: u32) -> TickProfileSample {
        TickProfileSample {
            total_micros,
            pre_tick_micros: pre_micros,
            player_sim_micros: pre_micros / 2,
            post_tick_micros: pre_micros / 4,
            match_maintenance_micros: pre_micros / 8,
        }
    }

    fn intent(forward: f32, strafe: f32, jump: bool) -> PlayerIntent {
        PlayerIntent {
            identity: Identity::ZERO,
            forward,
            strafe,
            yaw: 1.25,
            jump,
            input_tick: 1,
            updated_at: Timestamp::UNIX_EPOCH,
        }
    }

    #[test]
    fn voluntary_move_epoch_ignores_yaw_only_intent() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.0, 0.0, false),
            true,
            Some(7),
        );

        assert!(!changed);
        assert_eq!(state.voluntary_move_epoch, 0);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    #[test]
    fn voluntary_move_epoch_increments_for_accepted_locomotion_intent() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.5, 0.0, false),
            false,
            Some(7),
        );

        assert!(changed);
        assert_eq!(state.voluntary_move_epoch, 1);
        assert_eq!(state.last_voluntary_move_input_tick, 7);
    }

    #[test]
    fn voluntary_move_epoch_increments_for_grounded_jump_input() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.0, 0.0, true),
            true,
            Some(7),
        );

        assert!(changed);
        assert_eq!(state.voluntary_move_epoch, 1);
        assert_eq!(state.last_voluntary_move_input_tick, 7);
    }

    #[test]
    fn voluntary_move_epoch_ignores_airborne_jump_input() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.0, 0.0, true),
            false,
            Some(7),
        );

        assert!(!changed);
        assert_eq!(state.voluntary_move_epoch, 0);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    #[test]
    fn voluntary_move_epoch_ignores_blocked_movement_input() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            true,
            &intent(1.0, 0.0, true),
            true,
            Some(7),
        );

        assert!(!changed);
        assert_eq!(state.voluntary_move_epoch, 0);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    #[test]
    fn voluntary_move_epoch_does_not_record_fallback_as_authored_movement() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(1.0, 0.0, false),
            true,
            None,
        );

        assert!(changed);
        assert_eq!(state.voluntary_move_epoch, 1);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    fn test_physics_at(x: f32, y: f32, z: f32, yaw: f32) -> PlayerPhysics {
        PlayerPhysics {
            identity: Identity::ZERO,
            pos_x: x,
            pos_y: y,
            pos_z: z,
            vel_x: 1.0,
            vel_y: 2.0,
            vel_z: 3.0,
            yaw,
            grounded: false,
            last_processed_tick: 7,
            updated_at: Timestamp::from_micros_since_unix_epoch(1),
        }
    }

    #[test]
    fn stationary_playground_target_settle_preserves_pose_and_clears_velocity() {
        let mut physics = test_physics_at(12.5, 4.0, -3.25, 1.2);
        let updated_at = Timestamp::from_micros_since_unix_epoch(3);

        settle_stationary_playground_target(&mut physics, updated_at);

        assert_eq!(physics.pos_x, 12.5);
        assert_eq!(physics.pos_y, 4.0);
        assert_eq!(physics.pos_z, -3.25);
        assert_eq!(physics.yaw, 1.2);
        assert_eq!(physics.vel_x, 0.0);
        assert_eq!(physics.vel_y, 0.0);
        assert_eq!(physics.vel_z, 0.0);
        assert!(physics.grounded);
        assert_eq!(physics.updated_at, updated_at);
    }

    #[test]
    fn special_movement_handoff_preserves_airborne_state_for_fixed_y_runtime() {
        assert!(!special_movement_grounded_state(
            SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y,
            true
        ));
        assert!(!special_movement_grounded_state(
            SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY,
            true
        ));
    }

    #[test]
    fn special_movement_handoff_preserves_grounded_state_for_ground_following_runtime() {
        assert!(special_movement_grounded_state("STOP_AT_BLOCK", true));
        assert!(!special_movement_grounded_state("STOP_AT_BLOCK", false));
    }

    #[test]
    fn percentile_sorted_uses_nearest_rank() {
        let sorted = [1_u32, 2, 3, 4, 5];
        assert_eq!(percentile_sorted(&sorted, 50, 100), 3);
        assert_eq!(percentile_sorted(&sorted, 95, 100), 5);
        assert_eq!(percentile_sorted(&sorted, 99, 100), 5);
    }

    #[test]
    fn tick_profile_window_flushes_after_five_seconds() {
        let mut state = TickProfileWindowState::default();
        assert!(state.record(0, sample(12_000, 6_000)).is_none());

        let summary = state
            .record(5_000_000, sample(18_000, 8_000))
            .expect("expected flush after five seconds");

        assert_eq!(summary.count, 2);
        assert_eq!(summary.total_p50_micros, 12_000);
        assert_eq!(summary.total_p95_micros, 18_000);
        assert_eq!(summary.total_p99_micros, 18_000);
        assert_eq!(summary.total_max_micros, 18_000);
        assert_eq!(summary.pre_tick.p95_micros, 8_000);
        assert_eq!(summary.pre_tick.max_micros, 8_000);
    }

    #[test]
    fn tick_profile_window_tracks_over_budget_streaks() {
        let mut state = TickProfileWindowState::default();
        assert!(state.record(0, sample(34_000, 10_000)).is_none());
        assert!(state.record(1_000_000, sample(35_000, 10_000)).is_none());
        assert!(state.record(2_000_000, sample(10_000, 10_000)).is_none());
        assert!(state.record(3_000_000, sample(34_000, 10_000)).is_none());

        let summary = state
            .record(5_000_000, sample(10_000, 10_000))
            .expect("expected flush after five seconds");

        assert_eq!(summary.over_budget_count, 3);
        assert_eq!(summary.max_consecutive_over_budget, 2);
    }
}
