//! Game Loop - The SOLE Authority on Physics State
//!
//! This module contains:
//! - GameLoopTimer table (for scheduled reducer)
//! - init reducer (starts the game loop)
//! - game_tick reducer (THE physics simulation)
//!
//! CRITICAL OWNERSHIP RULE:
//! `game_tick` is the ONLY reducer that writes to PlayerPhysics.
//! All movement state changes happen HERE and NOWHERE else.
//!
//! The game_tick reducer:
//! 1. Reads PlayerIntent (what player wants)
//! 2. Computes new physics state (what actually happens)
//! 3. Writes PlayerPhysics (authoritative result)
//! 4. Clears consumed intent flags (jump)
//!
//! Jump and landing transitions BOTH happen in this function.
//! You can read this one function to understand the complete state machine.

use spacetimedb::{reducer, table, Identity, ReducerContext, ScheduleAt, Table, Timestamp};
use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};
use std::time::Duration;

// Import movement constants and helper
use crate::action_prediction::prune_predicted_action_results;
use crate::appearance::backfill_character_appearance_rows;
#[allow(unused_imports)]
use crate::arena::arena_instance as _;
#[allow(unused_imports)]
use crate::arena::player_open_world_scene as _;
#[allow(unused_imports)]
use crate::arena::player_world as _;
use crate::arena::{
    arena_seed_for_identity, backfill_player_open_world_scene_rows, backfill_player_world_rows,
    despawn_legacy_default_dummies, open_world_scene_name_for_identity, MATCH_PHASE_COUNTDOWN,
    MATCH_PHASE_IN_PROGRESS,
};
use crate::auto_attack::tick_auto_attacks;
use crate::combat::actor_snapshot::CombatActorSnapshotSet;
use crate::combat::{
    clear_statuses_for_dead_players, expire_combat_engagements, expire_status_effects,
    has_due_pending_effects, normalize_legacy_hot_status_rows, process_periodic_status_ticks,
    prune_combat_events, resolve_pending_effects, respawn_player,
    sync_combat_projectile_definitions, sync_player_state_derived_stats, tick_auras,
    tick_combat_projectiles_with_snapshots, tick_combat_stacking_passives, tick_emanations,
    MovementModifiers, StatusRuntimeView, TemporaryCombatModifiers,
};
use crate::defense::prune_defense_states;
use crate::derived_stats::{
    derived_combat_stats_for_owner, derived_combat_stats_from_allocations, DerivedCombatStats,
};
use crate::inventory::{
    equipment_modifier_totals_for_owner, sync_item_definitions, tick_equipment_periodic_effects,
    EquipmentModifierTotals,
};
use crate::melee::{
    has_due_pending_melee_impacts, has_due_pending_projectile_releases,
    resolve_pending_melee_impacts, resolve_pending_projectile_releases, sync_melee_definitions,
    tick_pending_melee_timed_movements, tick_queued_melee_followups,
};
use crate::movement::{
    velocity_from_intent, FIXED_TICK_MILLIS, FIXED_TICK_SECONDS, GRAVITY, JUMP_VELOCITY,
    MOVE_SPEED, ZERO_INPUT_EPSILON,
};
use crate::movement_actions::{
    reset_dodge_charge_state_to_full, sync_all_fixed_action_charge_states,
    tick_fixed_action_charge_states, tick_movement_actions,
};
use crate::npcs::sync_npc_catalog;
use crate::npcs::{prune_due_npc_corpse_despawns, tick_npc_combat};
use crate::party::expire_party_invites;
use crate::player_input::{
    clear_pending_player_commands, clear_pending_player_commands_through_tick,
    count_buffered_commands, pop_command_for_tick,
};
use crate::player_intent::PlayerIntent;
use crate::player_physics::{commit_player_physics, PhysicsWriteMode, PlayerPhysics};
use crate::playground_targets::is_playground_target;
use crate::practice::{is_training_instance, tick_practice};
use crate::progression::{
    backfill_character_action_bar_rows, backfill_sword_and_shield_visible_action_bar_rows,
    clear_generic_fixed_action_bar_assignments, migrate_generic_spell_action_bar_assignments,
    migrate_renamed_melee_action_bar_assignments, sync_progression_catalogs,
};
use crate::resources::{
    reset_player_resources_to_full, sync_all_player_resources,
    sync_primary_resource_for_player_with, tick_primary_resource_for_player, ResourceSpecInputs,
};
use crate::spells::{
    has_due_pending_area_impacts, resolve_pending_area_impacts, resolve_pending_casts,
    resolve_special_movement_y, sync_spell_definitions, tick_active_casts,
    tick_bespoke_spells_with_snapshots,
};
use crate::tick_metrics::{
    profiling_enabled as tick_profiling_enabled, record_table_write, PhaseStopwatch, ScopeTimer,
    TableWriteKind,
};
use crate::world_collision::{
    preload_world_collision_data, resolve_world_horizontal_sweep_collision_y_with_layout_for_scene,
    surface_height_for_world_at_y_with_layout, surface_height_for_world_at_y_with_layout_for_scene,
};

// Import accessor traits (generated by #[table] macro, needed for ctx.db.table_name())
#[allow(unused_imports)]
use crate::combat::active_combat_projectile as _;
#[allow(unused_imports)]
use crate::combat::status_effect as _;
#[allow(unused_imports)]
use crate::movement_actions::fixed_action_charge_state as _;
#[allow(unused_imports)]
use crate::movement_actions::movement_action_state as _;
#[allow(unused_imports)]
use crate::npcs::npc_state as _;
#[allow(unused_imports)]
use crate::player::player as _;
#[allow(unused_imports)]
use crate::player_input::player_command as _;
#[allow(unused_imports)]
use crate::player_input::player_input_cursor as _;
#[allow(unused_imports)]
use crate::player_intent::player_intent as _;
#[allow(unused_imports)]
use crate::player_physics::player_physics as _;
#[allow(unused_imports)]
use crate::player_state::player_state as _;
#[allow(unused_imports)]
use crate::spells::active_bespoke_spell as _;
#[allow(unused_imports)]
use crate::spells::active_cast as _;
#[allow(unused_imports)]
use crate::spells::special_movement_runtime as _;

const MAX_HORIZONTAL_COLLISION_STEP: f32 = 0.10;
const MAX_GROUNDED_SNAP_DOWN: f32 = 0.75;
const GAME_TICK_INTERVAL: Duration = Duration::from_millis(FIXED_TICK_MILLIS);
/// Fixed-rate chain catch-up bound: a stall deeper than this many ticks
/// re-anchors to now instead of fast-forwarding through the backlog.
const GAME_TICK_MAX_CATCHUP_TICKS: i64 = 3;
/// The watchdog only re-seeds a dead chain; 1 s of lost ticks after a
/// catastrophic (rolled-back/panicked) tick is the accepted worst case.
const GAME_LOOP_WATCHDOG_INTERVAL: Duration = Duration::from_secs(1);
const EVENT_PRUNE_INTERVAL: Duration = Duration::from_millis(500);
const TICK_PROFILE_WINDOW_MICROS: i64 = 5_000_000;
const TICK_BUDGET_MICROS: u32 = FIXED_TICK_MILLIS as u32 * 1_000;
const SPECIAL_MOVEMENT_PATH_INSTANT: &str = "INSTANT";
const SPECIAL_MOVEMENT_FACING_FACE_PATH: &str = "FACE_PATH";
const SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y: &str = "STOP_AT_BLOCK_FIXED_Y";
const SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY: &str =
    "STOP_AT_BLOCK_KEEP_HEIGHT";
const SPECIAL_MOVEMENT_INPUT_DISCARD_LEAD_TICKS: u32 = 4;

/// Pre-tick housekeeping sub-phases timed individually when profiling is
/// enabled. Indexes must match `PRE_TICK_SUBPHASE_NAMES`.
const PRE_TICK_SUBPHASE_COUNT: usize = 16;
const PRE_SUB_PROGRESSION_SYNC: usize = 0;
const PRE_SUB_CHARGE_STATES: usize = 1;
const PRE_SUB_PRACTICE: usize = 2;
const PRE_SUB_MOVEMENT_ACTIONS: usize = 3;
const PRE_SUB_MELEE_TIMED_MOVEMENTS: usize = 4;
const PRE_SUB_SPECIAL_MOVEMENT: usize = 5;
const PRE_SUB_ACTIVE_CASTS: usize = 6;
const PRE_SUB_MELEE_FOLLOWUPS: usize = 7;
const PRE_SUB_AUTO_ATTACKS: usize = 8;
const PRE_SUB_NPC_COMBAT: usize = 9;
const PRE_SUB_COMBAT_CYCLE: usize = 10;
const PRE_SUB_SPELL_PROJECTILE_SIM: usize = 11;
const PRE_SUB_PERIODIC_EFFECTS: usize = 12;
const PRE_SUB_PASSIVES_AURAS: usize = 13;
const PRE_SUB_EXPIRIES: usize = 14;
const PRE_SUB_MOVEMENT_MODIFIERS: usize = 15;

const PRE_TICK_SUBPHASE_NAMES: [&str; PRE_TICK_SUBPHASE_COUNT] = [
    "progression_sync",
    "charge_states",
    "practice",
    "movement_actions",
    "melee_timed_movements",
    "special_movement",
    "active_casts",
    "melee_followups",
    "auto_attacks",
    "npc_combat",
    "combat_cycle",
    "spell_projectile_sim",
    "periodic_effects",
    "passives_auras",
    "expiries",
    "movement_modifiers",
];

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct TickProfileSample {
    total_micros: u32,
    pre_tick_micros: u32,
    player_sim_micros: u32,
    post_tick_micros: u32,
    match_maintenance_micros: u32,
    pre_subphase_micros: [u32; PRE_TICK_SUBPHASE_COUNT],
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct TickPhaseSummary {
    p95_micros: u32,
    max_micros: u32,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct TickProfileSummary {
    count: usize,
    total_p50_micros: u32,
    total_p95_micros: u32,
    total_p99_micros: u32,
    total_max_micros: u32,
    over_budget_count: usize,
    max_consecutive_over_budget: usize,
    pre_tick: TickPhaseSummary,
    player_sim: TickPhaseSummary,
    post_tick: TickPhaseSummary,
    match_maintenance: TickPhaseSummary,
    pre_subphases: [TickPhaseSummary; PRE_TICK_SUBPHASE_COUNT],
}

#[derive(Default)]
struct TickProfileWindowState {
    window_started_at_micros: Option<i64>,
    total_micros: Vec<u32>,
    pre_tick_micros: Vec<u32>,
    player_sim_micros: Vec<u32>,
    post_tick_micros: Vec<u32>,
    match_maintenance_micros: Vec<u32>,
    pre_subphase_micros: [Vec<u32>; PRE_TICK_SUBPHASE_COUNT],
    over_budget_count: usize,
    consecutive_over_budget: usize,
    max_consecutive_over_budget: usize,
}

impl TickProfileWindowState {
    fn record(&mut self, now_micros: i64, sample: TickProfileSample) -> Option<TickProfileSummary> {
        if self.window_started_at_micros.is_none() {
            self.window_started_at_micros = Some(now_micros);
        }

        self.total_micros.push(sample.total_micros);
        self.pre_tick_micros.push(sample.pre_tick_micros);
        self.player_sim_micros.push(sample.player_sim_micros);
        self.post_tick_micros.push(sample.post_tick_micros);
        self.match_maintenance_micros
            .push(sample.match_maintenance_micros);
        for (values, micros) in self
            .pre_subphase_micros
            .iter_mut()
            .zip(sample.pre_subphase_micros.iter())
        {
            values.push(*micros);
        }

        if sample.total_micros > TICK_BUDGET_MICROS {
            self.over_budget_count += 1;
            self.consecutive_over_budget += 1;
            self.max_consecutive_over_budget = self
                .max_consecutive_over_budget
                .max(self.consecutive_over_budget);
        } else {
            self.consecutive_over_budget = 0;
        }

        let window_started_at_micros = self.window_started_at_micros.unwrap_or(now_micros);
        if now_micros.saturating_sub(window_started_at_micros) < TICK_PROFILE_WINDOW_MICROS {
            return None;
        }

        self.flush()
    }

    fn flush(&mut self) -> Option<TickProfileSummary> {
        if self.total_micros.is_empty() {
            self.window_started_at_micros = None;
            self.consecutive_over_budget = 0;
            return None;
        }

        let mut pre_subphases = [TickPhaseSummary::default(); PRE_TICK_SUBPHASE_COUNT];
        for (summary, values) in pre_subphases
            .iter_mut()
            .zip(self.pre_subphase_micros.iter())
        {
            *summary = summarize_phase(values);
        }

        let summary = TickProfileSummary {
            count: self.total_micros.len(),
            total_p50_micros: percentile_value(&self.total_micros, 50, 100),
            total_p95_micros: percentile_value(&self.total_micros, 95, 100),
            total_p99_micros: percentile_value(&self.total_micros, 99, 100),
            total_max_micros: max_value(&self.total_micros),
            over_budget_count: self.over_budget_count,
            max_consecutive_over_budget: self.max_consecutive_over_budget,
            pre_tick: summarize_phase(&self.pre_tick_micros),
            player_sim: summarize_phase(&self.player_sim_micros),
            post_tick: summarize_phase(&self.post_tick_micros),
            match_maintenance: summarize_phase(&self.match_maintenance_micros),
            pre_subphases,
        };

        self.window_started_at_micros = None;
        self.total_micros.clear();
        self.pre_tick_micros.clear();
        self.player_sim_micros.clear();
        self.post_tick_micros.clear();
        self.match_maintenance_micros.clear();
        for values in self.pre_subphase_micros.iter_mut() {
            values.clear();
        }
        self.over_budget_count = 0;
        self.consecutive_over_budget = 0;
        self.max_consecutive_over_budget = 0;

        Some(summary)
    }
}

fn max_value(values: &[u32]) -> u32 {
    values.iter().copied().max().unwrap_or(0)
}

fn summarize_phase(values: &[u32]) -> TickPhaseSummary {
    TickPhaseSummary {
        p95_micros: percentile_value(values, 95, 100),
        max_micros: max_value(values),
    }
}

fn percentile_value(values: &[u32], numerator: usize, denominator: usize) -> u32 {
    if values.is_empty() {
        return 0;
    }

    let mut sorted = values.to_vec();
    sorted.sort_unstable();
    percentile_sorted(&sorted, numerator, denominator)
}

fn percentile_sorted(sorted: &[u32], numerator: usize, denominator: usize) -> u32 {
    if sorted.is_empty() {
        return 0;
    }

    let rank = div_ceil(sorted.len() * numerator, denominator).saturating_sub(1);
    sorted[rank.min(sorted.len().saturating_sub(1))]
}

fn div_ceil(value: usize, divisor: usize) -> usize {
    if divisor == 0 {
        return 0;
    }
    (value + divisor - 1) / divisor
}

fn format_micros(micros: u32) -> String {
    format!("{:.2}ms", micros as f32 / 1_000.0)
}

fn tick_profile_store() -> &'static Mutex<TickProfileWindowState> {
    static TICK_PROFILE_STORE: OnceLock<Mutex<TickProfileWindowState>> = OnceLock::new();
    TICK_PROFILE_STORE.get_or_init(|| Mutex::new(TickProfileWindowState::default()))
}

/// Returns the number of ticks in the flushed window, or `None` while the
/// window is still accumulating. The tick count matters for interpretation:
/// SpacetimeDB may run several pooled wasm instances, each with its own copy
/// of this static window state, so one log line covers only the ticks that
/// executed on that instance — always read the counters as per-tick ratios
/// against `ticks=`, not as absolute per-5s totals.
fn record_tick_profile(now: Timestamp, sample: TickProfileSample) -> Option<usize> {
    let maybe_summary = {
        let mut state = tick_profile_store()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        state.record(now.to_micros_since_unix_epoch(), sample)
    };

    let summary = maybe_summary?;

    if !crate::tick_metrics::WALL_CLOCK_AVAILABLE {
        // Percentile micros are all zero in the wasm module (no Instant);
        // wall-clock comes from the sampled console timers instead.
        return Some(summary.count);
    }

    log::info!(
        "[TICK_PROFILE] window=5.00s ticks={} total(p50/p95/p99/max)={}/{}/{}/{} over_budget={} max_consecutive_over_budget={} pre(p95/max)={}/{} player(p95/max)={}/{} post(p95/max)={}/{} match(p95/max)={}/{}",
        summary.count,
        format_micros(summary.total_p50_micros),
        format_micros(summary.total_p95_micros),
        format_micros(summary.total_p99_micros),
        format_micros(summary.total_max_micros),
        summary.over_budget_count,
        summary.max_consecutive_over_budget,
        format_micros(summary.pre_tick.p95_micros),
        format_micros(summary.pre_tick.max_micros),
        format_micros(summary.player_sim.p95_micros),
        format_micros(summary.player_sim.max_micros),
        format_micros(summary.post_tick.p95_micros),
        format_micros(summary.post_tick.max_micros),
        format_micros(summary.match_maintenance.p95_micros),
        format_micros(summary.match_maintenance.max_micros),
    );

    let mut pre_line = String::with_capacity(512);
    for (name, phase) in PRE_TICK_SUBPHASE_NAMES
        .iter()
        .zip(summary.pre_subphases.iter())
    {
        pre_line.push_str(&format!(
            " {}(p95/max)={}/{}",
            name,
            format_micros(phase.p95_micros),
            format_micros(phase.max_micros)
        ));
    }
    log::info!(
        "[TICK_PROFILE_PRE] window=5.00s ticks={}{}",
        summary.count,
        pre_line
    );

    Some(summary.count)
}

/// Log the per-window scan/write counters plus a one-shot population sample.
/// Called only when profiling is enabled and a profile window just flushed.
/// `window_ticks` is this instance's tick count for the window — divide every
/// counter by it (pooled wasm instances each report their own share).
fn log_tick_scan_profile(ctx: &ReducerContext, window_ticks: usize) {
    let scan = crate::tick_metrics::snapshot_and_reset();

    let mut alive_players = 0usize;
    let mut dummies = 0usize;
    for state in ctx.db.player_state().iter() {
        if state.is_dummy {
            dummies += 1;
        } else if state.alive {
            alive_players += 1;
        }
    }
    let alive_npcs = ctx
        .db
        .npc_state()
        .iter()
        .filter(|state| state.alive)
        .count();
    let active_statuses = ctx.db.status_effect().iter().count();
    let active_casts = ctx.db.active_cast().iter().count();
    let active_projectiles = ctx.db.active_combat_projectile().iter().count();

    let mut writes_line = String::with_capacity(256);
    for (name, count) in crate::tick_metrics::TABLE_WRITE_KIND_NAMES
        .iter()
        .zip(scan.table_writes.iter())
    {
        writes_line.push_str(&format!(" writes_{}={}", name, count));
    }

    log::info!(
        "[TICK_PROFILE_SCAN] ticks={} status_collects={} status_collect_ms={:.2} status_rows_scanned={} equipment_scans={} move_fallbacks={} npc_target_pairs={}{} alive_players={} dummies={} alive_npcs={} active_statuses={} active_casts={} active_projectiles={}",
        window_ticks,
        scan.status_collect_count,
        scan.status_collect_micros as f64 / 1_000.0,
        scan.status_collect_rows,
        scan.equipment_scan_count,
        scan.move_fallback_count,
        scan.npc_target_pairs_scanned,
        writes_line,
        alive_players,
        dummies,
        alive_npcs,
        active_statuses,
        active_casts,
        active_projectiles,
    );
}

fn timed_subphase<T>(
    profiling: bool,
    stopwatch_active: bool,
    name: &'static str,
    slot: &mut u32,
    f: impl FnOnce() -> T,
) -> T {
    if !profiling {
        return f();
    }

    let _stopwatch = PhaseStopwatch::start(stopwatch_active, name);
    let timer = ScopeTimer::start(true);
    let result = f();
    *slot = slot.saturating_add(timer.elapsed_micros());
    result
}

/// Per-tick, per-player memo of equipment totals and derived stats (tick
/// audit T2): within one tick the loadout cannot change (equip reducers run
/// outside `game_tick`), so every consumer reads the same values. Derived
/// stats may go one tick stale after a mid-tick progression change, which the
/// audit accepts. Never reused across ticks.
pub(crate) struct PlayerTickContext {
    equipment: EquipmentModifierTotals,
    derived: DerivedCombatStats,
}

pub(crate) struct PlayerTickContexts {
    by_owner: HashMap<Identity, PlayerTickContext>,
}

impl PlayerTickContexts {
    fn collect(ctx: &ReducerContext) -> Self {
        let mut by_owner = HashMap::new();
        for state in ctx.db.player_state().iter() {
            if state.is_dummy {
                continue;
            }
            let equipment = equipment_modifier_totals_for_owner(ctx, state.player_id);
            by_owner.insert(
                state.player_id,
                PlayerTickContext {
                    equipment,
                    derived: derived_combat_stats_from_allocations(
                        equipment.allocated_stat_totals(),
                    ),
                },
            );
        }
        Self { by_owner }
    }

    pub(crate) fn equipment(
        &self,
        ctx: &ReducerContext,
        owner: Identity,
    ) -> EquipmentModifierTotals {
        self.by_owner
            .get(&owner)
            .map(|context| context.equipment)
            .unwrap_or_else(|| equipment_modifier_totals_for_owner(ctx, owner))
    }

    pub(crate) fn derived(&self, ctx: &ReducerContext, owner: Identity) -> DerivedCombatStats {
        self.by_owner
            .get(&owner)
            .map(|context| context.derived)
            .unwrap_or_else(|| derived_combat_stats_for_owner(ctx, owner))
    }
}

pub(crate) fn ensure_game_loop_schedule(ctx: &ReducerContext) {
    if ctx.db.game_loop_timer().iter().next().is_some() {
        return;
    }

    // Fixed-RATE chain (S5 cadence fix): each game_tick re-inserts a one-shot
    // Time row anchored on its own scheduled time, so execution and
    // scheduling overhead do not leak into the period. The previous
    // ScheduleAt::Interval row was host-managed fixed-DELAY — measured live
    // at 36.6 ms/tick against the authored 33 ms (10% slow), which both
    // dilated the whole simulation against wall clock (dt stays 33 ms) and
    // fed the client input loop a permanent surplus.
    ctx.db.game_loop_timer().insert(GameLoopTimer {
        scheduled_id: 0,
        scheduled_at: ScheduleAt::Time(fresh_game_tick_schedule(ctx.timestamp)),
    });
    log::info!("[GAME_LOOP] Scheduled game_tick fixed-rate chain (33ms tick)");
}

pub(crate) fn ensure_game_loop_watchdog_schedule(ctx: &ReducerContext) {
    if ctx.db.game_loop_watchdog().iter().next().is_some() {
        return;
    }

    ctx.db.game_loop_watchdog().insert(GameLoopWatchdog {
        scheduled_id: 0,
        scheduled_at: ScheduleAt::Interval(GAME_LOOP_WATCHDOG_INTERVAL.into()),
    });
}

/// Re-arms the fixed-rate chain. Called FIRST inside game_tick so the next
/// link exists in the same transaction as the tick's writes.
///
/// Anchor policy: next = this row's scheduled time + one tick — never
/// "now + one tick" — so per-tick overhead cannot accumulate into the
/// period. Brief stalls are caught up (the host fires overdue rows
/// immediately); a stall deeper than the catch-up cap drops the backlog and
/// re-anchors one tick into the future instead of leaving a due-now recovery
/// row that may remain inert after a module publish.
fn fresh_game_tick_schedule(now: Timestamp) -> Timestamp {
    let tick_micros = GAME_TICK_INTERVAL.as_micros() as i64;
    Timestamp::from_micros_since_unix_epoch(
        now.to_micros_since_unix_epoch().saturating_add(tick_micros),
    )
}

fn next_game_tick_schedule(now: Timestamp, fired_at: &ScheduleAt) -> (Timestamp, bool) {
    let now_micros = now.to_micros_since_unix_epoch();
    let tick_micros = GAME_TICK_INTERVAL.as_micros() as i64;
    let anchor_micros = match fired_at {
        ScheduleAt::Time(scheduled) => scheduled.to_micros_since_unix_epoch(),
        // Legacy Interval row (pre-fix DB) has no scheduled-time anchor.
        ScheduleAt::Interval(_) => now_micros,
    };

    let anchored_next_micros = anchor_micros.saturating_add(tick_micros);
    let max_backlog_micros = tick_micros * GAME_TICK_MAX_CATCHUP_TICKS;
    let reanchored = anchored_next_micros < now_micros.saturating_sub(max_backlog_micros);
    let next_micros = if reanchored {
        // A recovery link must be strictly future-dated. Re-inserting a Time
        // row at the current reducer timestamp can leave an inert, overdue row
        // behind after a data-preserving module publish.
        now_micros.saturating_add(tick_micros)
    } else {
        anchored_next_micros
    };

    (
        Timestamp::from_micros_since_unix_epoch(next_micros),
        reanchored,
    )
}

fn game_loop_timer_is_overdue(now: Timestamp, scheduled_at: &ScheduleAt) -> bool {
    let ScheduleAt::Time(scheduled) = scheduled_at else {
        return false;
    };

    let tick_micros = GAME_TICK_INTERVAL.as_micros() as i64;
    let max_backlog_micros = tick_micros * GAME_TICK_MAX_CATCHUP_TICKS;
    scheduled.to_micros_since_unix_epoch()
        < now
            .to_micros_since_unix_epoch()
            .saturating_sub(max_backlog_micros)
}

fn reschedule_game_tick(ctx: &ReducerContext, fired: &GameLoopTimer) {
    // Defensive sweep: clears the fired row regardless of host one-shot
    // delete semantics, and migrates the legacy Interval row on first fire
    // after republish (two live rows would double-tick).
    let stale_ids: Vec<u64> = ctx
        .db
        .game_loop_timer()
        .iter()
        .map(|row| row.scheduled_id)
        .collect();
    for scheduled_id in stale_ids {
        ctx.db.game_loop_timer().scheduled_id().delete(scheduled_id);
    }

    let (next_scheduled_at, reanchored) =
        next_game_tick_schedule(ctx.timestamp, &fired.scheduled_at);
    if reanchored {
        log::warn!(
            "[GAME_LOOP] tick chain fell behind; re-anchoring one tick in the future (backlog dropped)"
        );
    }

    ctx.db.game_loop_timer().insert(GameLoopTimer {
        scheduled_id: 0,
        scheduled_at: ScheduleAt::Time(next_scheduled_at),
    });
}

fn bootstrap_server_state(ctx: &ReducerContext) {
    let collision_summary = preload_world_collision_data();
    log::info!(
        "[INIT] Preloaded world collision data scenes={} arena_gameplay_boxes={} arena_query_boxes={} arena_query_mesh_geometries={} arena_query_mesh_instances={} arena_query_mesh_triangles={} open_world_gameplay_boxes={} open_world_query_boxes={} open_world_query_mesh_geometries={} open_world_query_mesh_instances={} open_world_query_mesh_triangles={} query_mesh_bvh_nodes={} broadphase_cells={} broadphase_index_entries={} broadphase_max_cell_occupancy={} broadphase_max_cells_per_collider={} broadphase_unindexed_colliders={} generated_open_world_colliders={}",
        collision_summary.scene_count,
        collision_summary.arena_gameplay_boxes,
        collision_summary.arena_query_boxes,
        collision_summary.arena_query_mesh_geometries,
        collision_summary.arena_query_mesh_instances,
        collision_summary.arena_query_mesh_triangles,
        collision_summary.open_world_gameplay_boxes,
        collision_summary.open_world_query_boxes,
        collision_summary.open_world_query_mesh_geometries,
        collision_summary.open_world_query_mesh_instances,
        collision_summary.open_world_query_mesh_triangles,
        collision_summary.query_mesh_bvh_nodes,
        collision_summary.broadphase_cells,
        collision_summary.broadphase_index_entries,
        collision_summary.broadphase_max_cell_occupancy,
        collision_summary.broadphase_max_cells_per_collider,
        collision_summary.broadphase_unindexed_colliders,
        collision_summary.generated_open_world_colliders
    );
    if collision_summary.broadphase_unindexed_colliders > 0 {
        log::warn!(
            "[INIT] World collision broadphase left {} gameplay collider(s) unindexed; affected queries will fall back to full scan to avoid false negatives.",
            collision_summary.broadphase_unindexed_colliders
        );
    }

    sync_progression_catalogs(ctx);
    sync_npc_catalog(ctx);
    sync_item_definitions(ctx);
    sync_combat_projectile_definitions(ctx);
    sync_spell_definitions(ctx);
    sync_melee_definitions(ctx);
    sync_all_player_resources(ctx, ctx.timestamp);
    sync_all_fixed_action_charge_states(ctx, ctx.timestamp);
    let removed_generic_fixed_action_bar_rows = clear_generic_fixed_action_bar_assignments(ctx);
    if removed_generic_fixed_action_bar_rows > 0 {
        log::warn!(
            "[INIT] Removed {} legacy generic fixed action-bar assignment row(s)",
            removed_generic_fixed_action_bar_rows
        );
    }
    let migrated_melee_action_bar_rows = migrate_renamed_melee_action_bar_assignments(ctx);
    if migrated_melee_action_bar_rows > 0 {
        log::warn!(
            "[INIT] Migrated {} renamed melee action-bar assignment row(s)",
            migrated_melee_action_bar_rows
        );
    }
    let migrated_generic_spell_action_bar_rows = migrate_generic_spell_action_bar_assignments(ctx);
    if migrated_generic_spell_action_bar_rows > 0 {
        log::warn!(
            "[INIT] Migrated {} generic spell action-bar assignment row(s)",
            migrated_generic_spell_action_bar_rows
        );
    }
    let repaired_action_bar_rows = backfill_character_action_bar_rows(ctx);
    if repaired_action_bar_rows > 0 {
        log::warn!(
            "[INIT] Backfilled default action bars for {} character(s)",
            repaired_action_bar_rows
        );
    }
    let repaired_sword_and_shield_visible_rows =
        backfill_sword_and_shield_visible_action_bar_rows(ctx);
    if repaired_sword_and_shield_visible_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} SwordAndShield visible action-bar assignment row(s)",
            repaired_sword_and_shield_visible_rows
        );
    }
    let repaired_appearance_rows = backfill_character_appearance_rows(ctx);
    if repaired_appearance_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} missing character appearance rows",
            repaired_appearance_rows
        );
    }
    let repaired_hot_rows = normalize_legacy_hot_status_rows(ctx);
    if repaired_hot_rows > 0 {
        log::warn!(
            "[INIT] Normalized {} legacy HOT status rows with negative tick_amount",
            repaired_hot_rows
        );
    }
    let bootstrap_contexts = PlayerTickContexts::collect(ctx);
    let bootstrap_status_modifiers = crate::combat::temporary_combat_modifiers(ctx, ctx.timestamp);
    sync_progression_runtime_rows(
        ctx,
        ctx.timestamp,
        &bootstrap_status_modifiers,
        &bootstrap_contexts,
    );
}

/// Schedule table for the game loop.
/// Inserting a row schedules game_tick to run. Rows are one-shot Time links
/// in a fixed-rate chain (see reschedule_game_tick); the watchdog re-seeds
/// the chain if it ever dies.
#[table(accessor = game_loop_timer, scheduled(game_tick))]
pub struct GameLoopTimer {
    #[primary_key]
    #[auto_inc]
    pub scheduled_id: u64,
    pub scheduled_at: ScheduleAt,
}

/// Immortal (host-managed Interval) backstop for the fixed-rate chain: a
/// panicked or rolled-back game_tick can remove the next link, while a module
/// publish can leave an overdue row present but inert. This runs at 1 Hz,
/// reads one tiny table, and replaces either failure state.
#[table(accessor = game_loop_watchdog, scheduled(game_loop_watchdog_tick))]
pub struct GameLoopWatchdog {
    #[primary_key]
    #[auto_inc]
    pub scheduled_id: u64,
    pub scheduled_at: ScheduleAt,
}

#[reducer]
pub fn game_loop_watchdog_tick(
    ctx: &ReducerContext,
    _timer: GameLoopWatchdog,
) -> Result<(), String> {
    let overdue_ids: Vec<u64> = ctx
        .db
        .game_loop_timer()
        .iter()
        .filter(|row| game_loop_timer_is_overdue(ctx.timestamp, &row.scheduled_at))
        .map(|row| row.scheduled_id)
        .collect();
    for scheduled_id in &overdue_ids {
        ctx.db
            .game_loop_timer()
            .scheduled_id()
            .delete(*scheduled_id);
    }

    if ctx.db.game_loop_timer().iter().next().is_none() {
        log::warn!(
            "[GAME_LOOP] watchdog re-seeding a dead game_tick chain overdue_rows={}",
            overdue_ids.len()
        );
        ctx.db.game_loop_timer().insert(GameLoopTimer {
            scheduled_id: 0,
            scheduled_at: ScheduleAt::Time(fresh_game_tick_schedule(ctx.timestamp)),
        });
    }
    Ok(())
}

/// Module initialization - starts the game loop.
#[reducer(init)]
pub fn init(ctx: &ReducerContext) -> Result<(), String> {
    ensure_game_loop_schedule(ctx);
    ensure_game_loop_watchdog_schedule(ctx);
    crate::contract_version::sync_contract_versions(ctx);
    bootstrap_server_state(ctx);
    despawn_legacy_default_dummies(ctx);

    let repaired_rows = backfill_player_world_rows(ctx);
    if repaired_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} missing player_world rows as open-world",
            repaired_rows
        );
    }
    let repaired_scene_rows = backfill_player_open_world_scene_rows(ctx);
    if repaired_scene_rows > 0 {
        log::warn!(
            "[INIT] Backfilled {} missing player_open_world_scene rows with default open-world scene",
            repaired_scene_rows
        );
    }

    log::info!("[INIT] Game loop started at 30.3Hz (33ms tick)");
    if tick_profiling_enabled() {
        if crate::tick_metrics::WALL_CLOCK_AVAILABLE {
            log::info!(
                "[INIT] Tick profiling enabled via {}. Logging 5.00s rolling stats; target p95 < 20ms, p99 < 28ms, no sustained ticks over {}ms.",
                crate::tick_metrics::TICK_PROFILE_ENV_VAR,
                FIXED_TICK_MILLIS
            );
        } else {
            log::info!(
                "[INIT] Tick profiling enabled via compile-time {} (wasm module). Logging 5.00s [TICK_PROFILE_SCAN] counter windows; wall-clock comes from tick_profile/* console timers sampled once per window.",
                crate::tick_metrics::TICK_PROFILE_ENV_VAR
            );
        }
    }
    Ok(())
}

fn resolve_combat_cycle(ctx: &ReducerContext, now: Timestamp) {
    resolve_pending_melee_impacts(ctx, now);
    resolve_pending_projectile_releases(ctx, now);
    resolve_pending_area_impacts(ctx, now);
    resolve_pending_effects(ctx, now);
    clear_statuses_for_dead_players(ctx);
    expire_status_effects(ctx, now);
    prune_defense_states(ctx, now);
}

fn resolve_combat_cycle_if_needed(ctx: &ReducerContext, now: Timestamp) {
    if has_due_pending_melee_impacts(ctx, now)
        || has_due_pending_projectile_releases(ctx, now)
        || has_due_pending_area_impacts(ctx, now)
        || has_due_pending_effects(ctx, now)
    {
        resolve_combat_cycle(ctx, now);
    }
}

fn should_prune_events(now: Timestamp) -> bool {
    let now_micros = now.to_micros_since_unix_epoch();
    let tick_micros = GAME_TICK_INTERVAL.as_micros() as i64;
    let prune_micros = EVENT_PRUNE_INTERVAL.as_micros() as i64;
    let previous_tick_micros = now_micros.saturating_sub(tick_micros);
    now_micros.div_euclid(prune_micros) != previous_tick_micros.div_euclid(prune_micros)
}

fn run_pre_tick_housekeeping_phase(
    ctx: &ReducerContext,
    now: Timestamp,
    dt: f32,
    profiling: bool,
    stopwatch_active: bool,
    subphase_micros: &mut [u32; PRE_TICK_SUBPHASE_COUNT],
    contexts: &PlayerTickContexts,
) -> Result<(MovementModifiers, TemporaryCombatModifiers), String> {
    // View A (tick audit T1): one start-of-tick status view shared by the
    // pre-tick consumers that run before the status-mutating phases (Pass A
    // and later), replacing their per-call collects.
    let view_a = StatusRuntimeView::collect(ctx, now);
    let status_modifiers_a = view_a.temporary_combat_modifiers();
    let npc_movement_modifiers = view_a.movement_modifiers();

    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_PROGRESSION_SYNC],
        &mut subphase_micros[PRE_SUB_PROGRESSION_SYNC],
        || sync_progression_runtime_rows(ctx, now, &status_modifiers_a, contexts),
    );
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_CHARGE_STATES],
        &mut subphase_micros[PRE_SUB_CHARGE_STATES],
        || tick_fixed_action_charge_states(ctx, now),
    );
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_PRACTICE],
        &mut subphase_micros[PRE_SUB_PRACTICE],
        || tick_practice(ctx, now),
    )?;
    // Cancel invalid movement actions before authored displacement is sampled.
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_MOVEMENT_ACTIONS],
        &mut subphase_micros[PRE_SUB_MOVEMENT_ACTIONS],
        || tick_movement_actions(ctx, now),
    );
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_MELEE_TIMED_MOVEMENTS],
        &mut subphase_micros[PRE_SUB_MELEE_TIMED_MOVEMENTS],
        || tick_pending_melee_timed_movements(ctx, now),
    );
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_SPECIAL_MOVEMENT],
        &mut subphase_micros[PRE_SUB_SPECIAL_MOVEMENT],
        || tick_special_movement_runtimes(ctx, now),
    );

    // Resolve active cast completion/cancellation before combat resolution.
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_ACTIVE_CASTS],
        &mut subphase_micros[PRE_SUB_ACTIVE_CASTS],
        || tick_active_casts(ctx, now),
    )?;
    // Movement delivery uses active_cast as a completion/impact latch, so clean
    // the replicated movement-action mirror after completion/cancel.
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_MOVEMENT_ACTIONS],
        &mut subphase_micros[PRE_SUB_MOVEMENT_ACTIONS],
        || tick_movement_actions(ctx, now),
    );

    // Buffered melee follow-ups release here once their authored combo
    // transition timing has elapsed.
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_MELEE_FOLLOWUPS],
        &mut subphase_micros[PRE_SUB_MELEE_FOLLOWUPS],
        || tick_queued_melee_followups(ctx, now),
    );
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_AUTO_ATTACKS],
        &mut subphase_micros[PRE_SUB_AUTO_ATTACKS],
        || tick_auto_attacks(ctx, now),
    );
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_NPC_COMBAT],
        &mut subphase_micros[PRE_SUB_NPC_COMBAT],
        || tick_npc_combat(ctx, now, &npc_movement_modifiers),
    );

    // Pass A: resolve effects already queued (casts/reducers from previous frame boundary).
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_COMBAT_CYCLE],
        &mut subphase_micros[PRE_SUB_COMBAT_CYCLE],
        || resolve_combat_cycle_if_needed(ctx, now),
    );

    // Spell/projectile simulation can enqueue effects based on current
    // authoritative state. These phases run before their queued effects are
    // resolved, so they can share one phase-local player snapshot set.
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_SPELL_PROJECTILE_SIM],
        &mut subphase_micros[PRE_SUB_SPELL_PROJECTILE_SIM],
        || -> Result<(), String> {
            let has_active_bespoke_spells = ctx.db.active_bespoke_spell().iter().next().is_some();
            let has_active_combat_projectiles =
                ctx.db.active_combat_projectile().iter().next().is_some();
            if has_active_bespoke_spells || has_active_combat_projectiles {
                let actor_snapshots = CombatActorSnapshotSet::collect(ctx);
                tick_bespoke_spells_with_snapshots(ctx, dt, &actor_snapshots)?;
                tick_combat_projectiles_with_snapshots(ctx, dt, &actor_snapshots)?;
            }
            Ok(())
        },
    )?;

    // Periodic DOT/HOT effects can enqueue additional rows in the same frame.
    let (periodic_queued, equipment_periodic_queued) = timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_PERIODIC_EFFECTS],
        &mut subphase_micros[PRE_SUB_PERIODIC_EFFECTS],
        || {
            (
                process_periodic_status_ticks(ctx, now),
                tick_equipment_periodic_effects(ctx, now, dt, contexts),
            )
        },
    );
    if periodic_queued > 0
        || equipment_periodic_queued > 0
        || has_due_pending_melee_impacts(ctx, now)
        || has_due_pending_projectile_releases(ctx, now)
        || has_due_pending_area_impacts(ctx, now)
        || has_due_pending_effects(ctx, now)
    {
        // Single post-simulation pass resolves both spell-sim and periodic queues.
        timed_subphase(
            profiling,
            stopwatch_active,
            PRE_TICK_SUBPHASE_NAMES[PRE_SUB_COMBAT_CYCLE],
            &mut subphase_micros[PRE_SUB_COMBAT_CYCLE],
            || resolve_combat_cycle(ctx, now),
        );
    }
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_PASSIVES_AURAS],
        &mut subphase_micros[PRE_SUB_PASSIVES_AURAS],
        || {
            tick_combat_stacking_passives(ctx, now);
            tick_auras(ctx, now);
            tick_emanations(ctx, now);
        },
    );
    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_EXPIRIES],
        &mut subphase_micros[PRE_SUB_EXPIRIES],
        || {
            expire_combat_engagements(ctx, now);
            expire_status_effects(ctx, now);
        },
    );

    timed_subphase(
        profiling,
        stopwatch_active,
        PRE_TICK_SUBPHASE_NAMES[PRE_SUB_MOVEMENT_MODIFIERS],
        &mut subphase_micros[PRE_SUB_MOVEMENT_MODIFIERS],
        || {
            // View B (tick audit T1): post-status-resolution view shared by
            // the whole player-simulation phase (movement + resource regen
            // modifiers). No statuses mutate during player sim.
            let view_b = StatusRuntimeView::collect(ctx, now);
            Ok((
                view_b.movement_modifiers(),
                view_b.temporary_combat_modifiers(),
            ))
        },
    )
}

fn sync_progression_runtime_rows(
    ctx: &ReducerContext,
    now: Timestamp,
    status_modifiers: &TemporaryCombatModifiers,
    contexts: &PlayerTickContexts,
) {
    let owners: Vec<_> = ctx
        .db
        .player_state()
        .iter()
        .filter(|row| !row.is_dummy)
        .map(|row| row.player_id)
        .collect();
    for owner in owners {
        sync_player_state_derived_stats(ctx, owner, contexts.derived(ctx, owner));
        let equipment = contexts.equipment(ctx, owner);
        let inputs = ResourceSpecInputs {
            status_modifiers,
            equipment: &equipment,
        };
        sync_primary_resource_for_player_with(ctx, owner, now, &inputs);
    }
}

fn run_player_simulation_phase(
    ctx: &ReducerContext,
    now: Timestamp,
    dt: f32,
    movement_modifiers: &MovementModifiers,
    temporary_modifiers: &TemporaryCombatModifiers,
    contexts: &PlayerTickContexts,
) {
    let player_ids: Vec<_> = ctx.db.player_physics().iter().map(|p| p.identity).collect();
    for identity in player_ids {
        tick_player(
            ctx,
            identity,
            now,
            dt,
            movement_modifiers,
            temporary_modifiers,
            contexts,
        );
    }
}

fn run_post_tick_maintenance_phase(ctx: &ReducerContext, now: Timestamp) {
    prune_due_npc_corpse_despawns(ctx, now);
    if should_prune_events(now) {
        prune_combat_events(ctx, now);
        prune_predicted_action_results(ctx, now);
    }
}

fn run_match_world_maintenance_phase(ctx: &ReducerContext, now: Timestamp) {
    tick_countdowns(ctx, now);
    expire_party_invites(ctx, now);
}

fn try_tick_dead_player(
    ctx: &ReducerContext,
    now: Timestamp,
    physics: &mut PlayerPhysics,
    state: &mut crate::player_state::PlayerState,
) -> bool {
    if state.alive {
        return false;
    }

    if state.eliminated {
        return true;
    }

    if now >= state.respawn_at {
        let (spawn_x, spawn_y, spawn_z, spawn_yaw) = respawn_player(ctx, state);
        physics.pos_x = spawn_x;
        physics.pos_y = spawn_y;
        physics.pos_z = spawn_z;
        physics.vel_x = 0.0;
        physics.vel_y = 0.0;
        physics.vel_z = 0.0;
        physics.yaw = spawn_yaw;
        physics.grounded = true;
        // Respawn clears the queued command stream below; report a clean
        // consume state so the client's lead loop doesn't read the wipe as
        // starvation.
        physics.last_tick_consumed_command = true;
        physics.buffered_command_count = 0;
        physics.updated_at = now;
        if let Some(mut intent) = ctx.db.player_intent().identity().find(state.player_id) {
            intent.forward = 0.0;
            intent.strafe = 0.0;
            intent.yaw = spawn_yaw;
            intent.jump = false;
            intent.input_tick = physics.last_processed_tick;
            intent.updated_at = now;
            record_table_write(TableWriteKind::PlayerIntent);
            ctx.db.player_intent().identity().update(intent);
        }
        reset_player_resources_to_full(ctx, state.player_id, now);
        reset_dodge_charge_state_to_full(ctx, state.player_id, now);
        clear_pending_player_commands(ctx, state.player_id);
    }

    true
}

/// Returns `None` when the actor is not a dummy; otherwise `Some(changed)`
/// where `changed` says whether the physics row needs a commit. Stationary
/// dummies previously rewrote (and replicated) their `PlayerPhysics` row every
/// tick just to restamp `updated_at` (tick audit T3). Dummies carry no
/// prediction-ack semantics (`last_processed_tick` never advances), so
/// skipping the no-op commit is safe; live-player commits are never gated.
fn try_tick_dummy_player(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    physics: &mut PlayerPhysics,
    state: &crate::player_state::PlayerState,
) -> Option<bool> {
    if !state.is_dummy {
        return None;
    }

    if ctx
        .db
        .special_movement_runtime()
        .owner()
        .find(identity)
        .is_some()
    {
        return Some(false);
    }

    let flat_ground_only = uses_flat_training_collision(ctx, identity);
    let ground_y = surface_height_for_world_at_y_with_layout(
        arena_seed_for_identity(ctx, identity),
        flat_ground_only,
        physics.pos_x,
        physics.pos_z,
        physics.pos_y,
    );
    Some(settle_stationary_dummy(physics, ground_y, now))
}

/// Returns `None` when the actor is not a playground target; otherwise
/// `Some(changed)` (see `try_tick_dummy_player` for the write-gating rationale).
fn try_tick_playground_target(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    physics: &mut PlayerPhysics,
) -> Option<bool> {
    if !is_playground_target(ctx, identity) {
        return None;
    }

    ctx.db.special_movement_runtime().owner().delete(identity);
    Some(settle_stationary_playground_target(physics, now))
}

fn stationary_pose_is_settled(physics: &PlayerPhysics) -> bool {
    physics.vel_x == 0.0 && physics.vel_y == 0.0 && physics.vel_z == 0.0 && physics.grounded
}

fn settle_stationary_playground_target(physics: &mut PlayerPhysics, now: Timestamp) -> bool {
    if stationary_pose_is_settled(physics) {
        // Already settled: skip the write — never restamp `updated_at` as the
        // only change on a per-tick row.
        return false;
    }

    physics.vel_x = 0.0;
    physics.vel_y = 0.0;
    physics.vel_z = 0.0;
    physics.grounded = true;
    physics.updated_at = now;
    true
}

fn settle_stationary_dummy(physics: &mut PlayerPhysics, ground_y: f32, now: Timestamp) -> bool {
    if physics.pos_y == ground_y && stationary_pose_is_settled(physics) {
        return false;
    }

    physics.pos_y = ground_y;
    physics.vel_x = 0.0;
    physics.vel_y = 0.0;
    physics.vel_z = 0.0;
    physics.grounded = true;
    physics.updated_at = now;
    true
}

#[allow(clippy::too_many_arguments)]
fn simulate_non_dummy_player_kinematics(
    identity: Identity,
    physics: &mut PlayerPhysics,
    intent: &PlayerIntent,
    arena_seed: Option<u64>,
    flat_ground_only: bool,
    open_world_scene_name: String,
    now: Timestamp,
    dt: f32,
    movement_blocked: bool,
    move_speed_multiplier: f32,
    hit_radius: f32,
    hit_height: f32,
) {
    let ground_at = |x: f32, z: f32, probe_y: f32| -> f32 {
        surface_height_for_world_at_y_with_layout_for_scene(
            arena_seed,
            flat_ground_only,
            Some(open_world_scene_name.as_str()),
            x,
            z,
            probe_y,
        )
    };

    if physics.grounded {
        // Pre-step stabilization: terrain can shift under the player between ticks.
        // We still resnap after integration for final authoritative placement.
        physics.pos_y = ground_at(physics.pos_x, physics.pos_z, physics.pos_y);
    }

    // === Step 1: Always update yaw from intent ===
    // Player can rotate regardless of grounded state
    physics.yaw = intent.yaw;

    // === Step 2: Branch on grounded state ===
    if physics.grounded {
        // --- GROUNDED BRANCH ---
        if !movement_blocked {
            // Compute velocity from intent
            let (vel_x, vel_z) = velocity_from_intent(
                intent.forward,
                intent.strafe,
                intent.yaw,
                MOVE_SPEED * move_speed_multiplier,
            );
            physics.vel_x = vel_x;
            physics.vel_z = vel_z;
        }
        physics.vel_y = 0.0; // No vertical velocity when grounded

        // Check for jump request
        if intent.jump && !movement_blocked {
            // === JUMP TRANSITION ===
            // This is the ONLY place grounded becomes false
            log::debug!(
                "[JUMP] Player {} | pos_y={:.2} | vel=({:.2},{:.2},{:.2}) | grounded: true -> false",
                &identity.to_hex()[..8],
                physics.pos_y,
                physics.vel_x,
                physics.vel_y,
                physics.vel_z
            );

            physics.grounded = false;
            physics.vel_y = JUMP_VELOCITY;

            // Horizontal velocity is already set from intent above.
            // It will be LOCKED (not overwritten) while airborne.
            // No separate preserved_vel field needed.
        }
    } else {
        // --- AIRBORNE BRANCH ---

        // Horizontal velocity is LOCKED - do not modify vel_x or vel_z
        // This is the "preservation" - we simply don't touch them.

        // Apply gravity to vertical velocity
        physics.vel_y += GRAVITY * dt;
    }

    if movement_blocked {
        // Root is an immediate horizontal stop, including while airborne.
        physics.vel_x = 0.0;
        physics.vel_z = 0.0;
    }

    // === Step 3: Integrate position ===
    // This happens regardless of grounded state.
    // CRITICAL: This happens in the SAME tick as jump transition.
    let delta_x = physics.vel_x * dt;
    let delta_z = physics.vel_z * dt;
    let max_delta = delta_x.abs().max(delta_z.abs());
    let step_count = ((max_delta / MAX_HORIZONTAL_COLLISION_STEP).ceil() as usize).max(1);
    let step_x = delta_x / step_count as f32;
    let step_z = delta_z / step_count as f32;
    let mut next_x = physics.pos_x;
    let mut next_z = physics.pos_z;

    for _ in 0..step_count {
        let target_x = next_x + step_x;
        let target_z = next_z + step_z;
        let (resolved_x, resolved_z) =
            resolve_world_horizontal_sweep_collision_y_with_layout_for_scene(
                arena_seed,
                flat_ground_only,
                Some(open_world_scene_name.as_str()),
                next_x,
                next_z,
                target_x,
                target_z,
                hit_radius.max(0.1),
                hit_height.max(0.5),
                physics.pos_y,
            );
        next_x = resolved_x;
        next_z = resolved_z;
    }

    physics.pos_x = next_x;
    physics.pos_z = next_z;

    if physics.grounded {
        let ground_y = ground_at(physics.pos_x, physics.pos_z, physics.pos_y);
        let drop_to_ground = physics.pos_y - ground_y;
        if drop_to_ground <= MAX_GROUNDED_SNAP_DOWN {
            // Small step-down or incline change: keep grounded and snap.
            physics.pos_y = ground_y;
        } else {
            // Walking off a ledge: transition to airborne instead of teleporting down.
            // We intentionally defer landing checks until the next fully-airborne frame.
            physics.grounded = false;
            physics.vel_y = GRAVITY * dt;
            physics.pos_y += physics.vel_y * dt;
        }
    } else {
        // Capture the pre-integration height so landing probes can detect crossing this frame.
        let previous_y = physics.pos_y;
        physics.pos_y += physics.vel_y * dt;
        let ground_y = ground_at(physics.pos_x, physics.pos_z, previous_y);

        // === Step 4: Check landing (ONLY if airborne) ===
        // Landing condition: crossed below sampled walkable surface AND descending.
        // We probe with previous_y so high-speed falls cannot skip narrow tops.
        // Both conditions required - prevents landing while ascending.
        // This check happens AFTER integration - player has moved.
        if physics.pos_y <= ground_y && physics.vel_y <= 0.0 {
            // === LANDING TRANSITION ===
            // This is the ONLY place grounded becomes true (after initial spawn)
            log::debug!(
                "[LAND] Player {} | pos_y={:.2} | vel_y={:.2} | grounded: false -> true",
                &identity.to_hex()[..8],
                physics.pos_y,
                physics.vel_y
            );

            physics.pos_y = ground_y; // Snap to sampled ground
            physics.vel_y = 0.0; // Stop falling
            physics.grounded = true;

            // Note: vel_x and vel_z retain their values from airtime.
            // Next tick (grounded), they'll be recomputed from intent.
            // This prevents stale velocity issues.
        }
    }

    physics.updated_at = now;
}

fn uses_flat_training_collision(ctx: &ReducerContext, identity: Identity) -> bool {
    let Some(world) = ctx.db.player_world().identity().find(identity) else {
        return false;
    };

    let Some(instance_id) = world.instance_id else {
        return false;
    };

    is_training_instance(ctx, instance_id)
}

fn sync_player_movement_context(
    state: &mut crate::player_state::PlayerState,
    movement_blocked: bool,
    move_speed_multiplier: f32,
    movement_context_tick: u32,
) -> bool {
    let clamped_multiplier = move_speed_multiplier.clamp(0.0, 4.0);
    let multiplier_changed = (state.move_speed_multiplier - clamped_multiplier).abs() > 0.0001;
    let changed = state.movement_blocked != movement_blocked
        || multiplier_changed
        || state.movement_context_tick != movement_context_tick;

    if !changed {
        return false;
    }

    state.movement_blocked = movement_blocked;
    state.move_speed_multiplier = clamped_multiplier;
    state.movement_context_tick = movement_context_tick;
    true
}

fn sync_player_voluntary_move_epoch(
    state: &mut crate::player_state::PlayerState,
    movement_blocked: bool,
    intent: &PlayerIntent,
    grounded_before_step: bool,
    command_input_tick: Option<u32>,
) -> bool {
    if movement_blocked {
        return false;
    }

    // Axis input is voluntary even if some other force also moves the player.
    // Jump only counts when the server could accept it from a grounded step.
    let accepted_move = intent.forward.abs() > ZERO_INPUT_EPSILON
        || intent.strafe.abs() > ZERO_INPUT_EPSILON
        || (intent.jump && grounded_before_step);
    if !accepted_move {
        return false;
    }

    state.voluntary_move_epoch = state.voluntary_move_epoch.saturating_add(1);
    if let Some(command_input_tick) = command_input_tick {
        state.last_voluntary_move_input_tick = command_input_tick;
    }
    true
}

fn tick_special_movement_runtimes(ctx: &ReducerContext, now: Timestamp) {
    let runtimes: Vec<crate::spells::SpecialMovementRuntime> =
        ctx.db.special_movement_runtime().iter().collect();
    for runtime in runtimes {
        if is_playground_target(ctx, runtime.owner) {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        }

        let Some(mut physics) = ctx.db.player_physics().identity().find(runtime.owner) else {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        };
        let Some(state) = ctx.db.player_state().player_id().find(runtime.owner) else {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        };
        if !state.alive {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            continue;
        }

        let (desired_x, desired_y, desired_z, desired_yaw, finished) =
            sample_special_movement_pose(&runtime, now);
        let arena_seed = arena_seed_for_identity(ctx, runtime.owner);
        let flat_ground_only = uses_flat_training_collision(ctx, runtime.owner);
        let ground_y = surface_height_for_world_at_y_with_layout(
            arena_seed,
            flat_ground_only,
            desired_x,
            desired_z,
            desired_y,
        );
        let resolved_y = resolve_special_movement_y(
            &runtime.collision_policy,
            runtime.start_y,
            desired_y,
            ground_y,
        );

        let prev_x = physics.pos_x;
        let prev_y = physics.pos_y;
        let prev_z = physics.pos_z;
        physics.pos_x = desired_x;
        physics.pos_y = resolved_y;
        physics.pos_z = desired_z;
        physics.yaw = desired_yaw;
        if finished {
            // Prevent residual authored-movement velocity from carrying into
            // normal physics (airborne lock would otherwise slide the player
            // past the destination). Grounded state is handed back to normal
            // physics instead of being reclassified from terrain here.
            physics.vel_x = 0.0;
            physics.vel_y = 0.0;
            physics.vel_z = 0.0;
        } else {
            physics.vel_x = (desired_x - prev_x) / FIXED_TICK_SECONDS;
            physics.vel_y = (resolved_y - prev_y) / FIXED_TICK_SECONDS;
            physics.vel_z = (desired_z - prev_z) / FIXED_TICK_SECONDS;
        }
        physics.grounded =
            special_movement_grounded_state(&runtime.collision_policy, physics.grounded);
        physics.updated_at = now;
        let handoff_input_tick = physics.last_processed_tick;
        let handoff_yaw = physics.yaw;
        commit_player_physics(
            ctx,
            physics,
            PhysicsWriteMode::SpecialMovementTick,
            "tick_special_movement_runtimes",
        );

        if finished {
            ctx.db
                .special_movement_runtime()
                .owner()
                .delete(runtime.owner);
            reset_player_intent_after_special_movement(
                ctx,
                runtime.owner,
                handoff_input_tick,
                handoff_yaw,
                now,
            );
            // Drop queued commands and advance the receive cursor through the
            // normal client lead window. Commands authored during the special
            // movement can arrive after this reducer tick; rejecting that
            // in-flight window prevents a delayed jump edge from launching on
            // the first post-special-movement physics ticks.
            clear_pending_player_commands_through_tick(
                ctx,
                runtime.owner,
                handoff_input_tick.saturating_add(SPECIAL_MOVEMENT_INPUT_DISCARD_LEAD_TICKS),
            );
        }
    }
}

fn reset_player_intent_after_special_movement(
    ctx: &ReducerContext,
    identity: Identity,
    input_tick: u32,
    yaw: f32,
    now: Timestamp,
) {
    let Some(mut intent) = ctx.db.player_intent().identity().find(identity) else {
        return;
    };

    intent.forward = 0.0;
    intent.strafe = 0.0;
    intent.yaw = yaw;
    intent.jump = false;
    intent.input_tick = input_tick;
    intent.updated_at = now;
    record_table_write(TableWriteKind::PlayerIntent);
    ctx.db.player_intent().identity().update(intent);
}

fn special_movement_grounded_state(collision_policy: &str, current_grounded: bool) -> bool {
    if uses_fixed_y_collision_policy(collision_policy) {
        false
    } else {
        current_grounded
    }
}

fn sample_special_movement_pose(
    runtime: &crate::spells::SpecialMovementRuntime,
    now: Timestamp,
) -> (f32, f32, f32, f32, bool) {
    let start = runtime.started_at.to_micros_since_unix_epoch();
    let duration_micros = (runtime.duration_ms as i64).saturating_mul(1000);
    let end = start.saturating_add(duration_micros);
    let now_micros = now.to_micros_since_unix_epoch();
    let finished = runtime.duration_ms == 0 || now_micros >= end;

    if runtime.path_mode == SPECIAL_MOVEMENT_PATH_INSTANT || runtime.duration_ms == 0 {
        return (
            runtime.end_x,
            runtime.end_y,
            runtime.end_z,
            runtime.facing_yaw_start,
            true,
        );
    }

    let progress = if duration_micros <= 0 {
        1.0
    } else {
        ((now_micros - start) as f64 / duration_micros as f64).clamp(0.0, 1.0) as f32
    };
    let pos_x = runtime.start_x + (runtime.end_x - runtime.start_x) * progress;
    let pos_y = if uses_fixed_y_collision_policy(&runtime.collision_policy) {
        runtime.start_y
    } else {
        runtime.start_y + (runtime.end_y - runtime.start_y) * progress
    };
    let pos_z = runtime.start_z + (runtime.end_z - runtime.start_z) * progress;
    let yaw = if runtime.facing_policy == SPECIAL_MOVEMENT_FACING_FACE_PATH {
        let dx = runtime.end_x - runtime.start_x;
        let dz = runtime.end_z - runtime.start_z;
        if dx * dx + dz * dz > 0.0001 {
            dx.atan2(dz)
        } else {
            runtime.facing_yaw_start
        }
    } else {
        runtime.facing_yaw_start
    };

    (pos_x, pos_y, pos_z, yaw, finished)
}

fn uses_fixed_y_collision_policy(collision_policy: &str) -> bool {
    collision_policy == SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y
        || collision_policy == SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY
}

/// Synchronizes the persistent fallback state used when the next queued input
/// command has not arrived. Tick/timestamp bookkeeping alone is intentionally
/// excluded: the every-tick acknowledgement lives on `PlayerPhysics`, while
/// `PlayerIntent` only needs a write when gameplay-observable retained input
/// changes. Jump edges remain queue-only and are never retained here.
fn apply_player_intent_fallback_if_changed(
    current: &mut PlayerIntent,
    applied: &PlayerIntent,
) -> bool {
    let changed = current.forward != applied.forward
        || current.strafe != applied.strafe
        || current.yaw != applied.yaw
        || current.jump;
    if !changed {
        return false;
    }

    current.forward = applied.forward;
    current.strafe = applied.strafe;
    current.yaw = applied.yaw;
    current.jump = false;
    current.input_tick = applied.input_tick;
    current.updated_at = applied.updated_at;
    true
}

fn try_tick_special_movement_player(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    movement_blocked: bool,
    move_speed_multiplier: f32,
    physics: &mut PlayerPhysics,
    state: &mut crate::player_state::PlayerState,
    intent: &mut PlayerIntent,
) -> bool {
    if ctx
        .db
        .special_movement_runtime()
        .owner()
        .find(identity)
        .is_none()
    {
        return false;
    }

    let next_input_tick = physics.last_processed_tick.saturating_add(1);
    let mut step_intent = PlayerIntent {
        identity,
        forward: intent.forward,
        strafe: intent.strafe,
        yaw: intent.yaw,
        jump: false,
        input_tick: next_input_tick,
        updated_at: now,
    };
    let mut consumed_real_command = false;
    if let Some(command) = pop_command_for_tick(ctx, identity, next_input_tick) {
        step_intent.forward = command.forward;
        step_intent.strafe = command.strafe;
        step_intent.yaw = command.yaw;
        consumed_real_command = true;
    }

    physics.last_processed_tick = next_input_tick;
    physics.last_tick_consumed_command = consumed_real_command;
    physics.buffered_command_count = count_buffered_commands(ctx, identity);
    physics.updated_at = now;
    if apply_player_intent_fallback_if_changed(intent, &step_intent) {
        record_table_write(TableWriteKind::PlayerIntent);
        ctx.db.player_intent().identity().update(PlayerIntent {
            identity: intent.identity,
            forward: intent.forward,
            strafe: intent.strafe,
            yaw: intent.yaw,
            jump: intent.jump,
            input_tick: intent.input_tick,
            updated_at: intent.updated_at,
        });
    }

    let state_changed = sync_player_movement_context(
        state,
        movement_blocked,
        move_speed_multiplier,
        next_input_tick,
    );
    commit_player_physics(
        ctx,
        PlayerPhysics {
            identity: physics.identity,
            pos_x: physics.pos_x,
            pos_y: physics.pos_y,
            pos_z: physics.pos_z,
            vel_x: physics.vel_x,
            vel_y: physics.vel_y,
            vel_z: physics.vel_z,
            yaw: physics.yaw,
            grounded: physics.grounded,
            last_processed_tick: physics.last_processed_tick,
            last_tick_consumed_command: physics.last_tick_consumed_command,
            buffered_command_count: physics.buffered_command_count,
            updated_at: physics.updated_at,
        },
        PhysicsWriteMode::Normal,
        "try_tick_special_movement_player",
    );
    if state_changed {
        ctx.db
            .player_state()
            .player_id()
            .update(crate::player_state::PlayerState {
                player_id: state.player_id,
                is_dummy: state.is_dummy,
                alive: state.alive,
                eliminated: state.eliminated,
                hp: state.hp,
                max_hp: state.max_hp,
                hit_radius: state.hit_radius,
                hit_height: state.hit_height,
                movement_blocked: state.movement_blocked,
                move_speed_multiplier: state.move_speed_multiplier,
                movement_context_tick: state.movement_context_tick,
                voluntary_move_epoch: state.voluntary_move_epoch,
                last_voluntary_move_input_tick: state.last_voluntary_move_input_tick,
                respawn_at: state.respawn_at,
                last_strike_id: state.last_strike_id.clone(),
                last_strike_at: state.last_strike_at,
            });
    }

    true
}

fn tick_player(
    ctx: &ReducerContext,
    identity: Identity,
    now: Timestamp,
    dt: f32,
    movement_modifiers: &MovementModifiers,
    temporary_modifiers: &TemporaryCombatModifiers,
    contexts: &PlayerTickContexts,
) {
    // Get current physics state
    let Some(mut physics) = ctx.db.player_physics().identity().find(identity) else {
        return;
    };

    // Get current player state
    let Some(mut state) = ctx.db.player_state().player_id().find(identity) else {
        return;
    };

    let next_input_tick = physics.last_processed_tick.saturating_add(1);
    let movement_blocked = movement_modifiers.blocks_movement(&identity);
    let mut move_speed_multiplier =
        movement_modifiers.move_speed_multiplier(&identity, next_input_tick);

    // Dead players ignore inputs and physics until respawn.
    if try_tick_dead_player(ctx, now, &mut physics, &mut state) {
        if state.alive {
            commit_player_physics(
                ctx,
                physics,
                PhysicsWriteMode::Force,
                "try_tick_dead_player_respawn",
            );
            ctx.db.player_state().player_id().update(state);
        }
        return;
    }

    if let Some(physics_changed) = try_tick_playground_target(ctx, identity, now, &mut physics) {
        if physics_changed {
            commit_player_physics(
                ctx,
                physics,
                PhysicsWriteMode::Normal,
                "try_tick_playground_target",
            );
        }
        return;
    }

    if let Some(physics_changed) = try_tick_dummy_player(ctx, identity, now, &mut physics, &state) {
        let movement_context_tick = physics.last_processed_tick;
        let state_changed = sync_player_movement_context(
            &mut state,
            movement_blocked,
            move_speed_multiplier,
            movement_context_tick,
        );
        if physics_changed {
            commit_player_physics(
                ctx,
                physics,
                PhysicsWriteMode::Normal,
                "try_tick_dummy_player",
            );
        }
        if state_changed {
            ctx.db.player_state().player_id().update(state);
        }
        return;
    }

    // Get current intent
    let Some(mut intent) = ctx.db.player_intent().identity().find(identity) else {
        return;
    };
    if try_tick_special_movement_player(
        ctx,
        identity,
        now,
        movement_blocked,
        move_speed_multiplier,
        &mut physics,
        &mut state,
        &mut intent,
    ) {
        return;
    }
    let mut step_intent = PlayerIntent {
        identity,
        forward: intent.forward,
        strafe: intent.strafe,
        yaw: intent.yaw,
        jump: false,
        input_tick: next_input_tick,
        updated_at: now,
    };
    let mut applied_command_input_tick = None;
    if let Some(command) = pop_command_for_tick(ctx, identity, next_input_tick) {
        step_intent.forward = command.forward;
        step_intent.strafe = command.strafe;
        step_intent.yaw = command.yaw;
        step_intent.jump = command.jump;
        step_intent.input_tick = next_input_tick;
        step_intent.updated_at = now;
        applied_command_input_tick = Some(command.input_tick);
    } else {
        // Command hasn't arrived yet — use latest known intent values.
        // The client's prediction deadband absorbs the small error from
        // the stale yaw. Always advance the tick so the server stays
        // current and spells/effects use an up-to-date position.
        log::debug!(
            "[MOVE_FALLBACK] Player {} | tick={} | using fallback intent from tick={}",
            &identity.to_hex()[..8],
            next_input_tick,
            intent.input_tick
        );
        crate::tick_metrics::record_move_fallback();
        step_intent.jump = false;
        step_intent.input_tick = next_input_tick;
        step_intent.updated_at = now;
    }

    // S5: publish this tick's consume truth beside the ack so the client's
    // lead control loop sees starvation/surplus instead of guessing.
    physics.last_tick_consumed_command = applied_command_input_tick.is_some();
    physics.buffered_command_count = count_buffered_commands(ctx, identity);

    let equipment = contexts.equipment(ctx, identity);
    move_speed_multiplier *= contexts.derived(ctx, identity).run_speed_multiplier;
    move_speed_multiplier *= equipment.move_speed_multiplier();

    let grounded_before_step = physics.grounded;
    simulate_non_dummy_player_kinematics(
        identity,
        &mut physics,
        &step_intent,
        arena_seed_for_identity(ctx, identity),
        uses_flat_training_collision(ctx, identity),
        open_world_scene_name_for_identity(ctx, identity),
        now,
        dt,
        movement_blocked,
        move_speed_multiplier,
        state.hit_radius,
        state.hit_height,
    );
    physics.last_processed_tick = next_input_tick;
    if apply_player_intent_fallback_if_changed(&mut intent, &step_intent) {
        record_table_write(TableWriteKind::PlayerIntent);
        ctx.db.player_intent().identity().update(intent);
    }
    let resource_inputs = ResourceSpecInputs {
        status_modifiers: temporary_modifiers,
        equipment: &equipment,
    };
    tick_primary_resource_for_player(ctx, identity, now, dt, &resource_inputs);
    let voluntary_epoch_changed = sync_player_voluntary_move_epoch(
        &mut state,
        movement_blocked,
        &step_intent,
        grounded_before_step,
        applied_command_input_tick,
    );
    let state_changed = sync_player_movement_context(
        &mut state,
        movement_blocked,
        move_speed_multiplier,
        next_input_tick,
    ) || voluntary_epoch_changed;

    // === Step 5: Write physics state ===
    commit_player_physics(
        ctx,
        physics,
        PhysicsWriteMode::Normal,
        "simulate_non_dummy_player_kinematics",
    );
    if state_changed {
        ctx.db.player_state().player_id().update(state);
    }
}

/// The game tick - runs every 33ms.
///
/// This is the SOLE AUTHORITY on physics state.
///
/// The reducer is intentionally a phase orchestrator:
/// 1. Pre-tick housekeeping (casts, practice, queued combat/effects)
/// 2. Per-player authoritative simulation
/// 3. Post-tick pruning/maintenance
///
/// Physics ownership remains singular:
/// - `game_tick` is the only reducer that writes `PlayerPhysics`
/// - helpers may structure the logic, but they execute only inside this reducer
#[reducer]
pub fn game_tick(ctx: &ReducerContext, timer: GameLoopTimer) -> Result<(), String> {
    // Fixed-rate chain first: the next link commits with this tick's writes.
    // (A returned Err would roll the link back too — the watchdog re-seeds
    // that case within a second.)
    reschedule_game_tick(ctx, &timer);
    // Existing DBs republish without re-running init; seed the watchdog here.
    ensure_game_loop_watchdog_schedule(ctx);

    let dt = FIXED_TICK_SECONDS;
    let now = ctx.timestamp;
    let profiling_enabled = tick_profiling_enabled();
    // In the wasm module, one tick per profile window is timed with host-side
    // console timers (`ScopeTimer` reads zero there — no `Instant` on wasm).
    let stopwatch_active =
        profiling_enabled && crate::tick_metrics::take_stopwatch_sample_request();
    let _total_stopwatch = PhaseStopwatch::start(stopwatch_active, "tick_profile/total");
    let total_timer = ScopeTimer::start(profiling_enabled);

    // Per-tick, per-player equipment/derived memo (tick audit T2), shared by
    // the pre-tick and player-simulation phases.
    let player_contexts = PlayerTickContexts::collect(ctx);

    let pre_tick_stopwatch = PhaseStopwatch::start(stopwatch_active, "tick_profile/pre_tick");
    let pre_tick_timer = ScopeTimer::start(profiling_enabled);
    let mut pre_subphase_micros = [0u32; PRE_TICK_SUBPHASE_COUNT];
    let (movement_modifiers, temporary_modifiers) = run_pre_tick_housekeeping_phase(
        ctx,
        now,
        dt,
        profiling_enabled,
        stopwatch_active,
        &mut pre_subphase_micros,
        &player_contexts,
    )?;
    let pre_tick_micros = pre_tick_timer.elapsed_micros();
    drop(pre_tick_stopwatch);

    let player_sim_stopwatch = PhaseStopwatch::start(stopwatch_active, "tick_profile/player_sim");
    let player_sim_timer = ScopeTimer::start(profiling_enabled);
    run_player_simulation_phase(
        ctx,
        now,
        dt,
        &movement_modifiers,
        &temporary_modifiers,
        &player_contexts,
    );
    resolve_pending_casts(ctx, now)?;
    let player_sim_micros = player_sim_timer.elapsed_micros();
    drop(player_sim_stopwatch);

    let post_tick_stopwatch = PhaseStopwatch::start(stopwatch_active, "tick_profile/post_tick");
    let post_tick_timer = ScopeTimer::start(profiling_enabled);
    run_post_tick_maintenance_phase(ctx, now);
    let post_tick_micros = post_tick_timer.elapsed_micros();
    drop(post_tick_stopwatch);

    let match_stopwatch = PhaseStopwatch::start(stopwatch_active, "tick_profile/match");
    let match_maintenance_timer = ScopeTimer::start(profiling_enabled);
    run_match_world_maintenance_phase(ctx, now);
    let match_maintenance_micros = match_maintenance_timer.elapsed_micros();
    drop(match_stopwatch);

    if profiling_enabled {
        let maybe_window_ticks = record_tick_profile(
            now,
            TickProfileSample {
                total_micros: total_timer.elapsed_micros(),
                pre_tick_micros,
                player_sim_micros,
                post_tick_micros,
                match_maintenance_micros,
                pre_subphase_micros,
            },
        );
        if let Some(window_ticks) = maybe_window_ticks {
            log_tick_scan_profile(ctx, window_ticks);
            crate::tick_metrics::request_stopwatch_sample();
        }
    }

    Ok(())
}

const COUNTDOWN_DURATION: Duration = Duration::from_secs(3);

fn tick_countdowns(ctx: &ReducerContext, now: Timestamp) {
    let instances: Vec<_> = ctx
        .db
        .arena_instance()
        .iter()
        .filter(|a| a.phase == MATCH_PHASE_COUNTDOWN)
        .collect();

    for mut arena in instances {
        let Some(started_at) = arena.countdown_started_at else {
            continue;
        };
        let now_micros: i64 = now.to_micros_since_unix_epoch();
        let started_micros: i64 = started_at.to_micros_since_unix_epoch();
        let elapsed_micros = now_micros.saturating_sub(started_micros);
        if elapsed_micros >= COUNTDOWN_DURATION.as_micros() as i64 {
            arena.phase = MATCH_PHASE_IN_PROGRESS.to_string();
            arena.countdown_started_at = None;
            ctx.db.arena_instance().id().update(arena);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        apply_player_intent_fallback_if_changed, fresh_game_tick_schedule,
        game_loop_timer_is_overdue, next_game_tick_schedule, percentile_sorted,
        settle_stationary_dummy, settle_stationary_playground_target,
        special_movement_grounded_state, sync_player_voluntary_move_epoch, PlayerIntent,
        PlayerPhysics, TickProfileSample, TickProfileWindowState,
        SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y,
        SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY,
    };
    use crate::combat::new_player_state;
    use spacetimedb::{Identity, ScheduleAt, Timestamp};

    fn sample(total_micros: u32, pre_micros: u32) -> TickProfileSample {
        TickProfileSample {
            total_micros,
            pre_tick_micros: pre_micros,
            player_sim_micros: pre_micros / 2,
            post_tick_micros: pre_micros / 4,
            match_maintenance_micros: pre_micros / 8,
            pre_subphase_micros: [pre_micros / 16; super::PRE_TICK_SUBPHASE_COUNT],
        }
    }

    fn intent(forward: f32, strafe: f32, jump: bool) -> PlayerIntent {
        PlayerIntent {
            identity: Identity::ZERO,
            forward,
            strafe,
            yaw: 1.25,
            jump,
            input_tick: 1,
            updated_at: Timestamp::UNIX_EPOCH,
        }
    }

    #[test]
    fn game_tick_recovery_schedule_is_strictly_future_dated() {
        let now = Timestamp::from_micros_since_unix_epoch(1_000_000);
        let fresh = fresh_game_tick_schedule(now);
        assert_eq!(fresh.to_micros_since_unix_epoch(), 1_033_000);

        let stale = ScheduleAt::Time(Timestamp::from_micros_since_unix_epoch(500_000));
        let (recovered, reanchored) = next_game_tick_schedule(now, &stale);
        assert!(reanchored);
        assert_eq!(recovered.to_micros_since_unix_epoch(), 1_033_000);
    }

    #[test]
    fn healthy_game_tick_chain_preserves_fixed_rate_anchor() {
        let now = Timestamp::from_micros_since_unix_epoch(1_000_000);
        let fired = ScheduleAt::Time(Timestamp::from_micros_since_unix_epoch(990_000));
        let (next, reanchored) = next_game_tick_schedule(now, &fired);

        assert!(!reanchored);
        assert_eq!(next.to_micros_since_unix_epoch(), 1_023_000);
    }

    #[test]
    fn watchdog_treats_overdue_present_timer_as_dead_chain() {
        let now = Timestamp::from_micros_since_unix_epoch(1_000_000);
        let overdue = ScheduleAt::Time(Timestamp::from_micros_since_unix_epoch(900_000));
        let recent = ScheduleAt::Time(Timestamp::from_micros_since_unix_epoch(902_000));

        assert!(game_loop_timer_is_overdue(now, &overdue));
        assert!(!game_loop_timer_is_overdue(now, &recent));
    }

    #[test]
    fn player_intent_fallback_skips_bookkeeping_only_advances() {
        let mut current = intent(1.0, -0.5, false);
        let mut applied = intent(1.0, -0.5, false);
        applied.input_tick = 2;
        applied.updated_at = Timestamp::from_micros_since_unix_epoch(2);

        assert!(!apply_player_intent_fallback_if_changed(
            &mut current,
            &applied
        ));
        assert_eq!(current.input_tick, 1);
        assert_eq!(current.updated_at, Timestamp::UNIX_EPOCH);
    }

    #[test]
    fn player_intent_fallback_persists_key_up() {
        let mut current = intent(1.0, -0.5, false);
        let mut applied = intent(0.0, 0.0, false);
        applied.input_tick = 2;
        applied.updated_at = Timestamp::from_micros_since_unix_epoch(2);

        assert!(apply_player_intent_fallback_if_changed(
            &mut current,
            &applied
        ));
        assert_eq!(current.forward, 0.0);
        assert_eq!(current.strafe, 0.0);
        assert_eq!(current.input_tick, 2);
        assert_eq!(
            current.updated_at,
            Timestamp::from_micros_since_unix_epoch(2)
        );
    }

    #[test]
    fn player_intent_fallback_persists_yaw_only_changes() {
        let mut current = intent(0.0, 0.0, false);
        let mut applied = intent(0.0, 0.0, false);
        applied.yaw = 2.5;
        applied.input_tick = 2;
        applied.updated_at = Timestamp::from_micros_since_unix_epoch(2);

        assert!(apply_player_intent_fallback_if_changed(
            &mut current,
            &applied
        ));
        assert_eq!(current.yaw, 2.5);
        assert_eq!(current.input_tick, 2);
    }

    #[test]
    fn player_intent_fallback_does_not_persist_jump_edges() {
        let mut current = intent(0.0, 0.0, false);
        let mut applied = intent(0.0, 0.0, true);
        applied.input_tick = 2;
        applied.updated_at = Timestamp::from_micros_since_unix_epoch(2);

        assert!(!apply_player_intent_fallback_if_changed(
            &mut current,
            &applied
        ));
        assert!(!current.jump);
        assert_eq!(current.input_tick, 1);
    }

    #[test]
    fn voluntary_move_epoch_ignores_yaw_only_intent() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.0, 0.0, false),
            true,
            Some(7),
        );

        assert!(!changed);
        assert_eq!(state.voluntary_move_epoch, 0);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    #[test]
    fn voluntary_move_epoch_increments_for_accepted_locomotion_intent() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.5, 0.0, false),
            false,
            Some(7),
        );

        assert!(changed);
        assert_eq!(state.voluntary_move_epoch, 1);
        assert_eq!(state.last_voluntary_move_input_tick, 7);
    }

    #[test]
    fn voluntary_move_epoch_increments_for_grounded_jump_input() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.0, 0.0, true),
            true,
            Some(7),
        );

        assert!(changed);
        assert_eq!(state.voluntary_move_epoch, 1);
        assert_eq!(state.last_voluntary_move_input_tick, 7);
    }

    #[test]
    fn voluntary_move_epoch_ignores_airborne_jump_input() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(0.0, 0.0, true),
            false,
            Some(7),
        );

        assert!(!changed);
        assert_eq!(state.voluntary_move_epoch, 0);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    #[test]
    fn voluntary_move_epoch_ignores_blocked_movement_input() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            true,
            &intent(1.0, 0.0, true),
            true,
            Some(7),
        );

        assert!(!changed);
        assert_eq!(state.voluntary_move_epoch, 0);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    #[test]
    fn voluntary_move_epoch_does_not_record_fallback_as_authored_movement() {
        let mut state = new_player_state(Identity::ZERO, Timestamp::UNIX_EPOCH);
        let changed = sync_player_voluntary_move_epoch(
            &mut state,
            false,
            &intent(1.0, 0.0, false),
            true,
            None,
        );

        assert!(changed);
        assert_eq!(state.voluntary_move_epoch, 1);
        assert_eq!(state.last_voluntary_move_input_tick, 0);
    }

    fn test_physics_at(x: f32, y: f32, z: f32, yaw: f32) -> PlayerPhysics {
        PlayerPhysics {
            identity: Identity::ZERO,
            pos_x: x,
            pos_y: y,
            pos_z: z,
            vel_x: 1.0,
            vel_y: 2.0,
            vel_z: 3.0,
            yaw,
            grounded: false,
            last_processed_tick: 7,
            last_tick_consumed_command: true,
            buffered_command_count: 0,
            updated_at: Timestamp::from_micros_since_unix_epoch(1),
        }
    }

    #[test]
    fn stationary_playground_target_settle_preserves_pose_and_clears_velocity() {
        let mut physics = test_physics_at(12.5, 4.0, -3.25, 1.2);
        let updated_at = Timestamp::from_micros_since_unix_epoch(3);

        assert!(settle_stationary_playground_target(
            &mut physics,
            updated_at
        ));

        assert_eq!(physics.pos_x, 12.5);
        assert_eq!(physics.pos_y, 4.0);
        assert_eq!(physics.pos_z, -3.25);
        assert_eq!(physics.yaw, 1.2);
        assert_eq!(physics.vel_x, 0.0);
        assert_eq!(physics.vel_y, 0.0);
        assert_eq!(physics.vel_z, 0.0);
        assert!(physics.grounded);
        assert_eq!(physics.updated_at, updated_at);
    }

    #[test]
    fn stationary_settles_skip_the_write_when_already_settled() {
        let settled_at = Timestamp::from_micros_since_unix_epoch(3);
        let later = Timestamp::from_micros_since_unix_epoch(4);

        let mut target = test_physics_at(12.5, 4.0, -3.25, 1.2);
        assert!(settle_stationary_playground_target(&mut target, settled_at));
        assert!(!settle_stationary_playground_target(&mut target, later));
        assert_eq!(
            target.updated_at, settled_at,
            "a no-op settle must not restamp updated_at"
        );

        let mut dummy = test_physics_at(1.0, 2.0, 3.0, 0.0);
        assert!(settle_stationary_dummy(&mut dummy, 1.5, settled_at));
        assert!(!settle_stationary_dummy(&mut dummy, 1.5, later));
        assert_eq!(dummy.updated_at, settled_at);
        assert_eq!(dummy.pos_y, 1.5);
    }

    #[test]
    fn stationary_dummy_settle_writes_when_ground_height_changes() {
        let settled_at = Timestamp::from_micros_since_unix_epoch(3);
        let later = Timestamp::from_micros_since_unix_epoch(4);

        let mut dummy = test_physics_at(1.0, 2.0, 3.0, 0.0);
        assert!(settle_stationary_dummy(&mut dummy, 1.5, settled_at));
        assert!(settle_stationary_dummy(&mut dummy, 1.75, later));
        assert_eq!(dummy.pos_y, 1.75);
        assert_eq!(dummy.updated_at, later);
    }

    #[test]
    fn special_movement_handoff_preserves_airborne_state_for_fixed_y_runtime() {
        assert!(!special_movement_grounded_state(
            SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y,
            true
        ));
        assert!(!special_movement_grounded_state(
            SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_KEEP_HEIGHT_LEGACY,
            true
        ));
    }

    #[test]
    fn special_movement_handoff_preserves_grounded_state_for_ground_following_runtime() {
        assert!(special_movement_grounded_state("STOP_AT_BLOCK", true));
        assert!(!special_movement_grounded_state("STOP_AT_BLOCK", false));
    }

    #[test]
    fn percentile_sorted_uses_nearest_rank() {
        let sorted = [1_u32, 2, 3, 4, 5];
        assert_eq!(percentile_sorted(&sorted, 50, 100), 3);
        assert_eq!(percentile_sorted(&sorted, 95, 100), 5);
        assert_eq!(percentile_sorted(&sorted, 99, 100), 5);
    }

    #[test]
    fn tick_profile_window_flushes_after_five_seconds() {
        let mut state = TickProfileWindowState::default();
        assert!(state.record(0, sample(12_000, 6_000)).is_none());

        let summary = state
            .record(5_000_000, sample(18_000, 8_000))
            .expect("expected flush after five seconds");

        assert_eq!(summary.count, 2);
        assert_eq!(summary.total_p50_micros, 12_000);
        assert_eq!(summary.total_p95_micros, 18_000);
        assert_eq!(summary.total_p99_micros, 18_000);
        assert_eq!(summary.total_max_micros, 18_000);
        assert_eq!(summary.pre_tick.p95_micros, 8_000);
        assert_eq!(summary.pre_tick.max_micros, 8_000);
    }

    #[test]
    fn tick_profile_window_tracks_over_budget_streaks() {
        let mut state = TickProfileWindowState::default();
        assert!(state.record(0, sample(34_000, 10_000)).is_none());
        assert!(state.record(1_000_000, sample(35_000, 10_000)).is_none());
        assert!(state.record(2_000_000, sample(10_000, 10_000)).is_none());
        assert!(state.record(3_000_000, sample(34_000, 10_000)).is_none());

        let summary = state
            .record(5_000_000, sample(10_000, 10_000))
            .expect("expected flush after five seconds");

        assert_eq!(summary.over_budget_count, 3);
        assert_eq!(summary.max_consecutive_over_budget, 2);
    }
}
