//! Movement Constants and Movement Command Reducer
//!
//! This module contains:
//! - Movement constants (speed, gravity, jump velocity)
//! - send_movement_intent reducer
//!
//! CRITICAL OWNERSHIP RULE:
//! `send_movement_intent` writes ONLY to the queued input stream
//! (`PlayerCommand` and `PlayerInputCursor`).
//! It does not mutate PlayerPhysics or authoritative intent state, but it may
//! read PlayerPhysics to reject already-processed late commands.
//!
//! The intent reducer's job is to record what the player WANTS.
//! The game_tick reducer decides what actually HAPPENS.

use spacetimedb::{reducer, ReducerContext, Table};

// Import accessor traits (generated by #[table] macro, needed for ctx.db.table_name())
#[allow(unused_imports)]
use crate::player_input::player_command as _;
#[allow(unused_imports)]
use crate::player_input::player_input_cursor as _;
use crate::player_input::PlayerCommand;
#[allow(unused_imports)]
use crate::player_physics::player_physics as _;

// === Movement Constants ===
// These are used by game_tick, defined here for easy tuning.

/// Movement speed in units per second
pub const MOVE_SPEED: f32 = 7.0;

/// Authoritative movement tick in milliseconds.
pub const FIXED_TICK_MILLIS: u64 = 33;

/// Authoritative movement tick in seconds.
pub const FIXED_TICK_SECONDS: f32 = FIXED_TICK_MILLIS as f32 / 1000.0;

/// Initial upward velocity when jumping
pub const JUMP_VELOCITY: f32 = 8.0;

/// Gravity acceleration (negative = downward)
pub const GRAVITY: f32 = -25.0;
/// Flat-world baseline Y coordinate for terrain/collision fallback paths.
pub const GROUND_Y: f32 = 0.0;
pub const ZERO_INPUT_EPSILON: f32 = 0.0001;

/// Server mirror of the client's hard prediction bound. A command farther
/// ahead than this cannot be consumed legitimately and must not occupy the
/// persistent input queue.
pub const MAX_INPUT_LEAD_TICKS: u32 = 12;

/// With one command per future tick this is also the maximum legitimate queue
/// occupancy for a player.
pub const MAX_BUFFERED_COMMANDS_PER_PLAYER: u32 = MAX_INPUT_LEAD_TICKS;

// === Intent Reducer ===

/// Receives movement intent from client.
///
/// This reducer:
/// - Validates and clamps input values
/// - Writes to the queued player command stream
/// - Does NOTHING else
///
/// This reducer does NOT:
/// - Check if player is grounded
/// - Modify velocity
/// - Modify position
/// - Execute jump logic
///
/// The separation is intentional. Intent is DATA. Physics is computed in game_tick.
#[reducer]
pub fn send_movement_intent(
    ctx: &ReducerContext,
    forward: f32,    // -1 (back) to 1 (forward)
    strafe: f32,     // -1 (left) to 1 (right)
    yaw: f32,        // Facing direction in radians
    jump: bool,      // Jump requested this frame
    input_tick: u32, // Client-authored fixed input tick
) -> Result<(), String> {
    let identity = ctx.sender();

    if !movement_payload_is_finite(forward, strafe, yaw) {
        return Err("movement input must contain only finite values".to_string());
    }

    let Some(mut cursor) = ctx.db.player_input_cursor().identity().find(identity) else {
        return Err("Player not found".to_string());
    };

    let physics = ctx
        .db
        .player_physics()
        .identity()
        .find(identity)
        .ok_or_else(|| "Player physics not found".to_string())?;
    let max_accepted_tick = physics
        .last_processed_tick
        .saturating_add(MAX_INPUT_LEAD_TICKS);

    if input_tick > max_accepted_tick {
        return Err(format!(
            "movement input tick {input_tick} exceeds maximum accepted tick {max_accepted_tick}"
        ));
    }

    let latest_buffered_tick = crate::player_input::prune_player_commands_outside_window(
        ctx,
        identity,
        physics.last_processed_tick,
        max_accepted_tick,
    );

    // Repair a cursor poisoned by an older unbounded reducer. The queue was
    // pruned above, so the repaired cursor reflects only consumable input.
    if cursor.latest_received_tick > max_accepted_tick {
        cursor.latest_received_tick = latest_buffered_tick.unwrap_or(physics.last_processed_tick);
        ctx.db
            .player_input_cursor()
            .identity()
            .update(cursor.clone());
    }

    let forward = forward.clamp(-1.0, 1.0);
    let strafe = strafe.clamp(-1.0, 1.0);
    let yaw = normalize_yaw(yaw);

    if input_tick <= physics.last_processed_tick {
        // S5 jump preservation: the late command's motion is stale, but a
        // jump edge is a discrete press the player made — give it one
        // extra tick of life instead of eating it. Only a command that
        // missed its tick by less than one consume (input_tick equals the
        // tick just processed via fallback) slides; anything staler is
        // honestly dropped. The cursor gate stays authoritative: a tick
        // the cursor already passed (e.g. the post-special-movement
        // discard window) must not resurrect a jump through the slide.
        if jump
            && input_tick == physics.last_processed_tick
            && input_tick > cursor.latest_received_tick
        {
            let slide_tick = physics.last_processed_tick.saturating_add(1);
            if let Some(mut buffered) =
                crate::player_input::find_buffered_command_for_tick(ctx, identity, slide_tick)
            {
                if !buffered.jump {
                    buffered.jump = true;
                    ctx.db.player_command().command_id().update(buffered);
                }
            } else {
                if crate::player_input::count_buffered_commands(ctx, identity)
                    >= MAX_BUFFERED_COMMANDS_PER_PLAYER
                {
                    return Err("movement input queue is full".to_string());
                }
                ctx.db.player_command().insert(PlayerCommand {
                    command_id: 0,
                    identity,
                    input_tick: slide_tick,
                    forward,
                    strafe,
                    yaw,
                    jump: true,
                    received_at: ctx.timestamp,
                });
            }
            // info-level on purpose: slides are rare events (a jump that
            // missed its tick by less than one consume) and the log line
            // is the live evidence signal for them.
            log::info!(
                "[MOVE_JUMP_SLIDE] Player {} | late jump at tick={} rebuffered for tick={}",
                &identity.to_hex()[..8],
                input_tick,
                slide_tick
            );
            return Ok(());
        }

        log::debug!(
            "[MOVE_LATE_DROP] Player {} | input_tick={} <= last_processed_tick={}",
            &identity.to_hex()[..8],
            input_tick,
            physics.last_processed_tick
        );
        return Ok(());
    }

    // Ignore stale inputs (out of order)
    if input_tick <= cursor.latest_received_tick {
        return Ok(());
    }

    // A slid late jump (above) may already occupy this tick's slot; merge the
    // real command into it — the axes are fresher and the jump edge must not
    // be lost — instead of inserting a duplicate-tick row.
    if let Some(mut buffered) =
        crate::player_input::find_buffered_command_for_tick(ctx, identity, input_tick)
    {
        buffered.forward = forward;
        buffered.strafe = strafe;
        buffered.yaw = yaw;
        buffered.jump = buffered.jump || jump;
        buffered.received_at = ctx.timestamp;
        ctx.db.player_command().command_id().update(buffered);
    } else {
        if crate::player_input::count_buffered_commands(ctx, identity)
            >= MAX_BUFFERED_COMMANDS_PER_PLAYER
        {
            return Err("movement input queue is full".to_string());
        }
        ctx.db.player_command().insert(PlayerCommand {
            command_id: 0,
            identity,
            input_tick,
            forward,
            strafe,
            yaw,
            jump,
            received_at: ctx.timestamp,
        });
    }

    cursor.latest_received_tick = input_tick;
    ctx.db.player_input_cursor().identity().update(cursor);

    Ok(())
}

// === Helper Functions (pure, used by game_tick) ===

fn movement_payload_is_finite(forward: f32, strafe: f32, yaw: f32) -> bool {
    forward.is_finite() && strafe.is_finite() && yaw.is_finite()
}

fn normalize_yaw(yaw: f32) -> f32 {
    (yaw + std::f32::consts::PI).rem_euclid(std::f32::consts::TAU) - std::f32::consts::PI
}

/// Calculate world-space velocity from intent and yaw.
/// Returns (vel_x, vel_z) in world coordinates.
///
/// This is a pure function - no side effects, no table access.
pub fn velocity_from_intent(forward: f32, strafe: f32, yaw: f32, speed: f32) -> (f32, f32) {
    if !movement_payload_is_finite(forward, strafe, yaw) || !speed.is_finite() {
        return (0.0, 0.0);
    }

    // If no input, no velocity
    if forward.abs() <= ZERO_INPUT_EPSILON && strafe.abs() <= ZERO_INPUT_EPSILON {
        return (0.0, 0.0);
    }

    // Calculate direction vector in world space
    // yaw = 0 means facing +Z
    // forward input moves along facing direction
    // strafe input moves perpendicular (right is +yaw rotation)
    let sin_yaw = yaw.sin();
    let cos_yaw = yaw.cos();

    // Forward direction: (sin(yaw), cos(yaw))
    // Right direction: (cos(yaw), -sin(yaw))
    let dir_x = forward * sin_yaw + strafe * cos_yaw;
    let dir_z = forward * cos_yaw - strafe * sin_yaw;

    // Normalize if magnitude > 1 (diagonal movement shouldn't be faster)
    let mag_sq = dir_x * dir_x + dir_z * dir_z;
    if mag_sq > 1.0 {
        let mag = mag_sq.sqrt();
        return (dir_x / mag * speed, dir_z / mag * speed);
    }

    (dir_x * speed, dir_z * speed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn movement_payload_rejects_non_finite_components() {
        assert!(movement_payload_is_finite(1.0, -1.0, 0.5));
        assert!(!movement_payload_is_finite(f32::NAN, 0.0, 0.0));
        assert!(!movement_payload_is_finite(0.0, f32::INFINITY, 0.0));
        assert!(!movement_payload_is_finite(0.0, 0.0, f32::NEG_INFINITY));
    }

    #[test]
    fn movement_yaw_is_normalized_to_signed_radians() {
        assert!((normalize_yaw(0.0) - 0.0).abs() < 0.0001);
        assert!((normalize_yaw(std::f32::consts::TAU + 0.25) - 0.25).abs() < 0.0001);
        assert!((normalize_yaw(-std::f32::consts::TAU - 0.25) + 0.25).abs() < 0.0001);
    }

    #[test]
    fn velocity_helper_fails_closed_for_non_finite_input() {
        assert_eq!(
            velocity_from_intent(f32::NAN, 0.0, 0.0, MOVE_SPEED),
            (0.0, 0.0)
        );
        assert_eq!(
            velocity_from_intent(1.0, 0.0, f32::NAN, MOVE_SPEED),
            (0.0, 0.0)
        );
    }
}
