//! Movement Constants and Movement Command Reducer
//!
//! This module contains:
//! - Movement constants (speed, gravity, jump velocity)
//! - send_movement_intent reducer
//!
//! CRITICAL OWNERSHIP RULE:
//! `send_movement_intent` writes ONLY to the queued input stream
//! (`PlayerCommand` and `PlayerInputCursor`).
//! It does not mutate PlayerPhysics or authoritative intent state, but it may
//! read PlayerPhysics to reject already-processed late commands.
//!
//! The intent reducer's job is to record what the player WANTS.
//! The game_tick reducer decides what actually HAPPENS.

use spacetimedb::{reducer, ReducerContext, Table};

// Import accessor traits (generated by #[table] macro, needed for ctx.db.table_name())
#[allow(unused_imports)]
use crate::player_input::player_command as _;
#[allow(unused_imports)]
use crate::player_input::player_input_cursor as _;
use crate::player_input::PlayerCommand;
#[allow(unused_imports)]
use crate::player_physics::player_physics as _;

// === Movement Constants ===
// These are used by game_tick, defined here for easy tuning.

/// Movement speed in units per second
pub const MOVE_SPEED: f32 = 7.0;

/// Authoritative movement tick in milliseconds.
pub const FIXED_TICK_MILLIS: u64 = 33;

/// Authoritative movement tick in seconds.
pub const FIXED_TICK_SECONDS: f32 = FIXED_TICK_MILLIS as f32 / 1000.0;

/// Initial upward velocity when jumping
pub const JUMP_VELOCITY: f32 = 8.0;

/// Gravity acceleration (negative = downward)
pub const GRAVITY: f32 = -25.0;
/// Flat-world baseline Y coordinate for terrain/collision fallback paths.
pub const GROUND_Y: f32 = 0.0;
pub const ZERO_INPUT_EPSILON: f32 = 0.0001;

// === Intent Reducer ===

/// Receives movement intent from client.
///
/// This reducer:
/// - Validates and clamps input values
/// - Writes to the queued player command stream
/// - Does NOTHING else
///
/// This reducer does NOT:
/// - Check if player is grounded
/// - Modify velocity
/// - Modify position
/// - Execute jump logic
///
/// The separation is intentional. Intent is DATA. Physics is computed in game_tick.
#[reducer]
pub fn send_movement_intent(
    ctx: &ReducerContext,
    forward: f32,    // -1 (back) to 1 (forward)
    strafe: f32,     // -1 (left) to 1 (right)
    yaw: f32,        // Facing direction in radians
    jump: bool,      // Jump requested this frame
    input_tick: u32, // Client-authored fixed input tick
) -> Result<(), String> {
    let identity = ctx.sender();

    let Some(mut cursor) = ctx.db.player_input_cursor().identity().find(identity) else {
        return Err("Player not found".to_string());
    };

    if let Some(physics) = ctx.db.player_physics().identity().find(identity) {
        if input_tick <= physics.last_processed_tick {
            log::debug!(
                "[MOVE_LATE_DROP] Player {} | input_tick={} <= last_processed_tick={}",
                &identity.to_hex()[..8],
                input_tick,
                physics.last_processed_tick
            );
            return Ok(());
        }
    }

    // Ignore stale inputs (out of order)
    if input_tick <= cursor.latest_received_tick {
        return Ok(());
    }

    // Clamp inputs to valid range
    let forward = forward.clamp(-1.0, 1.0);
    let strafe = strafe.clamp(-1.0, 1.0);

    ctx.db.player_command().insert(PlayerCommand {
        command_id: 0,
        identity,
        input_tick,
        forward,
        strafe,
        yaw,
        jump,
        received_at: ctx.timestamp,
    });

    cursor.latest_received_tick = input_tick;
    ctx.db.player_input_cursor().identity().update(cursor);

    Ok(())
}

// === Helper Functions (pure, used by game_tick) ===

/// Calculate world-space velocity from intent and yaw.
/// Returns (vel_x, vel_z) in world coordinates.
///
/// This is a pure function - no side effects, no table access.
pub fn velocity_from_intent(forward: f32, strafe: f32, yaw: f32, speed: f32) -> (f32, f32) {
    // If no input, no velocity
    if forward.abs() <= ZERO_INPUT_EPSILON && strafe.abs() <= ZERO_INPUT_EPSILON {
        return (0.0, 0.0);
    }

    // Calculate direction vector in world space
    // yaw = 0 means facing +Z
    // forward input moves along facing direction
    // strafe input moves perpendicular (right is +yaw rotation)
    let sin_yaw = yaw.sin();
    let cos_yaw = yaw.cos();

    // Forward direction: (sin(yaw), cos(yaw))
    // Right direction: (cos(yaw), -sin(yaw))
    let dir_x = forward * sin_yaw + strafe * cos_yaw;
    let dir_z = forward * cos_yaw - strafe * sin_yaw;

    // Normalize if magnitude > 1 (diagonal movement shouldn't be faster)
    let mag_sq = dir_x * dir_x + dir_z * dir_z;
    if mag_sq > 1.0 {
        let mag = mag_sq.sqrt();
        return (dir_x / mag * speed, dir_z / mag * speed);
    }

    (dir_x * speed, dir_z * speed)
}
