//! Proximity-triggered dungeon traps.
//!
//! Placement (`random_dungeon.traps.shared.json`) is regenerated by the dungeon
//! generator; behaviour (`world_trap_profiles.shared.json`) is authored per
//! kind, so retuning trap damage never requires a dungeon rebuild.
//!
//! Authority split, mirroring the world-door foundation:
//!   * the server owns every trap decision and all damage;
//!   * the client receives one row per FIRING trap and scrubs a vendor clip to
//!     the frame that row's `cycle_started_at` implies;
//!   * confirmed trap contacts reuse the shared combat-impact presentation path.
//!
//! Traps never block movement, sight, or projectiles: no collider is authored
//! on a trap, and nothing here participates in the collision or LOS contract.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;
use std::time::Duration;

use serde::Deserialize;
use spacetimedb::{table, Identity, ReducerContext, Table, Timestamp};

use crate::arena::{resolve_player_world_context, ResolvedWorldContext};
use crate::combat::actor_snapshot::{CombatActorSnapshot, CombatActorSnapshotSet};
use crate::combat::{
    queue_effects, timestamp_to_micros, CombatEvent, DamageDelivery, DamageType, EffectPacket,
    StackPolicy, StatusDispelType, StatusPayload, StatusPolarity, COMBAT_EVENT_IMPACT,
    COMBAT_METADATA_NONE, COMBAT_SCALAR_NONE, COMBAT_SEQUENCE_NONE, DAMAGE_SOURCE_KIND_TRAP,
};
use crate::relations::TargetAudience;

#[allow(unused_imports)]
use crate::combat::combat_event as _;
#[allow(unused_imports)]
use crate::npcs::npc_instance as _;
#[allow(unused_imports)]
use crate::player_state::player_state as _;
#[allow(unused_imports)]
use crate::world_traps::{world_trap_activation_hit as _, world_trap_state as _};

const TRAP_MANIFEST_JSON: &str = include_str!("world_data/random_dungeon.traps.shared.json");
const TRAP_PROFILE_MANIFEST_JSON: &str = include_str!("world_data/world_trap_profiles.shared.json");
const RANDOM_DUNGEON_WORLD_KEY: &str = "RANDOM_DUNGEON";
const RANDOM_DUNGEON_SCENE_NAME: &str = "RandomDungeon";
const WORLD_KIND_OPEN: &str = "OPEN";

const TRIGGER_KIND_PROXIMITY: &str = "PROXIMITY";
const TRIGGER_KIND_ALWAYS: &str = "ALWAYS";
const EFFECT_KIND_DAMAGE: &str = "DAMAGE";
const EFFECT_KIND_DOT: &str = "DOT";

/// One row per trap that is mid-cycle. At rest the table is empty, so
/// replication cost scales with FIRING traps, not with trap count.
#[table(accessor = world_trap_state, public)]
#[derive(Clone)]
pub struct WorldTrapState {
    #[primary_key]
    pub trap_state_id: String,
    #[index(btree)]
    pub trap_definition_id: String,
    pub world_kind: String,
    pub instance_id: Option<u64>,
    /// Query-safe scalar mirror of `instance_id`; zero means open world.
    #[index(btree)]
    pub instance_scope_id: u64,
    pub open_world_scene_name: String,
    /// The one authoritative phase anchor. Everything else — telegraph, hazard
    /// window, client scrub — is derived from it.
    pub cycle_started_at: Timestamp,
    #[index(btree)]
    pub cycle_ends_at_micros: i64,
    pub activation: u64,
}

/// Server-only ledger enforcing one hit per actor per activation. Deleted with
/// its state row, so it can never outlive the cycle that created it.
#[table(accessor = world_trap_activation_hit)]
#[derive(Clone)]
pub struct WorldTrapActivationHit {
    #[primary_key]
    pub hit_id: String,
    #[index(btree)]
    pub trap_state_id: String,
    pub actor: Identity,
}

#[derive(Clone, Copy, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ManifestVector3 {
    x: f32,
    y: f32,
    z: f32,
}

#[derive(Clone, Copy, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TrapVolumeDefinition {
    center: ManifestVector3,
    size: ManifestVector3,
}

#[derive(Clone, Copy, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TrapTrackKey {
    t_ms: u32,
    offset: ManifestVector3,
}

/// Flat, not a tagged union: one struct with every field present keeps the
/// `deny_unknown_fields` contract simple and makes a mis-tagged entry
/// impossible. `effect` selects which fields matter.
#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TrapOnHitDefinition {
    effect: String,
    amount: i32,
    damage_type: String,
    tick_amount: i32,
    tick_interval_ms: u64,
    duration_ms: u64,
    stack_group: String,
    max_stacks: u32,
    stack_policy: String,
    #[serde(default)]
    dispel_types: Vec<StatusDispelType>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TrapProfileDefinition {
    profile_id: String,
    trigger_kind: String,
    trigger_delay_ms: u64,
    cycle_ms: u64,
    hazard_start_ms: u64,
    hazard_end_ms: u64,
    rearm_ms: u64,
    trigger_volume: TrapVolumeDefinition,
    hazard_volume: TrapVolumeDefinition,
    hazard_track: Vec<TrapTrackKey>,
    on_hit: Vec<TrapOnHitDefinition>,
    one_hit_per_activation: bool,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TrapProfileManifest {
    schema_version: u32,
    profiles: Vec<TrapProfileDefinition>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TrapDefinition {
    trap_definition_id: String,
    world_definition_key: String,
    trap_profile_id: String,
    origin: ManifestVector3,
    yaw_degrees: f32,
    footprint_cells: u32,
    definition_version: u32,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TrapManifest {
    schema_version: u32,
    world_definition_key: String,
    traps: Vec<TrapDefinition>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct TrapScope {
    world_kind: String,
    instance_id: Option<u64>,
    open_world_scene_name: String,
}

#[derive(Clone, Copy, Debug)]
struct TrapObb {
    center: [f32; 3],
    half_extents: [f32; 3],
    yaw_radians: f32,
}

// ---------------------------------------------------------------------------
// Tick
// ---------------------------------------------------------------------------

/// Runs inside the pre-tick spell/projectile simulation scope so it reuses the
/// already-built actor snapshot set and its spatial index.
///
/// Asymmetry worth stating out loud (owner ruling, 2026-07-26): the ARMING scan
/// iterates players only, so wandering mobs cannot leave traps permanently
/// cycling; the HAZARD scan iterates every actor, so an NPC standing in a
/// running saw still takes hits.
pub(crate) fn tick_world_traps(
    ctx: &ReducerContext,
    now: Timestamp,
    snapshots: &CombatActorSnapshotSet,
    players: &[Identity],
) {
    if players.is_empty() {
        return;
    }

    expire_due_trap_states(ctx, now);

    let scope = open_random_dungeon_scope();
    let scope_actors = dungeon_scope_actor_identities(ctx, players);
    let live_states: Vec<WorldTrapState> = ctx.db.world_trap_state().iter().collect();
    let mut armed: HashSet<String> = HashSet::with_capacity(live_states.len());
    let mut scratch: Vec<usize> = Vec::new();

    for state in live_states {
        armed.insert(state.trap_definition_id.clone());
        let Some(definition) = trap_definition(state.trap_definition_id.as_str()) else {
            delete_trap_state(ctx, &state);
            continue;
        };
        let Some(profile) = trap_profile(definition.trap_profile_id.as_str()) else {
            delete_trap_state(ctx, &state);
            continue;
        };

        let phase_ms = elapsed_ms(state.cycle_started_at, now);
        let clip_ms = clip_time_ms(phase_ms, profile.trigger_delay_ms);
        if !hazard_is_live(clip_ms, profile) {
            continue;
        }

        apply_hazard_hits(
            ctx,
            &state,
            definition,
            profile,
            clip_ms as f32,
            snapshots,
            &scope_actors,
            &mut scratch,
        );
    }

    for definition in trap_definitions_in_scope(&scope) {
        if armed.contains(definition.trap_definition_id.as_str()) {
            continue;
        }
        let Some(profile) = trap_profile(definition.trap_profile_id.as_str()) else {
            continue;
        };
        if !should_arm(profile, definition, snapshots, players) {
            continue;
        }

        insert_trap_state(ctx, definition, profile, &scope, now);
    }
}

fn should_arm(
    profile: &TrapProfileDefinition,
    definition: &TrapDefinition,
    snapshots: &CombatActorSnapshotSet,
    players: &[Identity],
) -> bool {
    if profile.trigger_kind == TRIGGER_KIND_ALWAYS {
        // An always-on trap re-arms the instant its previous cycle expires. It
        // still only cycles while a player is in the dungeon, because the whole
        // phase early-outs otherwise.
        return true;
    }

    let obb = trap_obb(definition, profile.trigger_volume, [0.0, 0.0, 0.0]);
    let index_by_id = snapshots.index_by_id();
    let actors = snapshots.as_slice();
    players.iter().any(|player| {
        index_by_id
            .get(player)
            .and_then(|index| actors.get(*index))
            .is_some_and(|actor| actor.alive && obb_overlaps_actor(obb, actor))
    })
}

#[allow(clippy::too_many_arguments)]
fn apply_hazard_hits(
    ctx: &ReducerContext,
    state: &WorldTrapState,
    definition: &TrapDefinition,
    profile: &TrapProfileDefinition,
    clip_ms: f32,
    snapshots: &CombatActorSnapshotSet,
    scope_actors: &HashSet<Identity>,
    scratch: &mut Vec<usize>,
) {
    let offset = hazard_offset_at(profile.hazard_track.as_slice(), clip_ms);
    let obb = trap_obb(definition, profile.hazard_volume, offset);
    let query_radius = (obb.half_extents[0] * obb.half_extents[0]
        + obb.half_extents[2] * obb.half_extents[2])
        .sqrt();
    snapshots.query_disc_indices(obb.center[0], obb.center[2], query_radius, scratch);

    let actors = snapshots.as_slice();
    let mut effects: Vec<EffectPacket> = Vec::new();
    for index in scratch.iter() {
        let Some(actor) = actors.get(*index) else {
            continue;
        };
        if !actor.alive || !scope_actors.contains(&actor.player_id) {
            continue;
        }
        if !obb_overlaps_actor(obb, actor) {
            continue;
        }
        if profile.one_hit_per_activation && !record_activation_hit(ctx, state, actor.player_id) {
            continue;
        }

        emit_trap_impact_event(ctx, state, definition, profile, actor, obb.center);
        push_on_hit_effects(&mut effects, profile, actor.player_id);
    }

    if !effects.is_empty() {
        queue_effects(ctx, effects);
    }
}

fn emit_trap_impact_event(
    ctx: &ReducerContext,
    state: &WorldTrapState,
    definition: &TrapDefinition,
    profile: &TrapProfileDefinition,
    target: &CombatActorSnapshot,
    hazard_center: [f32; 3],
) {
    // EntityRegistry's shared hit-reaction path currently presents players;
    // avoid publishing impact rows that no client can consume for NPC targets.
    if ctx
        .db
        .player_state()
        .player_id()
        .find(target.player_id)
        .is_none()
    {
        return;
    }

    let damage = profile
        .on_hit
        .iter()
        .filter(|entry| entry.effect == EFFECT_KIND_DAMAGE)
        .fold(0_i32, |total, entry| {
            total.saturating_add(entry.amount.max(0))
        });
    if damage <= 0 {
        return;
    }

    ctx.db.combat_event().insert(CombatEvent {
        event_id: 0,
        action_instance_id: format!("{}:{}", state.trap_state_id, state.activation),
        action_kind: profile.profile_id.clone(),
        ability_id: String::new(),
        hit_index: 0,
        event_type: COMBAT_EVENT_IMPACT.to_string(),
        source_kind: DAMAGE_SOURCE_KIND_TRAP.to_string(),
        caster: Identity::ZERO,
        hit: target.player_id,
        origin_x: definition.origin.x,
        origin_y: definition.origin.y,
        origin_z: definition.origin.z,
        // Floor spikes have no meaningful horizontal travel direction. The
        // shared client reaction resolver deliberately maps a zero vector to
        // its existing forward-hit fallback.
        dir_x: 0.0,
        dir_y: 1.0,
        dir_z: 0.0,
        speed: 0.0,
        max_distance: 0.0,
        scalar_kind: COMBAT_SCALAR_NONE.to_string(),
        scalar_value: 0.0,
        sequence_kind: COMBAT_SEQUENCE_NONE.to_string(),
        sequence_index: 0,
        sequence_count: 0,
        point_x: hazard_center[0],
        point_y: hazard_center[1],
        point_z: hazard_center[2],
        created_at: ctx.timestamp,
        created_at_micros: timestamp_to_micros(ctx.timestamp),
        damage,
        metadata_kind: COMBAT_METADATA_NONE.to_string(),
        metadata_key: String::new(),
        metadata_value: String::new(),
    });
}

fn push_on_hit_effects(
    effects: &mut Vec<EffectPacket>,
    profile: &TrapProfileDefinition,
    target: Identity,
) {
    for entry in &profile.on_hit {
        match entry.effect.as_str() {
            EFFECT_KIND_DAMAGE => effects.push(EffectPacket::Damage {
                amount: entry.amount,
                damage_type: DamageType::from_wire(entry.damage_type.as_str()),
                // System source: `apply_damage` and `resolve_damage_amount`
                // already branch on Identity::ZERO, skipping attacker stats and
                // `can_harm` while still applying the target's resistances and
                // damage-taken modifiers. No new damage plumbing is needed.
                source: Identity::ZERO,
                target,
                spell_id: profile.profile_id.clone(),
                delivery: DamageDelivery::Direct,
                source_kind: DAMAGE_SOURCE_KIND_TRAP.to_string(),
                direct_action_key: String::new(),
                is_area: false,
            }),
            EFFECT_KIND_DOT => effects.push(EffectPacket::ApplyStatus {
                source: Identity::ZERO,
                target,
                spell_id: profile.profile_id.clone(),
                payload: StatusPayload::Dot {
                    tick_damage: entry.tick_amount,
                    damage_type: DamageType::from_wire(entry.damage_type.as_str()),
                    tick_interval: Duration::from_millis(entry.tick_interval_ms.max(1)),
                },
                polarity: StatusPolarity::Debuff,
                target_audience: TargetAudience::Hostile,
                duration: Duration::from_millis(entry.duration_ms),
                stack_group: entry.stack_group.clone(),
                max_stacks: entry.max_stacks.max(1),
                stack_policy: stack_policy_from_wire(entry.stack_policy.as_str()),
                dispel_types: entry.dispel_types.clone(),
            }),
            _ => {}
        }
    }
}

fn record_activation_hit(ctx: &ReducerContext, state: &WorldTrapState, actor: Identity) -> bool {
    let hit_id = format!(
        "{}|{}|{}",
        state.trap_state_id,
        state.activation,
        actor.to_hex()
    );
    if ctx
        .db
        .world_trap_activation_hit()
        .hit_id()
        .find(hit_id.clone())
        .is_some()
    {
        return false;
    }

    ctx.db
        .world_trap_activation_hit()
        .insert(WorldTrapActivationHit {
            hit_id,
            trap_state_id: state.trap_state_id.clone(),
            actor,
        });
    true
}

fn insert_trap_state(
    ctx: &ReducerContext,
    definition: &TrapDefinition,
    profile: &TrapProfileDefinition,
    scope: &TrapScope,
    now: Timestamp,
) {
    // The row is inserted at TRIGGER time and the clip starts trigger_delay_ms
    // later, so the delay is the reaction window and the client parks the rest
    // pose while phase < delay.
    let lifetime_ms = profile
        .trigger_delay_ms
        .saturating_add(profile.cycle_ms)
        .saturating_add(profile.rearm_ms);
    let cycle_ends_at = now + Duration::from_millis(lifetime_ms);
    let activation = now.to_micros_since_unix_epoch().max(0) as u64;
    ctx.db.world_trap_state().insert(WorldTrapState {
        trap_state_id: trap_state_id(definition, scope),
        trap_definition_id: definition.trap_definition_id.clone(),
        world_kind: scope.world_kind.clone(),
        instance_id: scope.instance_id,
        instance_scope_id: scope.instance_id.unwrap_or_default(),
        open_world_scene_name: scope.open_world_scene_name.clone(),
        cycle_started_at: now,
        cycle_ends_at_micros: timestamp_to_micros(cycle_ends_at),
        activation,
    });
}

/// Tick gate: the dungeon players a trap tick could possibly involve. An empty
/// result is the whole-phase early out — no snapshot set is built, no arming
/// scan runs, and nothing but the post-tick expiry touches the trap tables.
pub(crate) fn collect_world_trap_tick_players(ctx: &ReducerContext) -> Vec<Identity> {
    if trap_manifest().traps.is_empty() {
        return Vec::new();
    }
    dungeon_player_identities(ctx)
}

/// Post-tick maintenance, beside `expire_world_obstacles`: a cycle that ran out
/// while the dungeon emptied still gets its row (and its hit ledger) reclaimed.
pub(crate) fn expire_world_traps(ctx: &ReducerContext, now: Timestamp) {
    expire_due_trap_states(ctx, now);
}

fn expire_due_trap_states(ctx: &ReducerContext, now: Timestamp) {
    let due: Vec<WorldTrapState> = ctx
        .db
        .world_trap_state()
        .cycle_ends_at_micros()
        .filter(..=timestamp_to_micros(now))
        .collect();
    for state in due {
        delete_trap_state(ctx, &state);
    }
}

fn delete_trap_state(ctx: &ReducerContext, state: &WorldTrapState) {
    ctx.db
        .world_trap_activation_hit()
        .trap_state_id()
        .delete(&state.trap_state_id);
    ctx.db
        .world_trap_state()
        .trap_state_id()
        .delete(state.trap_state_id.clone());
}

fn dungeon_player_identities(ctx: &ReducerContext) -> Vec<Identity> {
    ctx.db
        .player_state()
        .iter()
        .filter(|state| state.alive)
        .map(|state| state.player_id)
        .filter(|identity| {
            matches!(
                resolve_player_world_context(ctx, *identity),
                Some(ResolvedWorldContext::Open(scene))
                    if scene.eq_ignore_ascii_case(RANDOM_DUNGEON_SCENE_NAME))
        })
        .collect()
}

/// Every actor a live hazard may damage: dungeon players plus dungeon NPCs.
/// The snapshot set is world-agnostic, so this is what keeps a trap in the
/// dungeon from reaching an actor standing at the same coordinates elsewhere.
fn dungeon_scope_actor_identities(ctx: &ReducerContext, players: &[Identity]) -> HashSet<Identity> {
    let mut actors: HashSet<Identity> = players.iter().copied().collect();
    for npc in ctx.db.npc_instance().iter() {
        if npc.world_kind == WORLD_KIND_OPEN
            && npc
                .open_world_scene_name
                .eq_ignore_ascii_case(RANDOM_DUNGEON_SCENE_NAME)
        {
            actors.insert(npc.identity);
        }
    }
    actors
}

fn open_random_dungeon_scope() -> TrapScope {
    TrapScope {
        world_kind: WORLD_KIND_OPEN.to_string(),
        instance_id: None,
        open_world_scene_name: RANDOM_DUNGEON_SCENE_NAME.to_string(),
    }
}

fn trap_definitions_in_scope(scope: &TrapScope) -> impl Iterator<Item = &'static TrapDefinition> {
    let in_random_dungeon = scope.world_kind == WORLD_KIND_OPEN
        && scope
            .open_world_scene_name
            .eq_ignore_ascii_case(RANDOM_DUNGEON_SCENE_NAME);
    trap_manifest().traps.iter().filter(move |trap| {
        in_random_dungeon && trap.world_definition_key == RANDOM_DUNGEON_WORLD_KEY
    })
}

fn trap_state_id(definition: &TrapDefinition, scope: &TrapScope) -> String {
    match scope.instance_id {
        Some(instance_id) => format!("INSTANCE:{}:{}", instance_id, definition.trap_definition_id),
        None => format!(
            "OPEN:{}:{}",
            scope.open_world_scene_name, definition.trap_definition_id
        ),
    }
}

// ---------------------------------------------------------------------------
// Phase and geometry (pure)
// ---------------------------------------------------------------------------

fn elapsed_ms(from: Timestamp, to: Timestamp) -> i64 {
    (timestamp_to_micros(to) - timestamp_to_micros(from)) / 1_000
}

/// Clip-relative time. Negative values are the telegraph window: the row
/// exists, the clip has not started, and nothing is hazardous yet.
fn clip_time_ms(phase_ms: i64, trigger_delay_ms: u64) -> i64 {
    phase_ms - trigger_delay_ms as i64
}

fn hazard_is_live(clip_ms: i64, profile: &TrapProfileDefinition) -> bool {
    clip_ms >= profile.hazard_start_ms as i64 && clip_ms <= profile.hazard_end_ms as i64
}

/// Piecewise-linear hazard-centre offset, clamped outside the authored range.
/// This is what makes "the saw hits you when the saw is on you" true instead of
/// "the whole lane is lethal for two seconds".
fn hazard_offset_at(track: &[TrapTrackKey], clip_ms: f32) -> [f32; 3] {
    let Some(first) = track.first() else {
        return [0.0, 0.0, 0.0];
    };
    let last = track[track.len() - 1];
    if clip_ms <= first.t_ms as f32 {
        return [first.offset.x, first.offset.y, first.offset.z];
    }
    if clip_ms >= last.t_ms as f32 {
        return [last.offset.x, last.offset.y, last.offset.z];
    }

    for window in track.windows(2) {
        let (previous, next) = (window[0], window[1]);
        if clip_ms > next.t_ms as f32 {
            continue;
        }
        let span = (next.t_ms as f32) - (previous.t_ms as f32);
        let blend = if span <= 0.0 {
            0.0
        } else {
            ((clip_ms - previous.t_ms as f32) / span).clamp(0.0, 1.0)
        };
        return [
            previous.offset.x + (next.offset.x - previous.offset.x) * blend,
            previous.offset.y + (next.offset.y - previous.offset.y) * blend,
            previous.offset.z + (next.offset.z - previous.offset.z) * blend,
        ];
    }
    [last.offset.x, last.offset.y, last.offset.z]
}

fn trap_obb(
    definition: &TrapDefinition,
    volume: TrapVolumeDefinition,
    track_offset: [f32; 3],
) -> TrapObb {
    let yaw_radians = definition.yaw_degrees.to_radians();
    let local = [
        volume.center.x + track_offset[0],
        volume.center.y + track_offset[1],
        volume.center.z + track_offset[2],
    ];
    let cosine = yaw_radians.cos();
    let sine = yaw_radians.sin();
    TrapObb {
        center: [
            definition.origin.x + local[0] * cosine + local[2] * sine,
            definition.origin.y + local[1],
            definition.origin.z - local[0] * sine + local[2] * cosine,
        ],
        half_extents: [
            volume.size.x * 0.5,
            volume.size.y * 0.5,
            volume.size.z * 0.5,
        ],
        yaw_radians,
    }
}

fn obb_overlaps_actor(obb: TrapObb, actor: &CombatActorSnapshot) -> bool {
    let radius = actor.hit_radius.max(0.0);
    let half_height = actor.hit_height.max(0.0) * 0.5;
    let center = [actor.pos_x, actor.pos_y + half_height, actor.pos_z];
    if !center.iter().all(|value| value.is_finite()) {
        return false;
    }

    let dx = center[0] - obb.center[0];
    let dz = center[2] - obb.center[2];
    let cosine = obb.yaw_radians.cos();
    let sine = obb.yaw_radians.sin();
    let local = [
        dx * cosine - dz * sine,
        center[1] - obb.center[1],
        dx * sine + dz * cosine,
    ];
    let half = [
        obb.half_extents[0] + radius,
        obb.half_extents[1] + half_height,
        obb.half_extents[2] + radius,
    ];
    (0..3).all(|axis| local[axis].abs() <= half[axis])
}

fn stack_policy_from_wire(value: &str) -> StackPolicy {
    match value {
        "ADD_STACK_REFRESH" => StackPolicy::AddStackRefresh,
        "ADD_STACK_ESCALATING_DECAY" => StackPolicy::AddStackEscalatingDecay,
        "REPLACE_IF_STRONGER" => StackPolicy::ReplaceIfStronger,
        "IGNORE_IF_WEAKER" => StackPolicy::IgnoreIfWeaker,
        _ => StackPolicy::Refresh,
    }
}

// ---------------------------------------------------------------------------
// Manifests
// ---------------------------------------------------------------------------

fn trap_manifest() -> &'static TrapManifest {
    static MANIFEST: OnceLock<TrapManifest> = OnceLock::new();
    MANIFEST.get_or_init(|| {
        parse_trap_manifest(TRAP_MANIFEST_JSON)
            .unwrap_or_else(|error| panic!("Invalid random dungeon trap manifest: {error}"))
    })
}

fn trap_profile_manifest() -> &'static TrapProfileManifest {
    static MANIFEST: OnceLock<TrapProfileManifest> = OnceLock::new();
    MANIFEST.get_or_init(|| {
        parse_trap_profile_manifest(TRAP_PROFILE_MANIFEST_JSON)
            .unwrap_or_else(|error| panic!("Invalid world trap profile manifest: {error}"))
    })
}

fn trap_definition(trap_definition_id: &str) -> Option<&'static TrapDefinition> {
    let normalized = normalize_id(trap_definition_id);
    trap_manifest()
        .traps
        .iter()
        .find(|trap| trap.trap_definition_id == normalized)
}

fn trap_profile(profile_id: &str) -> Option<&'static TrapProfileDefinition> {
    let normalized = normalize_id(profile_id);
    trap_profile_manifest()
        .profiles
        .iter()
        .find(|profile| profile.profile_id == normalized)
}

fn parse_trap_manifest(json: &str) -> Result<TrapManifest, String> {
    let mut manifest: TrapManifest =
        serde_json::from_str(json).map_err(|error| error.to_string())?;
    manifest.world_definition_key = normalize_id(manifest.world_definition_key.as_str());
    if manifest.schema_version != 1 {
        return Err(format!(
            "unsupported schema_version {}",
            manifest.schema_version
        ));
    }
    if manifest.world_definition_key != RANDOM_DUNGEON_WORLD_KEY {
        return Err(format!(
            "unexpected world_definition_key '{}'",
            manifest.world_definition_key
        ));
    }

    // An empty trap list is legitimate: it is exactly the paired state of a
    // dungeon rebuilt with the trap pass disabled.
    let mut ids = HashSet::new();
    for trap in &mut manifest.traps {
        trap.trap_definition_id = normalize_id(trap.trap_definition_id.as_str());
        trap.world_definition_key = normalize_id(trap.world_definition_key.as_str());
        trap.trap_profile_id = normalize_id(trap.trap_profile_id.as_str());
        if trap.trap_definition_id.is_empty() || !ids.insert(trap.trap_definition_id.clone()) {
            return Err(format!(
                "trap_definition_id '{}' is empty or duplicated",
                trap.trap_definition_id
            ));
        }
        if trap.world_definition_key != manifest.world_definition_key {
            return Err(format!(
                "trap '{}' has mismatched world_definition_key '{}'",
                trap.trap_definition_id, trap.world_definition_key
            ));
        }
        if trap.definition_version == 0
            || trap.footprint_cells == 0
            || !vector_is_finite(trap.origin)
            || !trap.yaw_degrees.is_finite()
            || trap.trap_profile_id.is_empty()
        {
            return Err(format!(
                "trap '{}' has invalid placement, footprint, or profile",
                trap.trap_definition_id
            ));
        }
    }
    Ok(manifest)
}

fn parse_trap_profile_manifest(json: &str) -> Result<TrapProfileManifest, String> {
    let mut manifest: TrapProfileManifest =
        serde_json::from_str(json).map_err(|error| error.to_string())?;
    if manifest.schema_version != 1 {
        return Err(format!(
            "unsupported schema_version {}",
            manifest.schema_version
        ));
    }
    if manifest.profiles.is_empty() {
        return Err("profiles must not be empty".to_string());
    }

    let mut ids = HashSet::new();
    for profile in &mut manifest.profiles {
        profile.profile_id = normalize_id(profile.profile_id.as_str());
        profile.trigger_kind = normalize_id(profile.trigger_kind.as_str());
        if profile.profile_id.is_empty() || !ids.insert(profile.profile_id.clone()) {
            return Err(format!(
                "profile_id '{}' is empty or duplicated",
                profile.profile_id
            ));
        }
        if profile.trigger_kind != TRIGGER_KIND_PROXIMITY
            && profile.trigger_kind != TRIGGER_KIND_ALWAYS
        {
            return Err(format!(
                "profile '{}' has unknown trigger_kind '{}'",
                profile.profile_id, profile.trigger_kind
            ));
        }
        if profile.cycle_ms == 0 {
            return Err(format!("profile '{}' has a zero cycle", profile.profile_id));
        }
        if profile.hazard_start_ms > profile.hazard_end_ms
            || profile.hazard_end_ms > profile.cycle_ms
        {
            return Err(format!(
                "profile '{}' has a hazard window outside its cycle",
                profile.profile_id
            ));
        }
        if !volume_is_valid(profile.trigger_volume) || !volume_is_valid(profile.hazard_volume) {
            return Err(format!(
                "profile '{}' has a non-finite or degenerate volume",
                profile.profile_id
            ));
        }
        if profile.on_hit.is_empty() {
            return Err(format!(
                "profile '{}' applies no effects",
                profile.profile_id
            ));
        }

        let mut previous_t_ms: Option<u32> = None;
        for key in &profile.hazard_track {
            if !vector_is_finite(key.offset) {
                return Err(format!(
                    "profile '{}' has a non-finite hazard track offset",
                    profile.profile_id
                ));
            }
            if previous_t_ms.is_some_and(|previous| key.t_ms <= previous) {
                return Err(format!(
                    "profile '{}' has a hazard track that is not strictly increasing",
                    profile.profile_id
                ));
            }
            previous_t_ms = Some(key.t_ms);
        }

        for entry in &mut profile.on_hit {
            entry.effect = normalize_id(entry.effect.as_str());
            entry.damage_type = normalize_id(entry.damage_type.as_str());
            entry.stack_group = normalize_id(entry.stack_group.as_str());
            entry.stack_policy = normalize_id(entry.stack_policy.as_str());
            match entry.effect.as_str() {
                EFFECT_KIND_DAMAGE if entry.amount > 0 => {}
                EFFECT_KIND_DOT
                    if entry.tick_amount > 0
                        && entry.tick_interval_ms > 0
                        && entry.duration_ms > 0
                        && !entry.stack_group.is_empty() => {}
                _ => {
                    return Err(format!(
                        "profile '{}' has an invalid '{}' on_hit entry",
                        profile.profile_id, entry.effect
                    ));
                }
            }
        }
    }

    // Every placed trap must resolve to a profile, or the dungeon would ship a
    // trap that can never fire.
    let profile_ids: HashMap<&str, ()> = manifest
        .profiles
        .iter()
        .map(|profile| (profile.profile_id.as_str(), ()))
        .collect();
    for trap in &trap_manifest().traps {
        if !profile_ids.contains_key(trap.trap_profile_id.as_str()) {
            return Err(format!(
                "trap '{}' references unknown trap profile '{}'",
                trap.trap_definition_id, trap.trap_profile_id
            ));
        }
    }
    Ok(manifest)
}

fn normalize_id(value: &str) -> String {
    value.trim().to_ascii_uppercase()
}

fn vector_is_finite(value: ManifestVector3) -> bool {
    value.x.is_finite() && value.y.is_finite() && value.z.is_finite()
}

fn volume_is_valid(volume: TrapVolumeDefinition) -> bool {
    vector_is_finite(volume.center)
        && vector_is_finite(volume.size)
        && volume.size.x > 0.0
        && volume.size.y > 0.0
        && volume.size.z > 0.0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snapshot(pos: [f32; 3]) -> CombatActorSnapshot {
        CombatActorSnapshot {
            player_id: Identity::ZERO,
            alive: true,
            pos_x: pos[0],
            pos_y: pos[1],
            pos_z: pos[2],
            facing_yaw: 0.0,
            grounded: true,
            hit_radius: 0.28,
            hit_height: 1.8,
            last_processed_tick: 0,
        }
    }

    fn definition(yaw_degrees: f32) -> TrapDefinition {
        TrapDefinition {
            trap_definition_id: "RANDOM_DUNGEON:TRAP:SPIKES:0:0:0".to_string(),
            world_definition_key: RANDOM_DUNGEON_WORLD_KEY.to_string(),
            trap_profile_id: "TRAP_SPIKES".to_string(),
            origin: ManifestVector3 {
                x: 10.0,
                y: 4.0,
                z: -6.0,
            },
            yaw_degrees,
            footprint_cells: 1,
            definition_version: 1,
        }
    }

    fn volume(center: [f32; 3], size: [f32; 3]) -> TrapVolumeDefinition {
        TrapVolumeDefinition {
            center: ManifestVector3 {
                x: center[0],
                y: center[1],
                z: center[2],
            },
            size: ManifestVector3 {
                x: size[0],
                y: size[1],
                z: size[2],
            },
        }
    }

    fn track(keys: &[(u32, [f32; 3])]) -> Vec<TrapTrackKey> {
        keys.iter()
            .map(|(t_ms, offset)| TrapTrackKey {
                t_ms: *t_ms,
                offset: ManifestVector3 {
                    x: offset[0],
                    y: offset[1],
                    z: offset[2],
                },
            })
            .collect()
    }

    #[test]
    fn authored_manifests_parse_and_every_profile_resolves() {
        let traps = parse_trap_manifest(TRAP_MANIFEST_JSON).expect("trap manifest");
        let profiles =
            parse_trap_profile_manifest(TRAP_PROFILE_MANIFEST_JSON).expect("trap profiles");
        assert_eq!(profiles.profiles.len(), 4);
        let ids: HashSet<&str> = profiles
            .profiles
            .iter()
            .map(|profile| profile.profile_id.as_str())
            .collect();
        assert!(ids.contains("TRAP_SPIKES"));
        assert!(ids.contains("TRAP_SAW_SWEEP"));
        for trap in &traps.traps {
            assert!(ids.contains(trap.trap_profile_id.as_str()));
        }
    }

    #[test]
    fn only_spikes_take_a_reaction_window_and_only_saws_bleed() {
        let profiles =
            parse_trap_profile_manifest(TRAP_PROFILE_MANIFEST_JSON).expect("trap profiles");
        for profile in &profiles.profiles {
            let bleed = profile
                .on_hit
                .iter()
                .find(|entry| entry.effect == EFFECT_KIND_DOT);
            if profile.profile_id == "TRAP_SPIKES" {
                assert_eq!(profile.trigger_delay_ms, 350);
                assert!(bleed.is_none(), "spikes are one flat hit, not a bleed");
            } else {
                assert_eq!(profile.trigger_delay_ms, 0);
                let bleed = bleed.expect("saws trade impact for a stacking bleed");
                assert_eq!(bleed.max_stacks, 10);
                assert_eq!(
                    stack_policy_from_wire(bleed.stack_policy.as_str()),
                    StackPolicy::AddStackEscalatingDecay
                );
                assert_eq!(bleed.dispel_types, vec![StatusDispelType::Bleed]);
            }
        }
    }

    #[test]
    fn clip_time_is_negative_through_the_whole_telegraph_window() {
        assert_eq!(clip_time_ms(0, 350), -350);
        assert_eq!(clip_time_ms(349, 350), -1);
        assert_eq!(clip_time_ms(350, 350), 0);
        assert_eq!(clip_time_ms(530, 350), 180);
    }

    #[test]
    fn spike_hazard_is_live_only_during_the_eruption() {
        let mut profile = parse_trap_profile_manifest(TRAP_PROFILE_MANIFEST_JSON)
            .expect("trap profiles")
            .profiles
            .into_iter()
            .find(|profile| profile.profile_id == "TRAP_SPIKES")
            .expect("spike profile");
        profile.one_hit_per_activation = true;

        assert!(!hazard_is_live(
            clip_time_ms(0, profile.trigger_delay_ms),
            &profile
        ));
        assert!(!hazard_is_live(
            clip_time_ms(529, profile.trigger_delay_ms),
            &profile
        ));
        assert!(hazard_is_live(
            clip_time_ms(530, profile.trigger_delay_ms),
            &profile
        ));
        assert!(hazard_is_live(
            clip_time_ms(580, profile.trigger_delay_ms),
            &profile
        ));
        assert!(!hazard_is_live(
            clip_time_ms(581, profile.trigger_delay_ms),
            &profile
        ));
        assert!(!hazard_is_live(
            clip_time_ms(2550, profile.trigger_delay_ms),
            &profile
        ));
    }

    #[test]
    fn hazard_track_interpolates_and_clamps() {
        let keys = track(&[(250, [0.0, 0.0, 2.0]), (2133, [0.0, 0.0, -2.0])]);
        assert_eq!(hazard_offset_at(&keys, 0.0)[2], 2.0);
        assert_eq!(hazard_offset_at(&keys, 250.0)[2], 2.0);
        assert_eq!(hazard_offset_at(&keys, 3000.0)[2], -2.0);
        let midpoint = hazard_offset_at(&keys, (250.0 + 2133.0) * 0.5)[2];
        assert!(midpoint.abs() < 0.001, "midpoint was {midpoint}");
    }

    #[test]
    fn empty_track_is_a_stationary_hazard() {
        assert_eq!(hazard_offset_at(&[], 900.0), [0.0, 0.0, 0.0]);
    }

    #[test]
    fn hazard_follows_the_track_instead_of_flooding_the_lane() {
        let trap = definition(0.0);
        let keys = track(&[(250, [0.0, 0.0, 2.0]), (2133, [0.0, 0.0, -2.0])]);
        let hazard = volume([0.0, 0.7, 0.0], [0.9, 1.4, 2.0]);
        let near_start = trap_obb(&trap, hazard, hazard_offset_at(&keys, 250.0));
        let near_end = trap_obb(&trap, hazard, hazard_offset_at(&keys, 2133.0));

        // Standing at the far end of the lane while the blade is at the near
        // end must not connect; the same spot connects once the blade arrives.
        let actor = snapshot([10.0, 4.0, -8.0]);
        assert!(!obb_overlaps_actor(near_start, &actor));
        assert!(obb_overlaps_actor(near_end, &actor));
    }

    #[test]
    fn yaw_rotates_the_hazard_with_the_placed_trap() {
        let keys = track(&[(0, [0.0, 0.0, 2.0])]);
        let offset = hazard_offset_at(&keys, 0.0);
        let hazard = volume([0.0, 0.7, 0.0], [0.9, 1.4, 2.0]);

        let facing_north = trap_obb(&definition(0.0), hazard, offset);
        assert!((facing_north.center[2] - (-4.0)).abs() < 0.001);
        assert!((facing_north.center[0] - 10.0).abs() < 0.001);

        let facing_east = trap_obb(&definition(90.0), hazard, offset);
        assert!((facing_east.center[0] - 12.0).abs() < 0.001);
        assert!((facing_east.center[2] - (-6.0)).abs() < 0.001);
    }

    #[test]
    fn a_full_cell_spike_field_catches_a_capsule_anywhere_on_the_plate() {
        let trap = definition(0.0);
        let hazard = volume([0.0, 0.6, 0.0], [4.0, 1.2, 4.0]);
        let obb = trap_obb(&trap, hazard, [0.0, 0.0, 0.0]);
        assert!(obb_overlaps_actor(obb, &snapshot([10.0, 4.0, -6.0])));
        assert!(obb_overlaps_actor(obb, &snapshot([11.9, 4.0, -4.1])));
        // Two metres clear of the plate edge is safe.
        assert!(!obb_overlaps_actor(obb, &snapshot([14.5, 4.0, -6.0])));
    }

    #[test]
    fn a_hazard_at_chest_height_still_reaches_a_standing_capsule() {
        let trap = definition(0.0);
        let hazard = volume([0.0, 1.39, 0.0], [2.2, 0.9, 2.2]);
        let obb = trap_obb(&trap, hazard, [0.0, 0.0, 0.0]);
        assert!(obb_overlaps_actor(obb, &snapshot([10.0, 4.0, -6.0])));
        // A floor two levels down is out of reach.
        assert!(!obb_overlaps_actor(obb, &snapshot([10.0, 0.0, -6.0])));
    }

    #[test]
    fn stack_policy_wire_values_round_trip() {
        assert_eq!(
            stack_policy_from_wire("ADD_STACK_REFRESH"),
            StackPolicy::AddStackRefresh
        );
        assert_eq!(
            stack_policy_from_wire("ADD_STACK_ESCALATING_DECAY"),
            StackPolicy::AddStackEscalatingDecay
        );
        assert_eq!(stack_policy_from_wire("REFRESH"), StackPolicy::Refresh);
        assert_eq!(stack_policy_from_wire("nonsense"), StackPolicy::Refresh);
    }

    #[test]
    fn manifest_parse_rejects_a_hazard_window_outside_its_cycle() {
        let json = r#"{
          "schema_version": 1,
          "profiles": [{
            "profile_id": "BAD",
            "trigger_kind": "PROXIMITY",
            "trigger_delay_ms": 0,
            "cycle_ms": 1000,
            "hazard_start_ms": 100,
            "hazard_end_ms": 2000,
            "rearm_ms": 0,
            "trigger_volume": {"center":{"x":0,"y":0,"z":0},"size":{"x":1,"y":1,"z":1}},
            "hazard_volume": {"center":{"x":0,"y":0,"z":0},"size":{"x":1,"y":1,"z":1}},
            "hazard_track": [],
            "on_hit": [{"effect":"DAMAGE","amount":1,"damage_type":"PHYSICAL","tick_amount":0,
                        "tick_interval_ms":0,"duration_ms":0,"stack_group":"","max_stacks":1,
                        "stack_policy":"REFRESH"}],
            "one_hit_per_activation": true
          }]
        }"#;
        assert!(parse_trap_profile_manifest(json).is_err());
    }

    #[test]
    fn manifest_parse_rejects_an_unknown_field() {
        let json = r#"{
          "schema_version": 1,
          "world_definition_key": "RANDOM_DUNGEON",
          "traps": [{
            "trap_definition_id": "X",
            "world_definition_key": "RANDOM_DUNGEON",
            "trap_profile_id": "TRAP_SPIKES",
            "origin": {"x":0,"y":0,"z":0},
            "yaw_degrees": 0,
            "footprint_cells": 1,
            "definition_version": 1,
            "surprise": true
          }]
        }"#;
        assert!(parse_trap_manifest(json).is_err());
    }
}
