#!/usr/bin/env python3
"""Generate shared UI design tokens for the Arena UI art direction (v2).

Source of truth: "Arena UI Art Direction & Design System" (repo root PDF) and
its master style sheet image. This script encodes that palette/type scale as
deterministic values and emits identical custom-property blocks for the two
consumers of the design system:

  Assets/Arena/Resources/UI/Toolkit/tokens.uss   (game USS, via ArenaTheme.tss)
  docs/ui-prototypes/tokens.css                  (web prototype specs)

The legacy uGUI palette (ArenaUiTheme.cs Canon*) is a separate, older system;
new UI Toolkit surfaces use these tokens instead.

Run after editing the token table:

  ops/gen_ui_tokens.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_USS = REPO / "Assets/Arena/Resources/UI/Toolkit/tokens.uss"
OUT_CSS = REPO / "docs/ui-prototypes/tokens.css"

TOKENS: list[tuple[str, str] | str] = [
    "materials — neutrals & metals (decoration lives here, never gameplay color)",
    ("--arena-charcoal", "#17181B"),        # window/leather fill base
    ("--arena-well", "#101114"),            # recessed interiors (slots, tracks)
    ("--arena-iron", "#26282C"),            # dark forged iron
    ("--arena-gunmetal", "#3B3E44"),        # frame mid-tone
    ("--arena-steel", "#6E747D"),           # tempered steel
    ("--arena-steel-bright", "#A9AFB8"),    # polished bevel highlight
    ("--arena-leather", "#221B17"),         # aged leather fill
    ("--arena-leather-red", "#41201B"),     # embossed maroon leather (header plate)
    ("--arena-brass", "#8A6B3A"),           # brass trim
    ("--arena-ember", "#C58F2A"),           # ember gold — the accent of value
    ("--arena-ember-bright", "#E4B34A"),    # hover/lit ember
    ("--arena-ember-deep", "#96691C"),      # pressed ember
    "text — parchment on charcoal, gold reserved for titles/value",
    ("--arena-text", "#E7E1D3"),
    ("--arena-text-muted", "#A89F8D"),
    ("--arena-text-dim", "#78705F"),
    ("--arena-gold-text", "#D9B56A"),
    ("--arena-on-ember", "#1E1608"),        # label on ember fills
    "hairlines & veils",
    ("--arena-hairline", "rgba(231, 225, 211, 0.10)"),
    ("--arena-hairline-strong", "rgba(231, 225, 211, 0.22)"),
    ("--arena-veil", "rgba(6, 6, 8, 0.74)"),
    "gameplay colors — mechanics only, never decoration",
    ("--arena-danger", "#A32C22"),
    ("--arena-danger-bright", "#C43A2C"),
    ("--arena-heal", "#3F7D45"),
    ("--arena-frost", "#3C6DB0"),
    ("--arena-arcane", "#7B4FA5"),
    ("--arena-rarity-common", "#C9CCD1"),
    ("--arena-rarity-uncommon", "#4C9B4F"),
    ("--arena-rarity-rare", "#4477C8"),
    ("--arena-rarity-epic", "#8A55BB"),
    ("--arena-rarity-legendary", "#C97A2B"),
    "type scale — Cinzel (display small-caps), Alegreya (body)",
    ("--arena-font-title", "20px"),
    ("--arena-font-section", "15px"),
    ("--arena-font-button", "14px"),
    ("--arena-font-body", "14px"),
    ("--arena-font-small", "12px"),
    "shared metrics",
    ("--arena-button-height", "36px"),
    ("--arena-row-height", "36px"),
    ("--arena-content-pad", "20px"),
]


def render() -> str:
    lines = [
        "/* GENERATED by ops/gen_ui_tokens.py — do not hand-edit.",
        " * Source of truth: Arena UI Art Direction & Design System (v2).",
        " * Same variables ship to web prototypes (tokens.css) and game USS (tokens.uss). */",
        ":root {",
    ]
    for entry in TOKENS:
        if isinstance(entry, str):
            lines.append(f"    /* {entry} */")
        else:
            name, value = entry
            lines.append(f"    {name}: {value};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    body = render()
    for out in (OUT_USS, OUT_CSS):
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body)
        print(f"wrote {out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
