//! Spells - Minimal server-authoritative spell logic

use std::collections::HashSet;
use std::time::Duration;

use spacetimedb::{reducer, table, Identity, ReducerContext, Table, Timestamp};

use crate::action_ids::AuthoredActionId;
use crate::progression::{
    action_id_is_selectable_action_bar_action, active_selectable_ability_for_authored_action,
    movement_delivery_for_ability_id, movement_delivery_for_action_id,
};

#[allow(unused_imports)]
use crate::inventory::item_spell as _;

// Import accessor traits (generated by #[table] macro, needed for ctx.db.table_name())
#[allow(unused_imports)]
use crate::spells::active_bespoke_spell as _;
#[allow(unused_imports)]
use crate::spells::active_cast as _;
#[allow(unused_imports)]
use crate::spells::capacitor_state as _;
#[allow(unused_imports)]
use crate::spells::cast_prediction_correlation as _;
#[allow(unused_imports)]
use crate::spells::channel_cast_runtime as _;
#[allow(unused_imports)]
use crate::spells::global_cooldown as _;
#[allow(unused_imports)]
use crate::spells::pending_area_impact as _;
#[allow(unused_imports)]
use crate::spells::pending_cast_cancel as _;
#[allow(unused_imports)]
use crate::spells::pending_cast_request as _;
#[allow(unused_imports)]
use crate::spells::player_known_spell as _;
#[allow(unused_imports)]
use crate::spells::recall_slot as _;
#[allow(unused_imports)]
use crate::spells::special_movement_runtime as _;
#[allow(unused_imports)]
use crate::spells::spell_cooldown as _;
#[allow(unused_imports)]
use crate::spells::spell_counter as _;
#[allow(unused_imports)]
use crate::spells::spell_definition as _;

mod casting;
mod catalog;
mod cooldowns;
mod events;
mod manifest;
mod necro_prison;
mod sanctuary;
mod simulation;

use manifest::spell_definitions;

pub(crate) use crate::combat::scene_query::aoe_hits_player;
#[cfg(test)]
pub(crate) use casting::special_movement_uses_air_path_with_ground;
pub(crate) use casting::{
    approach_line_contact_point_xz, bake_linear_special_movement, begin_active_cast,
    begin_instant_special_movement, begin_parabolic_arc_special_movement, begin_special_movement,
    begin_special_movement_with_facing_policy, cast_spell_for_server_actor, clear_active_cast,
    clear_recall_slot, contact_distance_from_radii, fire_chain_reaction_spell,
    fizzle_active_cast_for_interrupt, has_due_pending_area_impacts,
    horizontal_movement_duration_ms, is_externally_imposed_movement_kind,
    movement_delivery_destination, resolve_pending_area_impacts, resolve_pending_casts,
    resolve_special_movement_y, resolved_primary_resource_cost_for_amount,
    special_movement_uses_air_path, tick_active_casts, tick_persistent_areas,
    validate_movement_delivery_target, KNOCKBACK_MOVEMENT_KIND,
    SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK, SPECIAL_MOVEMENT_COLLISION_STOP_AT_BLOCK_FIXED_Y,
    SPECIAL_MOVEMENT_FACING_FACE_PATH, SPECIAL_MOVEMENT_FACING_FACE_START,
    STAGGER_SHOVE_MOVEMENT_KIND,
};
pub(crate) use catalog::spell_definition_by_str;
pub(crate) use cooldowns::{
    advance_active_ability_cooldowns, advance_other_movement_ability_cooldowns,
    clear_actor_cooldowns, is_on_cooldown as is_on_spell_cooldown, is_on_global_cooldown,
    is_on_named_cooldown, stamp_global_cooldown_for_duration, stamp_named_cooldown_for_duration,
};
pub(crate) use events::Vec3 as SpellVec3;
pub(crate) use manifest::{
    ImmolationSecondaryTunables, ImpactEffect, NecroPrisonSecondaryTunables,
    SanctuarySecondaryTunables, SpellBehavior, SpellDefinition as SpellRuntimeDefinition, SpellId,
    SpellTargeting, WorldObstacleSecondaryTunables,
};
pub(crate) use necro_prison::{
    clear_necro_prisons_for_owner, expire_necro_prisons, resolve_hostile_necro_prison_movement,
    spawn_necro_prison,
};
pub(crate) use sanctuary::{
    area_overlaps_hostile_sanctuary, clear_sanctuary_zones_for_owner, expire_sanctuary_zones,
    first_hostile_sanctuary_projectile_hit, resolve_hostile_sanctuary_movement,
    spawn_sanctuary_zone,
};
#[allow(unused_imports)]
pub(crate) use simulation::{tick_bespoke_spells, tick_bespoke_spells_with_snapshots};

pub(super) const EVENT_CAST: &str = crate::combat::COMBAT_EVENT_CAST;
pub(super) const EVENT_RELEASE: &str = crate::combat::COMBAT_EVENT_RELEASE;
pub(super) const EVENT_CONTACT: &str = crate::combat::COMBAT_EVENT_CONTACT;
pub(super) const EVENT_IMPACT: &str = crate::combat::COMBAT_EVENT_IMPACT;
pub(super) const EVENT_AREA_IMPACT: &str = crate::combat::COMBAT_EVENT_AREA_IMPACT;
pub(super) const EVENT_FIZZLE: &str = crate::combat::COMBAT_EVENT_FIZZLE;
pub(super) const EVENT_UPDATE: &str = crate::combat::COMBAT_EVENT_UPDATE;

pub(super) fn normalize_vec3(x: f32, y: f32, z: f32) -> Option<(f32, f32, f32)> {
    let len_sq = x * x + y * y + z * z;
    if len_sq <= 0.000001 {
        return None;
    }
    let inv_len = 1.0 / len_sq.sqrt();
    Some((x * inv_len, y * inv_len, z * inv_len))
}

// Long-lived bespoke spell simulations only. Generic projectile spells use
// ActiveCombatProjectile; instant/channel bespoke spells resolve at cast time.
#[table(accessor = active_bespoke_spell)]
pub struct ActiveBespokeSpell {
    #[primary_key]
    pub spell_id: String,
    pub kind: String,
    pub ability_id: String,
    pub caster: Identity,
    pub target: Identity,
    pub origin_x: f32,
    pub origin_y: f32,
    pub origin_z: f32,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub dir_x: f32,
    pub dir_y: f32,
    pub dir_z: f32,
    pub speed: f32,
    pub max_distance: f32,
    pub traveled: f32,
    pub age: f32,
    pub lifetime: f32,
    pub update_accum: f32,
    pub created_at: Timestamp,
}

#[table(accessor = pending_area_impact)]
pub struct PendingAreaImpact {
    #[primary_key]
    #[auto_inc]
    pub impact_id: u64,
    pub caster: Identity,
    pub spell_id: String,
    pub kind: String,
    pub ability_id: String,
    pub origin_x: f32,
    pub origin_y: f32,
    pub origin_z: f32,
    pub area_x: f32,
    pub area_y: f32,
    pub area_z: f32,
    pub facing_yaw: f32,
    pub impact_at: Timestamp,
    /// S10: the press's clamped attacker-view delay, frozen at cast time. The
    /// delayed-sweep resolve rewinds each candidate victim's membership by this
    /// much (mirrors PendingMeleeImpact.view_delay_micros / melee D2);
    /// 0 = present-time (no report, switch OFF, or a targeted-cast control).
    pub view_delay_micros: i64,
    #[index(btree)]
    pub resolve_at_micros: i64,
}

#[table(accessor = active_persistent_area, public)]
#[derive(Clone)]
pub struct ActivePersistentArea {
    #[primary_key]
    pub key: String,
    #[index(btree)]
    pub caster: Identity,
    /// Non-zero for actor-following fields; zero for fixed point-targeted fields.
    pub target: Identity,
    /// Fixed world-space center for point-targeted fields. Actor-following fields
    /// retain their cast-time center here for diagnostics while resolving from `target`.
    pub area_x: f32,
    pub area_y: f32,
    pub area_z: f32,
    pub spell_instance_id: String,
    pub kind: String,
    pub ability_id: String,
    pub activated_at: Timestamp,
    pub expires_at: Timestamp,
    pub next_pulse_at: Timestamp,
    /// Cast-time source and facing are retained so reconnecting clients can
    /// reconstruct authored directional field VFX deterministically. Defaults
    /// keep existing persistent-area rows compatible during data-preserving
    /// schema upgrades.
    #[default(0.0f32)]
    pub origin_x: f32,
    #[default(0.0f32)]
    pub origin_y: f32,
    #[default(0.0f32)]
    pub origin_z: f32,
    #[default(0.0f32)]
    pub dir_x: f32,
    #[default(0.0f32)]
    pub dir_y: f32,
    #[default(0.0f32)]
    pub dir_z: f32,
}

#[table(accessor = active_cast, public)]
#[derive(Clone)]
pub struct ActiveCast {
    #[primary_key]
    pub caster: Identity,
    pub cast_id: String,
    pub ability_id: String,
    pub kind: String,
    pub target_id: String,
    pub aim_x: f32,
    pub aim_y: f32,
    pub aim_z: f32,
    pub started_at: Timestamp,
    pub ends_at: Timestamp,
    pub cast_authored_input_tick: u32,
    pub charge_count: u32,
    pub max_charge_count: u32,
    pub predicted_cast_id: String,
    pub client_action_seq: u64,
}

#[table(accessor = pending_cast_request)]
#[derive(Clone)]
pub struct PendingCastRequest {
    #[primary_key]
    pub caster: Identity,
    pub spell_id: String,
    pub target_id: String,
    pub aim_x: f32,
    pub aim_y: f32,
    pub aim_z: f32,
    pub cast_input_tick: u32,
    pub cast_pos_x: f32,
    pub cast_pos_y: f32,
    pub cast_pos_z: f32,
    pub cast_yaw: f32,
    pub predicted_cast_id: String,
    pub client_action_seq: u64,
    pub received_at: Timestamp,
    #[index(btree)]
    pub received_at_micros: i64,
}

#[table(accessor = pending_cast_cancel)]
#[derive(Clone)]
pub struct PendingCastCancel {
    #[primary_key]
    pub cancel_key: String,
    pub caster: Identity,
    pub predicted_cast_id: String,
    pub client_action_seq: u64,
    pub reason: String,
    pub received_at: Timestamp,
    #[index(btree)]
    pub expires_at_micros: i64,
}

#[table(accessor = cast_prediction_correlation)]
#[derive(Clone)]
pub struct CastPredictionCorrelation {
    // One row per caster by design. This mirrors ActiveCast's caster primary key:
    // the game supports at most one active cast per caster.
    #[primary_key]
    pub caster: Identity,
    pub action_instance_id: String,
    pub predicted_cast_id: String,
    pub client_action_seq: u64,
    pub received_at: Timestamp,
    #[index(btree)]
    pub expires_at_micros: i64,
}

#[table(accessor = special_movement_runtime, public)]
#[derive(Clone)]
pub struct SpecialMovementRuntime {
    #[primary_key]
    pub owner: Identity,
    pub runtime_id: String,
    pub kind: String,
    pub path_mode: String,
    pub started_at: Timestamp,
    pub duration_ms: u64,
    pub start_x: f32,
    pub start_y: f32,
    pub start_z: f32,
    pub end_x: f32,
    pub end_y: f32,
    pub end_z: f32,
    pub arc_height: f32,
    pub facing_yaw_start: f32,
    pub facing_policy: String,
    pub collision_policy: String,
    pub resolve_policy: String,
}

#[table(accessor = channel_cast_runtime)]
#[derive(Clone)]
pub struct ChannelCastRuntime {
    #[primary_key]
    pub caster: Identity,
    pub spell_instance_id: String,
    pub last_update_at: Timestamp,
}

#[table(accessor = spell_counter)]
pub struct SpellCounter {
    #[primary_key]
    pub caster: Identity,
    pub last_cast_at: Timestamp,
    pub counter: u32,
}

#[table(accessor = global_cooldown, public)]
pub struct GlobalCooldown {
    #[primary_key]
    pub caster: Identity,
    pub started_at: Timestamp,
    pub duration_ms: u64,
}

#[table(accessor = spell_cooldown, public)]
pub struct SpellCooldown {
    #[primary_key]
    pub key: String,
    #[index(btree)]
    pub caster: Identity,
    pub kind: String,
    pub last_cast_at: Timestamp,
    pub duration_ms: u64,
}

#[table(accessor = recall_slot, public)]
#[derive(Clone)]
pub struct RecallSlot {
    #[primary_key]
    pub owner: Identity,
    /// Empty while Recall is armed and waiting for the next eligible spell.
    pub stored_spell_id: String,
    pub charge_count: u32,
    pub charge_pct: f32,
    pub armed_at: Timestamp,
    pub stored_at: Timestamp,
}

/// Stored lightning critical strikes for the selected Capacitor spell.
#[table(accessor = capacitor_state, public)]
#[derive(Clone)]
pub struct CapacitorState {
    #[primary_key]
    pub owner: Identity,
    pub charge_count: u32,
    pub charged_at: Timestamp,
}

const CAPACITOR_ACTION_ID: &str = "CAPACITOR";
const LIGHTNING_REFLEXES_ACTION_ID: &str = "LIGHTNING_REFLEXES";
const LIGHTNING_REFLEXES_STATUS_GROUP: &str = "LIGHTNING_REFLEXES";
const TRIP_ACTION_ID: &str = "TRIP";
const STALK_ACTION_ID: &str = "STALK";
const STALK_SHADOWSTEP_ACTION_ID: &str = "STALK_SHADOWSTEP";
pub(crate) const CAPACITOR_MAX_CHARGES: u32 = 5;

fn next_capacitor_charge_count(current: u32) -> u32 {
    current.saturating_add(1).min(CAPACITOR_MAX_CHARGES)
}

pub(crate) fn capacitor_charge_count(ctx: &ReducerContext, owner: Identity) -> u32 {
    ctx.db
        .capacitor_state()
        .owner()
        .find(owner)
        .map(|state| state.charge_count.min(CAPACITOR_MAX_CHARGES))
        .unwrap_or(0)
}

pub(crate) fn is_capacitor_charged(ctx: &ReducerContext, owner: Identity) -> bool {
    capacitor_charge_count(ctx, owner) > 0
}

pub(crate) fn charge_capacitor(ctx: &ReducerContext, owner: Identity, charged_at: Timestamp) {
    if active_selectable_ability_for_authored_action(
        ctx,
        owner,
        &AuthoredActionId::new(CAPACITOR_ACTION_ID),
    )
    .is_none()
    {
        return;
    }

    if let Some(mut state) = ctx.db.capacitor_state().owner().find(owner) {
        let next_count = next_capacitor_charge_count(state.charge_count);
        if next_count == state.charge_count {
            return;
        }
        state.charge_count = next_count;
        state.charged_at = charged_at;
        ctx.db.capacitor_state().owner().update(state);
    } else {
        ctx.db.capacitor_state().insert(CapacitorState {
            owner,
            charge_count: 1,
            charged_at,
        });
    }
}

pub(crate) fn consume_capacitor_charge(ctx: &ReducerContext, owner: Identity) -> Option<u32> {
    let charge_count = capacitor_charge_count(ctx, owner);
    if charge_count == 0 {
        return None;
    }
    ctx.db.capacitor_state().owner().delete(owner);
    Some(charge_count)
}

pub(crate) fn clear_capacitor_charge(ctx: &ReducerContext, owner: Identity) {
    ctx.db.capacitor_state().owner().delete(owner);
}

#[table(accessor = spell_definition, public)]
pub struct SpellDefinition {
    #[primary_key]
    pub kind: String,
    pub cooldown_ms: u64,
    pub uses_global_cooldown: bool,
    pub global_cooldown_ms: u64,
    pub cast_time_ms: u64,
    pub behavior: String,
    pub targeting: String,
    pub target_audience: String,
    pub requires_target: bool,
    pub requires_target_los: bool,
    pub aim_radius: f32,
    pub has_aim_radius: bool,
    pub speed: f32,
    pub max_distance: f32,
    pub damage: i32,
    pub damage_type: String,
    pub spawn_forward: f32,
    pub spawn_height: f32,
    pub turn_rate: f32,
    pub update_interval: f32,
    pub duration: f32,
    pub radius: f32,
    pub projectile_radius: f32,
    pub root_duration_ms: u64,
    pub has_root_duration: bool,
    pub status_stack_group: String,
    pub has_status_stack_group: bool,
    pub block_behavior: String,
    pub primary_resource_cost: f32,
    #[default(0i32)]
    pub self_health_cost: i32,
    pub generates_primary_resource_on_cast: bool,
}

#[table(accessor = player_known_spell, public)]
#[derive(Clone)]
pub struct PlayerKnownSpell {
    #[primary_key]
    pub key: String,
    #[index(btree)]
    pub owner: Identity,
    pub spell_id: String,
    pub learned_at: Timestamp,
}

fn player_known_spell_key(owner: Identity, spell_id: &str) -> String {
    format!(
        "{}:{}",
        owner.to_hex(),
        SpellId::new(spell_id)
            .map(|id| id.as_str().to_string())
            .unwrap_or_else(|_| spell_id.trim().to_ascii_uppercase())
    )
}

pub(crate) fn migrate_renamed_spell_storage(ctx: &ReducerContext) -> usize {
    const RENAMED_SPELLS: &[(&str, &str)] = &[("BOOMERANG_ORB", "VAMPIRIC_ORB")];
    let mut migrated = 0usize;

    let known_rows: Vec<_> = ctx.db.player_known_spell().iter().collect();
    for row in known_rows {
        let Some((_, replacement)) = RENAMED_SPELLS
            .iter()
            .find(|(legacy, _)| row.spell_id.eq_ignore_ascii_case(legacy))
        else {
            continue;
        };
        let replacement_key = player_known_spell_key(row.owner, replacement);
        if ctx
            .db
            .player_known_spell()
            .key()
            .find(replacement_key.clone())
            .is_none()
        {
            ctx.db.player_known_spell().insert(PlayerKnownSpell {
                key: replacement_key,
                owner: row.owner,
                spell_id: (*replacement).to_string(),
                learned_at: row.learned_at,
            });
        }
        ctx.db.player_known_spell().key().delete(row.key);
        migrated = migrated.saturating_add(1);
    }

    let item_rows: Vec<_> = ctx.db.item_spell().iter().collect();
    for mut row in item_rows {
        let Some((_, replacement)) = RENAMED_SPELLS
            .iter()
            .find(|(legacy, _)| row.spell_id.eq_ignore_ascii_case(legacy))
        else {
            continue;
        };
        row.spell_id = (*replacement).to_string();
        ctx.db.item_spell().key().update(row);
        migrated = migrated.saturating_add(1);
    }

    migrated
}

pub(crate) fn player_knows_spell(ctx: &ReducerContext, owner: Identity, spell_id: &str) -> bool {
    let Ok(spell_id) = SpellId::new(spell_id) else {
        return false;
    };
    ctx.db
        .player_known_spell()
        .key()
        .find(player_known_spell_key(owner, spell_id.as_str()))
        .is_some()
        || crate::inventory::equipped_spellbook_contains_spell(ctx, owner, spell_id.as_str())
}

pub(crate) fn ensure_player_knows_spell(
    ctx: &ReducerContext,
    owner: Identity,
    spell_id: &str,
    learned_at: Timestamp,
) -> Result<bool, String> {
    let definition = catalog::require_spell_definition_by_str(spell_id)?;
    let spell_id = definition.kind.as_str().to_string();
    let key = player_known_spell_key(owner, spell_id.as_str());
    if ctx
        .db
        .player_known_spell()
        .key()
        .find(key.clone())
        .is_some()
    {
        return Ok(false);
    }

    ctx.db.player_known_spell().insert(PlayerKnownSpell {
        key,
        owner,
        spell_id,
        learned_at,
    });
    Ok(true)
}

#[reducer]
pub fn learn_spell(ctx: &ReducerContext, spell_id: String) -> Result<(), String> {
    ensure_player_knows_spell(ctx, ctx.sender(), spell_id.as_str(), ctx.timestamp)?;
    Ok(())
}

pub(crate) fn spell_definition_ids() -> Vec<String> {
    spell_definitions()
        .iter()
        .map(|definition| definition.kind.as_str().to_string())
        .collect()
}

#[reducer]
pub fn cast_request(
    ctx: &ReducerContext,
    spell_id: String,
    target_id: String,
    aim_x: f32,
    aim_y: f32,
    aim_z: f32,
    cast_input_tick: u32,
    cast_pos_x: f32,
    cast_pos_y: f32,
    cast_pos_z: f32,
    cast_yaw: f32,
    predicted_cast_id: String,
    client_action_seq: u64,
    view_server_time_ms: u64,
) -> Result<(), String> {
    // S8: stamp the press's attacker-view claim for this transaction. Press
    // validation may rewind hostile target poses; scheduled completions and
    // sustains run in later transactions and stay present-time.
    crate::combat::position_history::record_press_view_delay(
        ctx,
        ctx.sender(),
        view_server_time_ms,
    );
    let authored_action_id = AuthoredActionId::new(spell_id.as_str());
    if movement_delivery_for_action_id(spell_id.as_str()).is_some() {
        let Some(ability) =
            active_selectable_ability_for_authored_action(ctx, ctx.sender(), &authored_action_id)
        else {
            return Err(format!(
                "movement ability '{}' is not assigned on the action bar",
                authored_action_id.as_str()
            ));
        };
        let Some(delivery) = movement_delivery_for_ability_id(ability.ability_id.as_str()) else {
            return Err(format!(
                "movement ability '{}' has no movement delivery",
                ability.ability_id
            ));
        };
        crate::world_interactions::cancel_active_world_interaction_for_actor(ctx, ctx.sender());
        return crate::movement_actions::start_movement_delivery_request(
            ctx,
            &ability,
            &delivery,
            target_id,
            cast_input_tick,
            cast_pos_x,
            cast_pos_y,
            cast_pos_z,
            cast_yaw,
        );
    }

    // Targeted spells resolve a server-side target; point-cast spells require aim data.
    let definition = catalog::require_spell_definition_by_str(spell_id.as_str())?;
    let kind = &definition.kind;
    let authored_action_id = AuthoredActionId::new(kind.as_str());
    if action_id_is_selectable_action_bar_action(ctx, &authored_action_id)
        && !spell_cast_is_authorized_by_action_bar_or_spellbook(
            ctx,
            ctx.sender(),
            &authored_action_id,
            kind.as_str(),
        )
    {
        return Err(format!(
            "spell '{}' is not assigned on the action bar",
            kind.as_str()
        ));
    }
    // Authorization is checked against the slotted action; the follow-up it opens up
    // is reached through that same keybind and is never assigned on its own.
    let definition = redirected_followup_definition(ctx, ctx.sender(), definition);
    let kind = &definition.kind;

    crate::world_interactions::cancel_active_world_interaction_for_actor(ctx, ctx.sender());
    if cast_request_executes_immediately(definition.behavior, definition.cast_time) {
        return casting::cast_spell(
            ctx,
            kind,
            target_id.as_str(),
            aim_x,
            aim_y,
            aim_z,
            cast_input_tick,
            cast_pos_x,
            cast_pos_y,
            cast_pos_z,
            cast_yaw,
            predicted_cast_id,
            client_action_seq,
        );
    }

    casting::queue_pending_cast_request(
        ctx,
        kind,
        target_id.as_str(),
        aim_x,
        aim_y,
        aim_z,
        cast_input_tick,
        cast_pos_x,
        cast_pos_y,
        cast_pos_z,
        cast_yaw,
        predicted_cast_id,
        client_action_seq,
    )
}

/// Lightning Reflexes re-armed: pressing the keybind again while the dodge window
/// is up spends it on Trip. The redirect happens after action-bar authorization
/// and before every gameplay gate, so Trip resolves against its own cooldown,
/// cost, targeting and delivery rather than inheriting the buff's. Consuming the
/// avoidance status is what makes the follow-up available exactly once, and it
/// ends the dodge early -- spending your reflexes is the price of the trip.
fn redirected_followup_definition(
    ctx: &ReducerContext,
    caster: Identity,
    definition: &'static SpellRuntimeDefinition,
) -> &'static SpellRuntimeDefinition {
    if definition.kind.as_str() == STALK_ACTION_ID {
        return redirected_stalk_definition(ctx, caster, definition);
    }
    if definition.kind.as_str() != LIGHTNING_REFLEXES_ACTION_ID {
        return definition;
    }
    if !crate::combat::has_active_status_group(
        ctx,
        caster,
        crate::combat::StatusEffectKind::AllAbilityAvoidance,
        LIGHTNING_REFLEXES_STATUS_GROUP,
        ctx.timestamp,
    ) {
        return definition;
    }
    let Some(trip) = catalog::spell_definition_by_str(TRIP_ACTION_ID) else {
        return definition;
    };
    crate::combat::remove_active_status_group(
        ctx,
        caster,
        crate::combat::StatusEffectKind::AllAbilityAvoidance,
        LIGHTNING_REFLEXES_STATUS_GROUP,
    );
    trip
}

/// Stalk with a shadow already out: the same keybind becomes the step to
/// whoever is carrying it. The redirect happens after action-bar authorization
/// and before every gameplay gate, so the step resolves against its own
/// cooldown, cost and SELF targeting rather than the mark's -- which is what
/// lets it be pressed with nothing selected and out of range.
///
/// Unlike Trip, the mark is *not* consumed here. The step can still fail its
/// own validation (the victim left the world, or died between press and
/// resolve), and a shadow burned by a cast that never happened would be a
/// silent loss of the ability. cast_stalk_teleport spends it on execution.
fn redirected_stalk_definition(
    ctx: &ReducerContext,
    caster: Identity,
    definition: &'static SpellRuntimeDefinition,
) -> &'static SpellRuntimeDefinition {
    if crate::combat::active_stalk_mark_target(ctx, caster, ctx.timestamp).is_none() {
        return definition;
    }
    catalog::spell_definition_by_str(STALK_SHADOWSTEP_ACTION_ID).unwrap_or(definition)
}

fn cast_request_executes_immediately(behavior: SpellBehavior, cast_time: Duration) -> bool {
    matches!(
        behavior,
        SpellBehavior::InstantBeam | SpellBehavior::Channel
    ) || cast_time == Duration::ZERO
}

fn spell_cast_is_authorized_by_action_bar_or_spellbook(
    ctx: &ReducerContext,
    owner: Identity,
    authored_action_id: &AuthoredActionId,
    spell_id: &str,
) -> bool {
    active_selectable_ability_for_authored_action(ctx, owner, authored_action_id).is_some()
        || player_knows_spell(ctx, owner, spell_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zero_cast_spells_execute_immediately() {
        assert!(cast_request_executes_immediately(
            SpellBehavior::Projectile,
            Duration::ZERO
        ));
        assert!(cast_request_executes_immediately(
            SpellBehavior::Area,
            Duration::ZERO
        ));
        assert!(cast_request_executes_immediately(
            SpellBehavior::SelfResource,
            Duration::ZERO
        ));
    }

    #[test]
    fn normal_cast_time_spells_still_use_pending_gate() {
        assert!(!cast_request_executes_immediately(
            SpellBehavior::Projectile,
            Duration::from_millis(1200)
        ));
        assert!(!cast_request_executes_immediately(
            SpellBehavior::ApplyStatus,
            Duration::from_millis(500)
        ));
    }

    #[test]
    fn channels_and_release_casts_execute_immediately() {
        assert!(cast_request_executes_immediately(
            SpellBehavior::Channel,
            Duration::from_millis(2500)
        ));
        assert!(cast_request_executes_immediately(
            SpellBehavior::InstantBeam,
            Duration::from_millis(900)
        ));
    }

    #[test]
    fn capacitor_stores_up_to_five_lightning_crits() {
        assert_eq!(next_capacitor_charge_count(0), 1);
        assert_eq!(next_capacitor_charge_count(4), 5);
        assert_eq!(next_capacitor_charge_count(5), 5);
        assert_eq!(next_capacitor_charge_count(u32::MAX), 5);
    }
}

#[reducer]
pub fn release_cast_request(
    ctx: &ReducerContext,
    spell_id: String,
    predicted_cast_id: String,
    client_action_seq: u64,
) -> Result<(), String> {
    let definition = catalog::require_spell_definition_by_str(spell_id.as_str())?;
    casting::release_cast(ctx, &definition.kind, predicted_cast_id, client_action_seq)
}

#[reducer]
pub fn cancel_active_cast_request(
    ctx: &ReducerContext,
    predicted_cast_id: String,
    client_action_seq: u64,
    reason: String,
    cancel_observed_remaining_ms: u64,
) -> Result<(), String> {
    casting::cancel_active_cast_from_input(
        ctx,
        predicted_cast_id,
        client_action_seq,
        reason,
        cancel_observed_remaining_ms,
    )
}

#[reducer]
pub fn publish_spell_definitions(ctx: &ReducerContext) -> Result<(), String> {
    sync_spell_definitions(ctx);
    Ok(())
}

pub(crate) fn sync_spell_definitions(ctx: &ReducerContext) {
    let expected: HashSet<String> = spell_definitions()
        .iter()
        .map(|definition| definition.kind.as_str().to_string())
        .collect();

    for definition in spell_definitions() {
        let key = definition.kind.as_str().to_string();
        let mut row = SpellDefinition {
            kind: key.clone(),
            cooldown_ms: definition.cooldown.as_millis() as u64,
            uses_global_cooldown: definition.uses_global_cooldown,
            global_cooldown_ms: if definition.uses_global_cooldown {
                definition.global_cooldown.as_millis() as u64
            } else {
                0
            },
            cast_time_ms: definition.cast_time.as_millis() as u64,
            behavior: definition.behavior.as_str().to_string(),
            targeting: definition.targeting.as_str().to_string(),
            target_audience: definition.target_audience.as_str().to_string(),
            requires_target: definition.requires_target,
            requires_target_los: definition.requires_target_los,
            aim_radius: definition.aim_radius.unwrap_or(0.0),
            has_aim_radius: definition.aim_radius.is_some(),
            speed: definition.speed,
            max_distance: definition.max_distance,
            damage: definition.damage,
            damage_type: definition.damage_type.as_str().to_string(),
            spawn_forward: definition.spawn_forward,
            spawn_height: definition.spawn_height,
            turn_rate: definition.turn_rate,
            update_interval: definition.update_interval,
            duration: definition.duration,
            radius: definition.radius,
            projectile_radius: definition.projectile_radius,
            root_duration_ms: 0,
            has_root_duration: false,
            status_stack_group: definition
                .status_stack_group
                .as_deref()
                .unwrap_or("")
                .to_string(),
            has_status_stack_group: definition.status_stack_group.is_some(),
            block_behavior: definition.block_behavior.as_str().to_string(),
            primary_resource_cost: definition.primary_resource_cost.max(0.0),
            self_health_cost: definition.self_health_cost.max(0),
            generates_primary_resource_on_cast: definition.generates_primary_resource_on_cast,
        };

        if let Some(existing) = ctx.db.spell_definition().kind().find(key) {
            row.kind = existing.kind;
            ctx.db.spell_definition().kind().update(row);
        } else {
            ctx.db.spell_definition().insert(row);
        }
    }

    let stale: Vec<String> = ctx
        .db
        .spell_definition()
        .iter()
        .map(|row| row.kind)
        .filter(|kind| !expected.contains(kind))
        .collect();
    for kind in stale {
        ctx.db.spell_definition().kind().delete(kind);
    }
}
